### ISSUE TITLE
Missing Libs on Ubuntu 16.04 with Giada 0.13.0

### ISSUE THREAD

**Issue by jhoermann** [monocasual/giada#102]
Hey!
First of all: Thanks for this awesome software!
I get an error with a fresh installed Deb from your download page:
`giada_lin: error while loading shared libraries: librtmidi.so.2: cannot open shared object file: No such file or directory`
Seams like there is a missing lib?

Greetings,
Jochen

**Comment by jhoermann** [comment]
I'm updating to 16.10 right now, there is the 0.12.2 version in the ubuntu repo. Getting the 0.13.0 from the Ubuntu 17.04 packages (not released yet) and installing it.

**Comment by jhoermann** [comment]
That worked! The Package is here: http://packages.ubuntu.com/zesty/giada
Maybe you should write on your download page that its only compatible with Ubuntu 16.10 and higher.

**Comment by monocasual** [comment]
@jhoermann thanks, we'll look into the missing shared libraries bug. Concerning the Ubuntu packages: they strip VST support due to licensing issues.
