### ISSUE TITLE
Improve "Free channel" function

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#105]
The improved "Free Channel" function should:

* remove the sample currently loaded; (ok)
* reset tracker, points, volumes, fades and so on; (ok)
* leave plugins untouched. (todo)

**Comment by bornej** [comment]
Safety warnings could be made optional -> check-box in settings

**Comment by monocasual** [comment]
Fixed in 07c608d0411d6412c05ff8ddd806f7a92705293e.
