### ISSUE TITLE
Use AppImage for Linux builds

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#109]
http://appimage.org/

Experimental version, 1st cut - [Giada-0.14.5-dev-x86_64-AppImage.zip](https://github.com/monocasual/giada/files/1545502/Giada-0.14.5-dev-x86_64-AppImage.zip)

**Comment by SpotlightKid** [comment]
As long as distro package maintainers still get easy access to a versioned source package download, I'm totally down with this.

(I maintain the [AUR package](https://aur.archlinux.org/packages/giada/) for giada.)

**Comment by monocasual** [comment]
Experimental version, 1st cut - [Giada-0.14.5-dev-x86_64-AppImage.zip](https://github.com/monocasual/giada/files/1545502/Giada-0.14.5-dev-x86_64-AppImage.zip)
