### ISSUE TITLE
Doubling/dividing length while recording crashes the app

### ISSUE THREAD

**Issue by bornej** [monocasual/giada#110]
Hi, 
using 0.13.2 on ubuntu:
 doubling/dividing the global length while recording in a sample channel 
is crashing giada with segmentation fault (core dumped).

This action should maybe be forbidden... Looks dangerous ^^

**Comment by monocasual** [comment]
@bornej I can reproduce it by pressing the "rec" button again, i.e. after the recording. I agree, the double/divide option should be disabled during that phase.

**Comment by monocasual** [comment]
Fixed in 1193775781d149ed516b5ac0713f7faff8d02018.
