### ISSUE TITLE
"No channel available for audio recording"

### ISSUE THREAD

**Issue by bornej** [monocasual/giada#111]
Strange behavior with the following test case:
_Single sample channel armed and loaded with a sample :  
pressing record trigs "No channel available for audio recording"
_Two sample channels armed, one loaded with a sample the other empty:
pressing record trigs recording of the audio input in the two channels.
In this case the recording overrides the content of the loaded channel.

ps: I'm new to posting issues on github, hope this makes sense...

**Comment by bornej** [comment]
Also thank you very much for your work! 

I've forked giada and started playing with it. I may start using it for a live performance project. 
I also stumbled upon features I would like to implement (some already in your roadmap) and some bugs...
Could you be interested by contributions?

Thanks again

Best regards.
Jonathan.

**Comment by monocasual** [comment]
>_Single sample channel armed and loaded with a sample :
pressing record trigs "No channel available for audio recording"

That is the correct behavior.

>_Two sample channels armed, one loaded with a sample the other empty:
pressing record trigs recording of the audio input in the two channels.
In this case the recording overrides the content of the loaded channel.

That's a bug! In addition, Giada crashes hard when the recording session is over. 

> ps: I'm new to posting issues on github, hope this makes sense...

You're going great :clap:

Then, 

> Could you be interested by contributions?

Absolutely yes, I am/we are: you are free and encouraged to experiment with Giada and to share the results with us (via pull requests). Thanks!

**Comment by bornej** [comment]
Thanks for your answer.

Related to this issue what would you think of the following features:
_Allow overriding when recording on a loaded channel: [Right-click / free channel] is tedious. 
_Option to arm only one engine at time: Record a single audio input into multiple channel doesn't make much sense...

> Yes I am/we are: you are free and encouraged to experiment with Giada and to share the results with us (via pull requests). Thanks!

I'll certainly get back to you with some pull request then!

**Comment by monocasual** [comment]
> _Allow overriding when recording on a loaded channel: [Right-click / free channel] is tedious.

This is a good point, yet dangerous: you could easily wipe out the previous sample if you forget to un-arm a channel...

_Option to arm only one engine at time: Record a single audio input into multiple channel doesn't make much sense...

This solution would mitigate the "danger" of the previous point. Actually recording into multiple channels was designed with multiple inputs in mind, a feature that will be implemented sooner or later. 

Any thoughts on this?

**Comment by bornej** [comment]
> This is a good point, yet dangerous: you could easily wipe out the previous sample if you forget to un-arm a channel... We could add an optional flag like "allow overriding when recording [...]" in the configuration window.

Either a flag or a new recording mode. 
A three state rec button: (disabled overdub overide) could do the trick...

> This solution would mitigate the "danger" of the previous point. Actually recording into multiple channels was designed with multiple inputs in mind, a feature that will be implemented sooner or later.

That was my understanding of the situation.
We could force the "only one recording track" behaviour until multiple audio input are implemented.

As for the "erasing a track by mistake" danger, it looks like an undo/redo mechanism would be the correct way to address the problem...

If this sounds reasonable to you, I could work on those points as my first contribution. Undo/redo doesn't look like a trivial thing to implement but I could try to get on it.

**Comment by monocasual** [comment]
> A three state rec button: (disabled overdub overide) could do the trick...

Sounds good. We have to find out how to handle this special button with FLTK. 

> We could force the "only one recording track" behaviour until multiple audio input are implemented.

+1 for me.

> If this sounds reasonable to you, I could work on those points as my first contribution. Undo/redo doesn't look like a trivial thing to implement but I could try to get on it.

It would be great! I agree on the undo/redo part, that's too complicated and rooted into the core for now (even for me/us :sweat_smile:).

**Comment by monocasual** [comment]
Closing this one: we have an in-depth discussion of this problem and possible fixes in #224 .
