### ISSUE TITLE
giada doesn't compile if vst is disabled

### ISSUE THREAD

**Issue by ycollet** [monocasual/giada#114]
If use Fedora 24 64 bits.
I configured giada using the following command:

./configure --target=linux --prefix=/opt/giada-devel

During compilation, the following error shows up:

test -f 'src/core/conf.cpp' || echo './'`src/core/conf.cpp
src/core/conf.cpp: Dans la fonction membre « void Conf::sanitize() »:
src/core/conf.cpp:420:6: erreur : « pluginChooserW » was not declared in this scope
  if (pluginChooserW < 640) pluginChooserW = 640;
      ^~~~~~~~~~~~~~
src/core/conf.cpp:421:6: erreur : « pluginChooserH » was not declared in this scope
  if (pluginChooserH < 480) pluginChooserW = 480;
      ^~~~~~~~~~~~~~
src/core/conf.cpp:421:28: erreur : « pluginChooserW » was not declared in this scope
  if (pluginChooserH < 480) pluginChooserW = 480;
                            ^~~~~~~~~~~~~~
Makefile:1699 : la recette pour la cible « src/core/giada-conf.o » a échouée

**Comment by monocasual** [comment]
Fixed in master branch. Thanks!
