### ISSUE TITLE
Support for mono input recording

### ISSUE THREAD

**Issue by datesss** [monocasual/giada#119]
Right now on OSX on version 0.13.2 (1.0) I can only select stereo pairs of input, when it would be nice to be able to select single channels as well (?)

![screen shot 2017-01-30 at 16 11 23](https://cloud.githubusercontent.com/assets/9736319/22441804/e86f3d8a-e706-11e6-90a6-32d931b67d07.png)

**Comment by f3flight** [comment]
Really need mono input for guitar looping

**Comment by monocasual** [comment]
Related: #319, #298

**Comment by monocasual** [comment]
Implemented in 75f716c0e8a64892d84d7f8de312d13d29a9ee47.
