### ISSUE TITLE
VST Support - Update Include path in JUCE.

### ISSUE THREAD

**Issue by therealkitman** [monocasual/giada#121]
Hi,
In order to get giada to compile with vst support I had to edit line 49 in `src/deps/juce/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp`.

From `#include "pluginterfaces/vst2.x/aeffectx.h"` to `#include "../../../../vst/aeffectx.h"` so that the newly created src/deps/vst folder, as mentioned in the install notes [here](https://www.giadamusic.com/documentation/show/compiling-from-source), is found.

Need to update the README.md and/or create an INSTALL.md file as well?

Regards,
Chris.

**Comment by monocasual** [comment]
Hi @therealkitman, that's odd. Are you sure you have the latest VST SDK? Did you copy only `aeffectx.h` in the VST folder (`src/deps/vst`)?

**Comment by therealkitman** [comment]
Hi,
I have the VST3_SDK from Sept 2016 and copied the 3 *.h files from `pluginterfaces/vst2.x` to `src/deps/vst`.

Dumb question but should the folder structure be `/src/deps/vst/pluginterfaces/vst2.x/` containing the 3 header files?

**Comment by monocasual** [comment]
Hmm I think you are right. This is what we have on our building machine:

```
vst
├── aeffect.h
├── aeffectx.h
├── pluginterfaces
│   ├── base
│   │   ├── conststringtable.cpp
│   │   ├── conststringtable.h
│   │   ├── falignpop.h
│   │   ├── falignpush.h
│   │   ├── fplatform.h
│   │   ├── fstrdefs.h
│   │   ├── ftypes.h
│   │   ├── funknown.cpp
│   │   ├── funknown.h
│   │   ├── futils.h
│   │   ├── fvariant.h
│   │   ├── geoconstants.h
│   │   ├── ibstream.h
│   │   ├── icloneable.h
│   │   ├── ierrorcontext.h
│   │   ├── ipersistent.h
│   │   ├── ipluginbase.h
│   │   ├── istringresult.h
│   │   ├── iupdatehandler.h
│   │   ├── keycodes.h
│   │   ├── pluginbasefwd.h
│   │   ├── smartpointer.h
│   │   ├── ustring.cpp
│   │   └── ustring.h
│   ├── gui
│   │   └── iplugview.h
│   ├── test
│   │   └── itest.h
│   ├── vst
│   │   ├── ivstattributes.h
│   │   ├── ivstaudioprocessor.h
│   │   ├── ivstautomationstate.h
│   │   ├── ivstchannelcontextinfo.h
│   │   ├── ivstcomponent.h
│   │   ├── ivstcontextmenu.h
│   │   ├── ivsteditcontroller.h
│   │   ├── ivstevents.h
│   │   ├── ivsthostapplication.h
│   │   ├── ivstinterappaudio.h
│   │   ├── ivstmessage.h
│   │   ├── ivstmidicontrollers.h
│   │   ├── ivstnoteexpression.h
│   │   ├── ivstparameterchanges.h
│   │   ├── ivstplugview.h
│   │   ├── ivstprefetchablesupport.h
│   │   ├── ivstprocesscontext.h
│   │   ├── ivstrepresentation.h
│   │   ├── ivstunits.h
│   │   ├── vstpresetkeys.h
│   │   ├── vstpshpack4.h
│   │   └── vsttypes.h
│   └── vst2.x
│       ├── aeffect.h
│       ├── aeffectx.h
│       └── vstfxstore.h
└── vstfxstore.h
```

I think we can safely remove the .h files in the root directory (i.e. vst/aeffect.h, vst/aeffectx.h, vstfxstore.h), since JUCE looks for those inside `pluginterfaces/vst2.x/`.

**Comment by therealkitman** [comment]
Ah ha!! :)
So I guess a re-wording of the "Compiling from source" instructions will get done. But do I assume from your listing the entire pluginterfaces structure and headers are required too or just the vst2.x contents?

Thanks.

**Comment by monocasual** [comment]
+1 for the re-wording, instructions are misleading! 

As of now only the vst2.x content is used. However you should keep the entire folder structure in light of the upcoming VST3 support.

**Comment by therealkitman** [comment]
Hi,
I experienced the exact same issue with the vst path in another application (Cabbage) when I was building it. Again it related to the `juce_VSTPluginFormat.cpp` not finding `#include "pluginterfaces/vst2.x/aeffectx.h` 

It was fixing it that I realized that the correct path for the vst in giada needs to be `src/deps/juce/modules/juce_audio_processors/format_types/pluginterfaces` and NOT `/src/deps/vst/pluginterfaces/vst2.x/`since the `juce_VSTPluginFormat.cpp` file is looking for pluginterfaces subfolder and contents from it's **current** location.

Makes sense?

**Comment by monocasual** [comment]
Thanks all, documentation updated.
