### ISSUE TITLE
No Windows VSTs listed on linux build

### ISSUE THREAD

**Issue by therealkitman** [monocasual/giada#122]
Hi,
I have successfully built 0.13.3 with vst support on my linux box. But it only lists my linux vsts *.so files from my vst folder but not the Windows vsts *.dll files.

Can I use *.dll vsts?

Thanks,
Chris.

**Comment by monocasual** [comment]
Hi @therealkitman , I quote the docs:

>Plugins must be hosted in compatible environments which means, for example, that an OS X plugin cannot be loaded in the Windows version of Giada and vice versa. Plugins also require binary compatibility with the host: you can't load a 32 bit plugins inside a 64 bit version of Giada and vice versa.

**Comment by therealkitman** [comment]
Ah, thank you. I must RTFM sometime :)
