### ISSUE TITLE
Segfault on linux

### ISSUE THREAD

**Issue by lukeoftheaura** [monocasual/giada#125]
when I try to run giada on linux, I get the following segfault:
```
[init] Giada 0.13.2 - Thu Mar  2 16:45:26 2017
[1]    1907 segmentation fault (core dumped)  giada
```
Any ideas?

EDIT: it only seems to happen half the time.

**Comment by monocasual** [comment]
@lukeoftheaura no idea at all :grimacing: Could you paste here a backtrace of the crash from GDB, please?

**Comment by monocasual** [comment]
Closing this as no feedback from original poster.
