### ISSUE TITLE
recording one shot samples into a loop

### ISSUE THREAD

**Issue by lukeoftheaura** [monocasual/giada#126]
[Feature Proposal]
I think giada should have a feature to record one-shot samples into a loop. For example, playing a drum pattern using one-shot drum samples and then looping it.

**Comment by monocasual** [comment]
@lukeoftheaura sounds good, I'm thinking aloud: why not recording the drum pattern as a set of actions? What are the downsides compared to a sample-based loop?

**Comment by tblrchstr** [comment]
No more activity here since March 2017, closing this.
