### ISSUE TITLE
frameRewind is not reset after oneshot playback

### ISSUE THREAD

**Issue by RomanHargrave** [monocasual/giada#127]
This is a rather bothersome issue that I'm experiencing with Giada, both from Git HEAD and the package on Debian testing (Stretch).

I have several samples configured to trigger on MIDI actions. I am using a MIDI keyboard (a cheap AKM 320) as a trigger device.

When I play a clip using the MIDI trigger and allow it to run out, I can not reliably get it to trigger again - I have to press the key many times in order to get Giada to acknowledge it.

However, if I stop the clip before it runs out (using the same key), I can reliably trigger it again.

I also noticed that, if I play a "stuck" sample using the mouse to click the play button on the sample, it seems to reset it, and I can trigger it again.

This is definitely not an issue with the keyboard, as other MIDI-aware applications work just fine with it.

**Comment by RomanHargrave** [comment]
I should note that the sample type is `oneshot basic`

**Comment by RomanHargrave** [comment]
Debug output from giada at runtime:

```

[KM] MIDI received - 0x90371300 (chan 0)
  >>> keyPress, ch=1 (pure=0x90370000)
[KM] MIDI received - 0x80374000 (chan 0)

[KM] MIDI received - 0x90375A00 (chan 0)
  >>> keyPress, ch=1 (pure=0x90370000)
[KM] MIDI received - 0x80374000 (chan 0)

[KM] MIDI received - 0x90374600 (chan 0)
  >>> keyPress, ch=1 (pure=0x90370000)
[KM] MIDI received - 0x80374000 (chan 0)

[KM] MIDI received - 0x90376200 (chan 0)
  >>> keyPress, ch=1 (pure=0x90370000)
[KM] MIDI received - 0x80374000 (chan 0)

```

On the last line the sample finally played. So Giada did receive events, but ignored them for some unknown reason.

**Comment by RomanHargrave** [comment]
More details -

I've been poking at the Sample Channel source, and the issue appears to have _something_ to do with the logic in `SampleChannel::clear()`:

```c++
void SampleChannel::clear()
{
	/** TODO - these memsets can be done only if status PLAY (if below),
	 * but it would require extra clearPChan calls when samples stop */

		memset(vChan, 0, sizeof(float) * bufferSize);
		memset(pChan, 0, sizeof(float) * bufferSize);

        // This predicate is not true for certain samples _after_ their first activation
	if (status & (STATUS_PLAY | STATUS_ENDING)) {
		tracker = fillChan(vChan, tracker, 0);
		if (fadeoutOn && fadeoutType == XFADE) {
			gu_log("[clear] filling pChan fadeoutTracker=%d\n", fadeoutTracker);
			fadeoutTracker = fillChan(pChan, fadeoutTracker, 0);
		}
	}
}
```

**Comment by RomanHargrave** [comment]
Further research has suggested that `SampleChannel::clear()` is not to blame.

It's actually in some logic in `SampleChannel::sum()` that resets the channel state. After stuffing some more verbose logging in, it's somewhat clear what's happening:

```
[KM] MIDI received - 0x90376500 (chan 0)
[KM] channel branch -> processMaster(); processChannels();
  >>> keyPress, ch=1 (pure=0x90370000)
glue_keyPress(SampleChannel, ctrl=0, shift=0)
glue_keyPress() deferring to ch->start(0, true, ..., ..., false, true)
SampleChannel::start(frame=0, qoQuantize=1, quantize=0, mixerIsRunning=0, forceStart=0, isUserGenerated=1)
... SampleChannel::status(this) = 8
... oneshot handling: normal
[KM] MIDI received - 0x80374000 (chan 0)
[KM] channel branch -> processMaster(); processChannels();
SampleChannel::sum() <normal frame, SINGLE> ending loop - status = STATUS_OFF
SampleChannel::reset(274)

[KM] MIDI received - 0x90375F00 (chan 0)
[KM] channel branch -> processMaster(); processChannels();
  >>> keyPress, ch=1 (pure=0x90370000)
glue_keyPress(SampleChannel, ctrl=0, shift=0)
glue_keyPress() deferring to ch->start(0, true, ..., ..., false, true)
SampleChannel::start(frame=0, qoQuantize=1, quantize=0, mixerIsRunning=0, forceStart=0, isUserGenerated=1)
... SampleChannel::status(this) = 8
... oneshot handling: normal
SampleChannel::sum() <normal frame, SINGLE> ending loop - status = STATUS_OFF
SampleChannel::reset(274)
[KM] MIDI received - 0x80374000 (chan 0)
[KM] channel branch -> processMaster(); processChannels();
```

In the first block - the log output generated from a successful playback  - `SampleChannel::sum()` sets `SampleChannel::status` to `STATUS_OFF` _after_ playback completes, whereas in the following N activations, it is set to `STATUS_OFF` immediately after input is received, which means that something is wrong with the playback tracking, or playback itself.

**Comment by monocasual** [comment]
Hi @RomanHargrave , thanks for the detailed report. We were unable to reproduce the bug in our laboratories (Linux Machine, results may vary). However: what happens if you toggle the "Device does not send NoteOff" checkbox in Configuration Window -> MIDI panel?

**Comment by RomanHargrave** [comment]
@monocasual MIDI input is effectively ignored when that option is enabled
