### ISSUE TITLE
FLAC and Ogg Support

### ISSUE THREAD

**Issue by oparisy** [monocasual/giada#145]
Hi,

while trying to use Giada with samples from LMMS, I systematically got stuck with the "`Unable to read this sample.`" message.

Those samples are all in the FLAC or Ogg format, according to their file extension.

According to #15, compiling binary versions of Giada with support for precisely those formats was discussed in 2013.

What is the status of those formats as of now? Can supporting them out of the box in binary builds be considered?

I tested this on a Windows binary build, under Windows 7 (`giada-0.14.3-win-amd64`).

Regards,
Olivier.

**Comment by monocasual** [comment]
Hi, +1 on this. The time has come for Giada to support FLAC and Ogg out of the box, at least on Mac and Windows. On Linux it depends on how libsndfile was configured. However we will be able provide FLAC+Ogg support on Linux too as soon as #109 is ready.

**Comment by monocasual** [comment]
FLAC and Ogg support added in the next builds.
