### ISSUE TITLE
FTBS with gcc7

### ISSUE THREAD

**Issue by miramikes** [monocasual/giada#147]
On debian system giada fail to built with gcc7.
That's why it has been removed from testing repositories.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853418

**Comment by monocasual** [comment]
Hi there, we are still stuck with GCC 6.x. Would passing the `-Wno-error=format-overflow` flag temporarily solve the issue? I know it's a dirty workaround, meanwhile we could try to upgrade our build environment to see if we can replicate your results...

**Comment by umlaeute** [comment]
it seems that the build-problem on gcc7 is simply fixable by using a larger string buffer to hold the expansion of `%f` (which, as gcc7 correctly notes, can be much larger than 6 characters).

The Debian package now uses [this patch](https://anonscm.debian.org/cgit/pkg-multimedia/giada.git/tree/debian/patches/03-gcc7.patch) to have giada built.

**Comment by monocasual** [comment]
@umlaeute that's a good news. The problem will get fixed naturally when Debian will upgrade Giada to 0.14.x, as we are removing all the char* stuff from the code base, in favor of std::string.

**Comment by umlaeute** [comment]
Debian already ships Giada-0.14.3 (which is the version this bug-report is about)

**Comment by monocasual** [comment]
> Debian already ships Giada-0.14.3 (which is the version this bug-report is about)

Isn't this about 0.13.2? 

From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853418:
> Package: src:giada
Version: 0.13.2~dfsg1-1
Severity: normal
[...]

I keep this open anyway as there are still some char* lying around (as seen in your linked patch).  Thank you all for your feedback.

**Comment by monocasual** [comment]
Should be fixed in e94349023deb291717c02349e500a6e5b25752a7.

**Comment by monocasual** [comment]
@umlaeute is this still an issue?

**Comment by umlaeute** [comment]
indeed it is fixed.

(there's a new bug with a [patch](https://anonscm.debian.org/cgit/pkg-multimedia/giada.git/tree/debian/patches/05-fix_FTBS_on_some_archs.patch) but you are probably already aware of that and while it bears the same label "fails to build on some archs" it is strictly not related to this issue)

**Comment by monocasual** [comment]
Great :ok_hand:. Thanks!
