### ISSUE TITLE
allow to use system-provided `catch`

### ISSUE THREAD

**Issue by umlaeute** [monocasual/giada#151]
Some systems (e.g. Debian, but i guess it's true for most linux distributions) package the `catch` test framework.
In Debian there's even a policy that strongly discourages the use of bundled 3rd party libraries, esp. if they are also available as Debian packages.

It would therefore be nice to (optionally) be able to use this system provided installation of `catch`.

Currently [Debian patches](https://anonscm.debian.org/cgit/pkg-multimedia/giada.git/tree/debian/patches/04-catch.patch) all the sources that use `catch` with something like:

~~~diff
-#include "catch/single_include/catch.hpp"
+#include <catch.hpp>
~~~

It would be great if you could include that upstream, and add `-I$(top_srcdir)/tests/catch/single_include/` to `giada_tests_CPPFLAGS`

Ideally this would be settable via a configure-flag (but in any case it is easier to patch out a single line from `Makefile.am` than having to patch multiple source files).

While you are at it, you might also want to prefix the other local include paths with `$(top_srcdir)`

~~~diff
- -I./src/deps/juce/modules                \
- -I./src/deps/vst                         \
+ -I$(top_srcdir)/src/deps/juce/modules    \
+ -I$(top_srcdir)/src/deps/vst             \
~~~

**Comment by monocasual** [comment]
+1. Added to the 0.14 milestone.

**Comment by monocasual** [comment]
@umlaeute commit 8ce01f5e adds a new configure flag `--enable-system-catch`. If present, the system-provided version will be used. Please let me know if it's OK for you. Thanks!

**Comment by umlaeute** [comment]
looks good
