### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#153]
Development branch: https://github.com/monocasual/giada/tree/cmake-support

Useful links:
* [An Introduction to Modern CMake](https://cliutils.gitlab.io/modern-cmake/)
* [avoid #include <...>](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/platform_dependent_issues/HowToUseExistingOSXFrameworks)

**Comment by tblrchstr** [comment]
Let's get rid of that f****** autotools!

**Comment by monocasual** [comment]
> Let's get rid of autotools as soon as possible!

Getting closer...

**Comment by monocasual** [comment]
Done in 637319d5fbae428dc0aeedadda45e5956d9bd43b et seq.
