### ISSUE TITLE
more colors in waveforn view

### ISSUE THREAD

**Issue by Reaper10** [monocasual/giada#154]
there needs to be more colors in waveforn view

![b174-x9iqaez8nm](https://user-images.githubusercontent.com/8137561/33106781-968ba414-cef9-11e7-8714-b48a5def9bc2.png)
its hard for me to see the waveform

**Comment by monocasual** [comment]
@Reaper10 might be wise to enhance the color contrast with the dark grey background. Thanks for the input.

**Comment by Reaper10** [comment]
you could use the color you use here for the waveform color
![921075_712220938913450_5564566805295454820_o](https://user-images.githubusercontent.com/8137561/34641184-d31ea42c-f2c5-11e7-8e1a-de254096f95f.png)
