### ISSUE TITLE
jack audio support

### ISSUE THREAD

**Issue by Reaper10** [monocasual/giada#158]
Have you thought of adding jack audio support?
http://www.jackaudio.org/

**Comment by monocasual** [comment]
@Reaper10 we already support Jack on Linux :raised_hands:

**Comment by Reaper10** [comment]
what about jack on window and mac you can get jack those os two

**Comment by tank-trax** [comment]
I have the most recent Giada 0.15.1 for Linux (.AppImage, 64 bit) and it does not recognize my USB sound card using Jack. It can only use the sound card if I enable PulseAudio.
