### ISSUE TITLE
[Win] Wrong default position for main window

### ISSUE THREAD

**Issue by Reaper10** [monocasual/giada#165]
you should add the windows title bar to main gui of giada . This way a user can use
minimize  
full screen
close
move giada around the desktop
<img width="467" alt="sketch" src="https://user-images.githubusercontent.com/8137561/34641471-ae24933e-f2ca-11e7-838f-a4af48cd7616.png">

**Comment by monocasual** [comment]
@Reaper10 I suspect your main UI is stuck in the upper left corner. Could you please post a screenshot of the entire desktop?

**Comment by Reaper10** [comment]
<img width="552" alt="sketch" src="https://user-images.githubusercontent.com/8137561/35397851-26dbfa0c-01b6-11e8-8ff8-e5d06da07291.png">

**Comment by monocasual** [comment]
@Reaper10 good. Try to drag the bottom-right corner of the main window: I'm pretty sure the title bar will then show up. If so, there is something wrong with the default window positioning.

**Comment by Reaper10** [comment]
thanks that worked but i would look into fixing so it all ways shows up if i was you

**Comment by monocasual** [comment]
Fixed in 412ddf216e227c09b5bb60d09a3cd303538d7a14.
