### ISSUE TITLE
Please provide AppImage on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [monocasual/giada#173]
https://github.com/monocasual/giada/blob/31cd5f8d77c7f8a46dfe490a011e39c2df66a278/ChangeLog#L30

Please provide the AppImage on GitHub Releases so that it can be included in the AppImageHub central directory of available AppImages. Please do _not_ put the AppImage into an archive file such as a zip. Thanks.

References:
* https://github.com/AppImage/appimage.github.io/pull/312
* https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by monocasual** [comment]
@probonopd thanks for the heads up! We will start publishing appImages on GitHub starting from the next upcoming release (0.14.6).

Zip issue: we need to include some additional stuff in each release (e.g. README file). Is it 100% wrong to archive the .AppImage file in a zip file? I suppose the user would always un-zip it first before launching the application...

**Comment by probonopd** [comment]
> Is it always 100% wrong to archive the .AppImage file in a zip file?

Yes. Thanks for asking.

Please __DO NOT__ put an AppImage into another archive like a `.zip` or `.tar.gz`. While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional `appimaged` daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by monocasual** [comment]
@probonopd the new version 0.14.6 is now available as a "pure" AppImage file [on the official website](https://www.giadamusic.com/download). Previous version [on GitHub](https://github.com/monocasual/giada/releases/tag/v0.14.5) instead. Please let me know if you find something weird. Thanks!

**Comment by probonopd** [comment]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

__electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).__. Please see the `category` key at https://www.electron.build/configuration/linux-other.

References:
* https://github.com/AppImage/AppImageHub/issues/2
* https://travis-ci.org/AppImage/appimage.github.io/builds/354700329#L550

**Comment by monocasual** [comment]
The missing .desktop entry has been added in 0.15.0, binary [here](https://giadamusic.com/data/Giada-0.15.0-x86_64.AppImage).

**Comment by probonopd** [comment]
https://www.giadamusic.com/download/grab/linux-64 seems to be dead, can you please resurrect it?

**Comment by probonopd** [comment]
The AppImage does not run on Ubuntu 14.04 which currently is the oldest still-supported distribution: `AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.8' not found`

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems and especially https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6.

**Comment by monocasual** [comment]
@probonopd we have just [upgraded](https://github.com/monocasual/giada/issues/272) our CI toolbox to Ubuntu Xenial (16.04). This means that a more recent version of libstdc++ is now required. Is this OK with the AppImage environment?

**Comment by probonopd** [comment]
As long as you are building on Xenial and are not adding e.g., PPAs that are pulling in newer versions of libstdc++ than what comes with Xenial, your AppImage should be able to run on Xenial and hence all still-supported releases of Ubuntu.
