### ISSUE TITLE
giada freezes when opening plugins

### ISSUE THREAD

**Issue by lytex** [monocasual/giada#176]
In Giada 0.14.5, when I try to open any plugins from /usr/lib/vst or whatever, giada freezes while loading them.
It seems to freeze after or while loading the last plugin in a given directory. Deleting specific plugins that may cause giada to fail is not helpful since giada always fails in the last plugin.
After that, I forcefully close the program and giada has loaded all (I think) the programs

**Comment by tblrchstr** [comment]
No feedback, closing this.
