### ISSUE TITLE
Feature request: sync to external midi clock

### ISSUE THREAD

**Issue by scitoast** [monocasual/giada#177]
I realize the docs explicitly say that Giada can act only as a midi clock master.  But this is a glaring omission.  If Giada -- which seems otherwise a very attractive project -- is to become a "real" tool it needs to midi sync to an external clock.  

Every performer out there has their own preference for how to do midi clocking. I use a hardware workstation as a master clock for a number of software and hardware based sound tools.  If a software  won't sync to an external clock, I don't consider it a mature enough package to be useable.

**Comment by ghendrix** [comment]
I hope this happens soon!! I need this too!

**Comment by monocasual** [comment]
Help wanted! :sunglasses:

**Comment by tomek-szczesny** [comment]
I'll give it a try. Stay tuned!

**Comment by gvnnz** [comment]
Done in development branch `midi-sync-fix`. Closing.
