### ISSUE TITLE
High DPI support + svg icons

### ISSUE THREAD

**Issue by ghost** [monocasual/giada#178]
On high DPI monitors, it's difficult to see the text and to click the buttons. Everything appears very small.

FLTK doesn't really take care of this, but [this article](https://www.oyranos.org/2016/01/high-dpi-with-fltk/index.html) seems to indicate that there's a solution.

**Comment by monocasual** [comment]
+1. In addition to that I would also include converting all raster icons/images to svg paths. FLTK  1.4 will have built-in support for svg files (http://seriss.com/people/erco/fltk/#Fl_SVG_Image).

**Comment by JPenuchot** [comment]
Is this feature still on the roadmap ?

**Comment by monocasual** [comment]
Yep, sooner or later. Or, better, as soon as FLTK 1.4 will be released. We need this before releasing version 1.0.

**Comment by rnkn** [comment]
Does FLTK 1.4 support Retina/High DPI on OS X? This page seems ambiguous to me: https://www.fltk.org/doc-1.4/drawing.html

>  ...but not on Mac OS X and for retina displays, where one drawing unit corresponds to two pixels.

Does that mean everything pixel-based in FLTK will still be blurry, or is this solved with SVG?

**Comment by monocasual** [comment]
@rnkn sorry for the shameful delay. Honestly I don't know yet. I suppose FLTK will take care of text and widget scaling. Images will be blurry if not in SVG format.

**Comment by tay10r** [comment]
[This](https://www.fltk.org/doc-1.4/classFl__SVG__Image.html) seems to indicate that FLTK supports SVG now (as mentioned, version 1.4).

**Comment by oldcastlehq** [comment]
+1
What's the status? 

Sorry guys, but it's quite hard to work on Giada for a long time using a HDPI laptop. I hope you can improve this.

**Comment by monocasual** [comment]
@oldcastlehq FLTK 1.4 is [under active development](https://www.fltk.org/images/monthly_commit_activity.svg), let's keep our fingers crossed...

**Comment by steevithak** [comment]
I've run into this issue as well. I have a 4k system and giada is tiny, about 3" high and 4" wide on my 27 inch monitor. It also doesn't seem to respect the font size set by Fedora and uses a tiny font.

**Comment by gvnnz** [comment]
DPI adjustment How-to in FLTK 1.4: https://github.com/fltk/fltk/issues/371#issuecomment-1032030182

**Comment by gvnnz** [comment]
Done in https://github.com/monocasual/giada/commit/c8e09854180c23b8f22e01ff646b176fd5d7dfab and later, closing.

**Comment by Tamriel** [comment]
I'm using Giada 1.0.0 on Wayland with a 4k monitor, and it's not high DPI :/

**Comment by gvnnz** [comment]
@Tamriel Did you set up the UI scaling correctly? Settings -> Misc -> UI scaling

**Comment by Tamriel** [comment]
I increased the UI scaling, since without it everything was very small. No matter that, everything is a bit pixelated.

**Comment by gvnnz** [comment]
@Tamriel can you please share a screenshot? Thanks!

**Comment by Tamriel** [comment]
![grafik](https://github.com/user-attachments/assets/f33edeb2-bfd8-408e-8678-2765575f40d0)
