### ISSUE TITLE
New proposed Logo for GIADA

### ISSUE THREAD

**Issue by k-syusteem** [monocasual/giada#182]
<H2>Hi, I am a graphic designer.</H2>

I am a graphic designer, for your project "Giada" I want to contribute a logo. This is free! may i do it?

Does "Giada" already have an official logo?

If not, I will design for free to this project. I have designed it and done it, here is the final result rather than the design:

<h3>- Model variations</h3>

![variasions model](https://user-images.githubusercontent.com/38687140/39665341-94d77478-50bc-11e8-969a-da4aa3b06c60.png)

<h3>- Background variations</h3>

![background versions](https://user-images.githubusercontent.com/38687140/39665347-c5fc4a06-50bc-11e8-81c1-86b81df15137.png)

<h4>The design concept of this logo:</h2>

- Symbol "G" 
- A character rather than a disc-disc music 
- Having a human and community symbol

<h3>Give feedback if you like it, and I hope my contribution can be used for the project "Giada".</h3>

<i>Regard : @k-syusteem </i>

**Comment by tay10r** [comment]
That's great work! I agree that there needs to be a better logo. This definitely fits the shoe. What do you think @monocasual?

**Comment by k-syusteem** [comment]
Thank you @tay10r, hope this logo is accepted and I will be proud!

**Comment by monocasual** [comment]
Excellent work @k-syusteem ! Personally I really like the monochrome version - we are a bunch of minimalistic freak here :smirk: Also, currently we lack of a good logo icon - we only have a logotype which is getting older with time. I'll schedule this one for the 0.15 series.

**Comment by k-syusteem** [comment]
Hi @monocasual, I agree with you. I prefer the 3rd version of my design. But I made some versions so you can also judge other versions. 

![nice](https://user-images.githubusercontent.com/38687140/39826581-5e713f74-53df-11e8-87ee-98714e275267.png)


Thank you for accepting this assignment, I also provide the editable file here: https://drive.google.com/drive/folders/157qc3mugESJg8EkMOoIR-FjB6CGkPspV?usp=sharing

**Comment by hugoaboud** [comment]
Amazing work! I would personally love to see the UI evolving along with this minimalist greyscale verison, also with the color details proposed on #166 (the helm example is great, color only where it's needed).

**Comment by monocasual** [comment]
Hey @k-syusteem , we are about to integrate the new logo 2.0 in the app and on the website. Could you please share here a link to the font in use? If you can't (not free) or you prefer to keep it private, we would need to convert the brand payoff "Your hardcore loopmachine" as well. Thanks again!

**Comment by tblrchstr** [comment]
@monocasual the brand payoff is no longer required in the new layout. No problem on the website either, where the payoff uses the giadamusic.com font. IMHO we can close this one.
