### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by marcelklehr** [monocasual/giada#185]
Hey there,
I'm really excited to try this piece of software!

Sadly, I haven't been able to get it to work, yet.
I installed v0.14.5 on ubuntu via apt and it tells me on startup that my soundcard is incorrectly configured. When I open the settings, I can select jack as system, but no devices are listed as available in either MIDI or sound panel, even though I have an internal soundcard, plugged in an external one and a MIDI keyboard, both via USB.

Any help is appreciated :)

**Comment by monocasual** [comment]
hi @marcelklehr , I encourage you to grab v0.15.0 from the [official download page](https://giadamusic.com/download): we provide AppImage for Linux, so you are a double-click away from running it. Let me know if the issue persists on the newer version.

**Comment by marcelklehr** [comment]
I think I found the cause. I hadn't started JACK :)
