### ISSUE TITLE
JUCE -Wclass-memaccess (GCC 8)

### ISSUE THREAD

**Issue by hugoaboud** [monocasual/giada#187]
GCC 8 introduced a new warning that won't allow Juce to compile with _-Wall -Werror_.
Refer to https://github.com/WeAreROLI/JUCE/issues/394.

A temporary workaround is adding _-Wno-error=class-memaccess_ to Makefile.am and generating the Makefile again.

**Comment by monocasual** [comment]
Related to #359 . Moving to 0.17.0.

**Comment by monocasual** [comment]
Fixed with #359 .
