### ISSUE TITLE
Ratio-based zoom calculation in Action Editor

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#188]
Currently the Action Editor computes the zoom level with silly integer value. Use the float one as implemented in the Sample Editor.

**Comment by tblrchstr** [comment]
Development branch: https://github.com/monocasual/giada/tree/ratio-based-ae

**Comment by monocasual** [comment]
Merged into master branch in 989225f95e2ecf4310cc9c38114e8207e0ceef51.
