### ISSUE TITLE
Wrong sample rate conversion when patch rate != system rate

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#192]
I have a project with samples @ 44100 Hz running in an environment (JACK-based) @ 48000. The internal Action Recorder detects the difference correctly and starts to convert all actions:

```
[recorder::updateSamplerate] systemRate (48000) != patchRate (44100), converting...
[recorder::updateSamplerate]    oldFrame = 0, newFrame = 0
....
```
However, samples are not converted. They stay @ 44100 Hz, playing faster.

**Comment by monocasual** [comment]
Fixed in d99f9ed0.
