### ISSUE TITLE
compilation error rtMidi

### ISSUE THREAD

**Issue by tank-trax** [monocasual/giada#195]
after typing make it builds for a bit and the stops with tihis error:

src/core/giada-kernelMidi.o: In function `giada::m::kernelMidi::openInDevice(int)':
giada-0.15.1-src/src/core/kernelMidi.cpp:152: undefined reference to `RtMidiIn::RtMidiIn(RtMidi::Api, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)'

src/core/giada-kernelMidi.o: In function `giada::m::kernelMidi::openOutDevice(int)':
giada-0.15.1-src/src/core/kernelMidi.cpp:107: undefined reference to `RtMidiOut::RtMidiOut(RtMidi::Api, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Makefile:2235: recipe for target 'giada' failed
make: *** [giada] Error 1

**Comment by monocasual** [comment]
Hey @tank-trax , what version of RtMidi and compiler are you using?

**Comment by tank-trax** [comment]
./configure --target=linux --enable-vst
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for g++... g++
checking whether we are using the GNU Objective C++ compiler... no
checking whether g++ accepts -g... no
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for pthread_exit in -lpthread... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking FL/Fl.H usability... yes
checking FL/Fl.H presence... yes
checking for FL/Fl.H... yes
checking rtmidi/RtMidi.h usability... yes
checking rtmidi/RtMidi.h presence... yes
checking for rtmidi/RtMidi.h... yes
checking jansson.h usability... yes
checking jansson.h presence... yes
checking for jansson.h... yes
checking sndfile.h usability... yes
checking sndfile.h presence... yes
checking for sndfile.h... yes
checking samplerate.h usability... yes
checking samplerate.h presence... yes
checking for samplerate.h... yes
checking X11/xpm.h usability... yes
checking X11/xpm.h presence... yes
checking for X11/xpm.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands

**Comment by tank-trax** [comment]
I have 64 bit Linux Mint 18.3 with KXStudio ropositories. 

rtMidi -> Latest Release (31 August 2017): Version 3.0.0 from https://www.music.mcgill.ca/~gary/rtmidi/

**Comment by tank-trax** [comment]
I managed to compile the Docker Giada, and it sees the USB card with the proper Midi and Audio connections and it loads up in Jack Connect.

However the app crashes if I do anything else.

Add new plugin -> undefined symbol: _ZN10Fl_Browser8textsizeEi
Load new sample -> undefined symbol: _ZN10Fl_Browser8textsizeEi
Edit Midi Actions -> undefined symbol: _ZN17Fl_Display_Device14display_deviceEv

**Comment by tblrchstr** [comment]
I'm closing this, since the best way to compile Giada now is through the Docker image. @tank-trax  please open a new issue if the crash still persists.

**Comment by tank-trax** [comment]
The docker image instructions  are not clear. 

After building the container
I run giadaDocker ./configure target=linux and it responds with

bash: giadaDocker : command not found

is giadaDocker a folder?

where is it?

**Comment by tank-trax** [comment]
it builds but it always crashes once I click on load sample

this app built via docker is unstable on my system where everything else is very stable...

the app image doesn't recognized JACK and can only use PulseAudio

I hope you get Jack support proper in the appImage

good luck
