### ISSUE TITLE
Mac OS 10.9.1 giada 0.15.1 crash on launch

### ISSUE THREAD

**Issue by jmarks** [monocasual/giada#199]
See debug log (Please note, I never got a confirmation e-mail from the forum app so posted here):

Process:         giada_osx [2436]
Path:            /Users/USER/Downloads/*/giada.app/Contents/MacOS/giada_osx
Identifier:      giada_osx
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [206]
Responsible:     giada_osx [2436]
User ID:         501

Date/Time:       2018-08-18 15:58:56.916 -0700
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID:  9578DB88-C0AB-6B3D-85AF-2D5B25CCDEB5

Sleep/Wake UUID: 6218039F-135A-4134-9D1A-6142D64BE311

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00000000f0001019

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x00000000f0001000  rbx: 0x00007fff5fc3c520  rcx: 0x0000000000000001  rdx: 0x00007fff5fbff200
  rdi: 0x00007fff5fc3c520  rsi: 0x0000000000000001  rbp: 0x00007fff5fbff1f0  rsp: 0x00007fff5fbff1f0
   r8: 0x00007fff5fc20b8c   r9: 0x0000000000000ec0  r10: 0x0000000100000000  r11: 0x00007fff5fc3c5f0
  r12: 0x00007fff5fc3a6d8  r13: 0x00007fff5fc259b6  r14: 0x00007fff5fc259d1  r15: 0x00007fff5fc3c520
  rip: 0x00007fff5fc1064c  rfl: 0x0000000000010206  cr2: 0x00000000f0001019
  
Logical CPU:     5
Error Code:      0x00000004
Trap Number:     14

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 14735
    thread_create: 0
    thread_set_state: 0

Model: MacPro3,1, BootROM MP31.006C.B05, 8 processors, Quad-Core Intel Xeon, 2.8 GHz, 4 GB, SMC 1.25f4
Graphics: ATI Radeon HD 2600 XT, ATI Radeon HD 2600, PCIe, 256 MB
Memory Module: DIMM Riser B/DIMM 1, 2 GB, DDR2 FB-DIMM, 800 MHz, 0x0000, 0x000000463732353642363145363830304600
Memory Module: DIMM Riser B/DIMM 2, 2 GB, DDR2 FB-DIMM, 800 MHz, 0x0000, 0x000000463732353642363145363830304600
Bluetooth: Version 5.2.7f4 15858, 3 services, 22 devices, 1 incoming serial ports
Network Service: Ethernet 2, Ethernet, en1
PCI Card: ATI Radeon HD 2600, Display Controller, Slot-1
Serial ATA Device: ST9320325ASG, 320.07 GB
Serial ATA Device: Hitachi HDS721010KLA330, 1 TB
Serial ATA Device: WDC WD5000AAKS-65A7B0, 500.11 GB
Serial ATA Device: M4-CT064M4SSD2, 64.02 GB
Parallel ATA Device: PIONEER DVD-RW  DVR-112D
Parallel ATA Device: PIONEER DVD-RW  DVR-112D
USB Device: Eleven Rack
USB Device: FreeAgent FW
USB Device: USB2.0 Hub
USB Device: Fishman TriplePlay
USB Device: iLok
USB Device: USB2.0 Hub
USB Device: Backup+ Desk
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
FireWire Device: built-in_hub, Up to 800 Mb/sec
FireWire Device: ProjectMix, M-Audio, Up to 400 Mb/sec
Thunderbolt Bus:

**Comment by monocasual** [comment]
Hey, looks like your debug output got truncated somewhere. Could you run Giada in a debugger to get advanced information?

**Comment by tblrchstr** [comment]
No feedback since August 23, closing this.
