### ISSUE TITLE
Windows builds on AppVeyor, Windows CI

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#204]
Depends on #153 .

**Comment by tblrchstr** [comment]
TravisCI now provides a Window build environment: https://docs.travis-ci.com/user/reference/windows/

**Comment by monocasual** [comment]
Or, even better: [GitHub Actions](https://github.com/features/actions)

**Comment by gvnnz** [comment]
CI implemented on GitHub Actions, closing.
