### ISSUE TITLE
Hover box hints

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#207]
Based on http://www.fltk.org/doc-1.3/classFl__Tooltip.html.

**Comment by monocasual** [comment]
PR: #323 .

**Comment by monocasual** [comment]
@tomek-szczesny wrote in #364:
> I am pretty sure I've seen such a request before, but couldn't find it.
>
> Anyway, Tooltips. I just made sure FLTK does indeed support them ;) They could appear after a really long-ish time, like 2 > seconds, so they don't get into a way of experienced users.
>
> Here's why:
>
> It's such a popular feature I honestly expected them just to be there,
Giada has no built-in help system,
Giada online docs tend to get outdated when new features are introduced,
It's by far the easiest way to provide help within the program itself.
Honestly I don't know what the three-dot button next to record arm does ;)
EDIT: Okay I see this is work in progress. I found a command line switch "-to" but it doesn't seem to work.
