### ISSUE TITLE
No overdub?

### ISSUE THREAD

**Issue by miguescri** [monocasual/giada#216]
Hi, there.

First of all, congratulations for the nice work.

Then, I'm pretty new to Giada, but after reading the docs and playing around with it, I can't find the way of overdubing on a sample after it has been created. Of course you can overdub at the creation time, but how do you add further sounds to the sample?

Is there something that I'm missing?

Thanks.

**Comment by monocasual** [comment]
hi @miguescri , thanks for your kind words ;) Yes, the overdub was not implemented on purpose to avoid mistakes during live recording (i.e. overwriting the current sample). Despite that, I think the feature could be added with some adjustments, for example: disable the rec button once the sample has been created, to be re-enabled if overdub is desired. I'll wrap my head around this, I'm sure @tblrchstr will provide useful insights...

**Comment by miguescri** [comment]
I think the behaviour of allowing overdub should be set through configuration; if we require to press a couple of buttons to be able to overdub once the initial sample has been created, it would make uncomfortable live sampling it.

In my case I downloaded Giada to get into beatbox loopstation, where overdubing needs to be as smooth and intuitive as possible. I don't know about the needs of others but I guess there are more scenarios where this feature is needed.

**Comment by tblrchstr** [comment]
The idea of audio overdub is cool and correct. You can overdub actions currently, why not samples?

**Comment by monocasual** [comment]
Related: #224

**Comment by monocasual** [comment]
Overdub implemented in 2bf696ec38df76dce50936b197d6fd230ff1f4cd .
