### ISSUE TITLE
New logo designer - rename! 

### ISSUE THREAD

**Issue by foways** [monocasual/giada#220]
This is what I yesterday designed the logo for the Giada project, when my github id was "k-syusteem" and then I agreed to turn everything into "foways". So I ask the Giada project owner to change the name there from K-syusteem to Foways. Thank you!

**Comment by monocasual** [comment]
Will do! Did you change your github page as well?

**Comment by foways** [comment]
@monocasual Yes, I changed everything but all my projects are still intact.

**Comment by monocasual** [comment]
Reopening this, we need to change your name on the main website.

**Comment by foways** [comment]
Yes, I see it hasn't changed and it's still the first name!

**Comment by monocasual** [comment]
Done! Please let me know if there is something missing :wink:
