### ISSUE TITLE
Solo_on/solo_off MIDI lightning never triggered

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#222]
https://giadamusic.com/forum/viewtopic.php?f=2&t=1510

`Channel::sendMidiLmute()` is never called anywhere.

**Comment by tomek-szczesny** [comment]
I got that fixed. Please allow me some more time to prepare a pull request.

**Comment by monocasual** [comment]
WIP in https://github.com/monocasual/giada/pull/223

**Comment by tblrchstr** [comment]
Fixed, merged and released in 0.15.3. Thanks again ;)
