### ISSUE TITLE
Saving mangles midi loops

### ISSUE THREAD

**Issue by hasjo** [monocasual/giada#227]
On Linux, whenever I save a patch or project it mangles the midi loops I have set up.

For example, I'll have a 2 section loop running with a note on every beat. I'll save the project/patch (the option there doesn't seem to matter), and when I load it back up the patterns are stretched to twice as long, with weird repeats after the length of the loop. Attached are a pair of screenshots showing this behavior.

BEFORE
![before](https://user-images.githubusercontent.com/6157052/49479976-97716880-f7ea-11e8-83d9-db91d94e2f80.png)

AFTER
![after](https://user-images.githubusercontent.com/6157052/49479975-96d8d200-f7ea-11e8-8361-3f83e89233d1.png)

**Comment by monocasual** [comment]
Interesting. We are rewriting the Action Recorder from scratch (very old and troublesome code in there), so I'm pretty sure this one will get fixed with the update.

**Comment by monocasual** [comment]
Should be fixed now in master branch, commit 7d630f932c3a5a42b4c4addd568db78434c24f18 (and beyond).
