### ISSUE TITLE
Freeing sample channel being played produces continuous loud tone

### ISSUE THREAD

**Issue by terencode** [monocasual/giada#233]
__Reproduction Steps:__
1. Add a new sample channel
2. Record something on it
3. Play as a loop
4. While playing, select the *Free channel* option 
5. The previously recorded material is gone, but a loud tone replaces it until you delete the channel.

---
giada 0.15.2
ArchLinux

**Comment by tomek-szczesny** [comment]
Could you check that on the latest Giada release, 0.15.3?

**Comment by terencode** [comment]
It doesn't seem to happen with 0.15.3.
I'll re-open if I face the same issue.
