### ISSUE TITLE
Menu buttons clickable surface is too small and pushed to the bottom

### ISSUE THREAD

**Issue by terencode** [monocasual/giada#235]
The buttons file/edit/config/about are only clickable when the mouse is hovering their bottom half.
Considering the buttons already have a small surface area, reducing it by half makes them really hard to press.

---
ArchLinux
giada 0.15.3

**Comment by monocasual** [comment]
Confirmed, the entire surface should be clickable. Thanks!

**Comment by tblrchstr** [comment]
Fixed in `solid-arch` branch.

**Comment by monocasual** [comment]
Merged and fixed.
