### ISSUE TITLE
Please merge the branch freebsd-support

### ISSUE THREAD

**Issue by yurivict** [monocasual/giada#244]
I can't update the port now because ```master``` changes are incompatible with the branch.
The PR was mergeable into ```master``` when I submitted it.

**Comment by monocasual** [comment]
I think you can merge it "graphically" - i.e. via GitHub interface on the `freebsd-support` branch. Can you confirm this?

**Comment by yurivict** [comment]
There are conflicts now. Such merges should be done by the upstream maintainer, and should be merge with the ```master``` branch.
Otherwise, there is not much value in the OS-specific branch if it isn't updated/needs constant attention.
It should be merged into ```master```.

**Comment by luzpaz** [comment]
I think @yurivict has a relevant argument that can apply to any package maintainer

**Comment by monocasual** [comment]
`freebsd-support` branch updated and ready for the merge :+1: Please let me know if there's something missing!

**Comment by yurivict** [comment]
I verified, this branch builds fine. Thank you!
