### ISSUE TITLE
Gray out bpm value when in JACK client mode

### ISSUE THREAD

**Issue by Zer0-** [monocasual/giada#245]
I cannot set the bpm in Giada. I click the bpm which is default to 120, set 100 for example and press "OK". It is still at 120. Here's a screen capture of exactly what I did:

https://home.volguine.com/files/simplescreenrecorder-2019-03-13_14.13.43.mkv

**Comment by terencode** [comment]
Are you using Jack as audio backend?

**Comment by Zer0-** [comment]
Yes I am.

**Comment by Zer0-** [comment]
Yes I am.

**Comment by terencode** [comment]
Please refer to #245 Giada doesn't have an option to request to be the tempo master, you need to control it from the application which has it (Carla for example).

**Comment by Zer0-** [comment]
Gotcha

**Comment by tomek-szczesny** [comment]
Graying out the unavailable option wouldn't hurt though.
