### ISSUE TITLE
v0.15.4 re-tagged

### ISSUE THREAD

**Issue by dvzrv** [monocasual/giada#249]
Hi! I'm maintaining giada on Arch Linux and seem to have built this software from a tarball of the sha512sum `53575620d13d2bab57ab2431dfcc8967bcc6a1109e788bc52bef638268f314a75f8c9a6de2301de31fbc0eca578874e641d14bf6e26e02f4c156d970d36345dd` on March 10th.

However, I just received a [bug report](https://bugs.archlinux.org/task/62691), that the checksum has changed.

The release page now states, [that version 0.15.4 got tagged on March 22nd](https://github.com/monocasual/giada/releases/tag/v0.15.4).

As I retrieve new versions only from this github project, I'm fairly certain, that I didn't commit a wrong version string to [the package script](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/giada).

As I was able to build giada on March 10th already, I assume, that the tag has been changed on March 20th.
Diffing my tarball against the giada repository at tag `v0.15.4` indeed reveals the changes from March 20th (although the ChangeLog says 2019-03-22 ;-) ) as the only difference:

```
diff -ruN giada-0.15.4/ChangeLog giada/ChangeLog
--- giada-0.15.4/ChangeLog      2019-03-08 20:39:18.000000000 +0100
+++ giada/ChangeLog     2019-05-21 17:34:50.794588288 +0200
@@ -12,7 +12,8 @@
 --------------------------------------------------------------------------------
 
 
-0.15.4 ---
+0.15.4 --- 2019 . 03 . 22
+- New record-on-signal option for input and action recording
 - Initial support for plug-ins with mono I/O buses
 - PluginHost refactoring
 - Smart pointers for Wave and Plugin objects
```

Please don't re-tag already released software. It breaks reproducible builds downstream and trust in the validity and security of the tarball.
If a tag should indeed point to another commit hash, just update the version and release again. That is far more coherent and safe!

**Comment by monocasual** [comment]
hey @dvzrv , I guess something went wrong last time. We definitely don't want to mess with tagged releases. Thank you for the heads up!
