### ISSUE TITLE
"One-shot press" channel mode doesn't work if triggered via mouse

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#262]

**Comment by monocasual** [comment]
Partially fixed in c45da37a6e8bff9adb56150b8117b4baad18c1e7. The issue is still present if the channel is triggered with the mouse.

**Comment by monocasual** [comment]
Depends on #277 .

**Comment by monocasual** [comment]
Fixed in development version, `non-virtual-channels` branch.
