### ISSUE TITLE
Avoid vector allocation in midiDispatcher::processChannels_

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#279]
Currently `midiDispatcher::processChannels_` performs some dirty std::vector-based tricks in order to overcome the limitations imposed by #277. This implies memory allocation on the MIDI thread. Remove the std::vector trick and just call the `c::` functions directly.

**Comment by monocasual** [comment]
`c::` functions may take a boolean flag that tells whether to lock the model or not.

**Comment by monocasual** [comment]
Fixed in development version, `non-virtual-channels` branch.
