### ISSUE TITLE
Head/tail mismatch in loop endless samples

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#280]
Steps to reproduce it:

1. load a sample in a sample channel set to loop endless mode;
1. play the sample, then stop it (channel status is "ending");
1. play the sample again.

Expected:

The sample should play from the very beginning, i.e. from frame 0.

Actual:

The sample starts at frame N, with N > 0.

**Comment by monocasual** [comment]
Fixed in development version, `non-virtual-channels` branch.
