### ISSUE TITLE
Please merge the branch freebsd-support with master

### ISSUE THREAD

**Issue by yurivict** [monocasual/giada#281]
The only problem is that I can't update the port with OS-specific patches being in another branch.

Otherwise I don't see the need to a special branch for freebsd. It works fine as it is.

Thanks.

**Comment by monocasual** [comment]
hi @yurivict , rebase & push done. Thanks!

I suppose we are ready to officially include FreeBSD support now. Just give us some time to release version 0.16.0 - it will take no more than a couple of weeks.

**Comment by yurivict** [comment]
Thanks!

Could you please also merge this PR: https://github.com/monocasual/giada/pull/282

These changes are needed to compile the current master.

**Comment by monocasual** [comment]
Merged #282 to `freebsd-support`.
