### ISSUE TITLE
can't build vst plugin on Linux

### ISSUE THREAD

**Issue by swestlake** [monocasual/giada#283]
here the release of 0.16 release builds the standalone binary but it does not build the vst plugin.. 

the modules folder from JUCE-5.3.2.tar.gz was copied to the juce folder under giada 

the configure command was then used,
"./configure --target=linux --enable-vst"

after compiling, the standalone binary is able to run successfully but there is no vst plugin to be found..

**Comment by monocasual** [comment]
This is correct: no VST plug-ins are shipped with Giada, you have to download them separately.
