### ISSUE TITLE
Ability to set libsamplerate quality for pitch control

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#288]
Currently the quality flag is hardcoded (to ultrafast). Solution: reuse the same value for sample rate conversion on file import.

**Comment by gvnnz** [comment]
Apparently there's something wrong with live resampling when quality is != ultrafast. Needs investigation, I'm moving this to 0.18.

**Comment by gvnnz** [comment]
WIP in `samplerate-quality` branch.

**Comment by gvnnz** [comment]
Done in 4b1af27 .
