### ISSUE TITLE
AudioBuffer improvements towards C++17

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#289]
* memset -> std::fill
* memcpy -> std::copy
* Move semantics with proper constructors instead of copyData, moveData

**Comment by keryell** [comment]
Replace C++11 with C++17 in the issue description :-)

**Comment by keryell** [comment]
While C++20 would add a lot of Pythonesque simplification with ranges, in the meantime we could use https://github.com/ericniebler/range-v3
This a well supported and packaged library.

**Comment by monocasual** [comment]
@keryell I like the idea of adding ranges support to the AudioBuffer. On the other hand I'd gladly avoid another dependency, if possible. For now I would start by fixing the missing move semantics, waiting for the big switch to C++20 in the (near) future.

**Comment by gvnnz** [comment]
Depends on #348
