### ISSUE TITLE
Select audio interface does not show all input channels

### ISSUE THREAD

**Issue by evertdhont** [monocasual/giada#298]
**Issue:**
I have a Zoom R16 audio interface (2 output channels, 8 input channels), when selecting it as an input and output device, no input or output channels are detected. And when I close the config window, the input and output devices revert back to the standard microphone of my PC/mac.

**What I've tried:**
- I have tried running it on Windows 10 (using DirectSound, WASAPI and ASIO), none of them showed any input channels when the Zoom R16 audio interface was selected.
- I also tried running Giada on macOS High Sierra, v10.13.6. With the CoreAudio system selected, but experienced the same exact behavior as on Windows (no channels detected)

**Comment by monocasual** [comment]
Thanks for reporting the issue. Could you please paste here the debug output? [Here's how to enable it](https://giadamusic.com/forum/viewtopic.php?f=2&t=2).

**Comment by monocasual** [comment]
Is this still an issue with Giada 0.16.3?

**Comment by monocasual** [comment]
No feedback, closing.
