### ISSUE TITLE
[Windows] Allow for alternative config file location

### ISSUE THREAD

**Issue by teknowledgist** [monocasual/giada#299]
I would be nice to have the ability to specify a different location for the config file.  In particular, if the location could use system variables (e.g. `%appdata%` in Windows) to allow every user their own configuration.

Think:  a music lab where the computer is locked down to already installed/approved apps and each user can only affect their own profile.  Currently, Giada can't work in this situation.

Thanks!

**Comment by monocasual** [comment]
I believe that `%appdata%` in Windows should be the default choice. The configuration file is located next to the binary file at the moment: not a great solution.

**Comment by gvnnz** [comment]
Hey @luzpaz , this has been scheduled for version 0.26 and will be tackled soon. Thanks!

**Comment by luzpaz** [comment]
Thanks! Once this is tackled then downstream window repos will be green light to distribute giada :+1:

**Comment by gvnnz** [comment]
Done in 63ce90769797f32acf072b9e9bb5ff677def09c3.
