### ISSUE TITLE
Giada causes system to hang/log out

### ISSUE THREAD

**Issue by hellocatfood** [monocasual/giada#302]
**System**
Ubuntu 19.10 on Dell XPS 13 with Wayland

**Giada Version**
0.15 and 0.16.1 appimage

At seemingly arbitrary points during my usage of Giada the who system will crash (screen goes black) and then I'm taken back to the login screen. Since it causes a whole system crash I'm not sure how to find the root cause of the crash

**Comment by monocasual** [comment]
@hellocatfood quick question: are you using JACK by any chance?

**Comment by hellocatfood** [comment]
Yes I am.

I'm also currently trying to analyse my log file to see if my guess about Wayland is a cause

**Comment by monocasual** [comment]
> Yes I am.

Interesting. We are experiencing weird errors when running Giada + JACK. Could you please try again with another audio backend (i.e. ALSA or PulseAudio if available)? Thanks!

**Comment by hellocatfood** [comment]
Tried with ALSA on Wayland and used it for about 30 minutes and had no crashes at all. The audio was a bit choppy though.

**Comment by monocasual** [comment]
In our previous experiments JACK seems to somehow clash with FLTK at some point. I'm still not 100% sure about this, though.

That said, `resizable-channels` branch features some changes that might be related to the JACK crash. Feel free to check it out, or wait until we merge it onto master (in the next few days).

**Comment by hellocatfood** [comment]
I think I'll wait until it's merged into master and then report back

**Comment by monocasual** [comment]
`resizable-channels` branch merged.

**Comment by gvnnz** [comment]
@hellocatfood any feedback on this?

**Comment by hellocatfood** [comment]
I'm testing on a Dell XPS 15 with NVIDIA drivers and all seems to work now version 0.18.0). I don't have the original machine (xps 13 with wayland) so can't test on that
