### ISSUE TITLE
giada error when building the version v0.16.1-4-g24e19f03

### ISSUE THREAD

**Issue by muziker** [monocasual/giada#309]
I'm getting this error when trying to build v0.16.1-4-g24e19f03
>g++ -DPACKAGE_NAME=\"giada\" -DPACKAGE_TARNAME=\"giada\" -DPACKAGE_VERSION=\"0.16\" -DPACKAGE_STRING=\"giada\ 0.16\" -DPACKAGE_BUGREPORT=\"giadaloopmachine@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"giada\" -DVERSION=\"0.16\" -DNDEBUG=1 -DHAVE_LIBPTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I.  -I./src  -I./tests/catch2/single_include  -D__LINUX_ALSA__ -D__LINUX_PULSE__ -D__UNIX_JACK__    -std=c++14 -Wall  -g -O2 -MT src/core/giada-midiDispatcher.o -MD -MP -MF src/core/.deps/giada-midiDispatcher.Tpo -c -o src/core/
'
src/core/midiDispatcher.cpp: In function ‘void giada::m::midiDispatcher::{anonymous}::learnPlugin_(giada::m::MidiEvent, int, giada::ID, std::function<void()>)’:
src/core/midiDispatcher.cpp:332:23: error: ‘plugins’ is not a member of ‘giada::m::model’
  model::onSwap(model::plugins, pluginId, [&](Plugin& p)
                       ^~~~~~~
src/core/midiDispatcher.cpp:332:46: error: ‘Plugin’ has not been declared
  model::onSwap(model::plugins, pluginId, [&](Plugin& p)
                                              ^~~~~~
src/core/midiDispatcher.cpp: In lambda function:
src/core/midiDispatcher.cpp:334:5: error: request for member ‘midiInParams’ in ‘p’, which is of non-class type  int’
   p.midiInParams[paramIndex] = e.getRawNoVelocity();
     ^~~~~~~~~~~~
make: *** [Makefile:3564: src/core/giada-midiDispatcher.o] Error 1
'

**Comment by monocasual** [comment]
It looks like you are building without VST support. Could you please try again with the `--with-vst` parameter enabled?

**Comment by muziker** [comment]
By the way, are you developing on the main branch, and so the tagged versions considered the release versions? Or is everything on the HEAD supposed to be ok for compilation?

**Comment by monocasual** [comment]
> By the way, are you developing on the main branch, and so the tagged versions considered the release versions? Or is everything on the HEAD supposed to be ok for compilation?

Good question. Quoting the [docs](https://giadamusic.com/documentation-development-git-setup):

> We put the most experimental code in a feature branch. When the new feature is completed, we merge/rebase the feature branch into master and we drop the feature branch. However the master branch does not necessarily point to the latest release. For that, we use tags, whenever a new release is ready.
