### ISSUE TITLE
"Your soundcard isn't configured correctly. Check the configuration and restart Giada." No way to edit config

### ISSUE THREAD

**Issue by dzoba** [monocasual/giada#31]
Hey folks!  Thanks for making what has the potential to be cool (haven't got to try it yet though).

Looks like I have two problems:

1) I get this error message when I start Giada, however, its just the message.  There isn't any way for me to edit the config.

2) I don't really know what would be causing this error to begin with.

![image](https://cloud.githubusercontent.com/assets/857664/4243295/8f9bba9a-3a0a-11e4-9bf8-457208a0f814.png)

**Comment by alex-bender** [comment]
Hello, I'm having the same error but can not find the logs file. Could you help with troubleshooting? Thanks

**Comment by alex-bender** [comment]
Actually this message disappears after I change system to PulseAudio,
while ALSA and Jack doesn't work.
System Ubuntu 18 x64

**Comment by tomek-szczesny** [comment]
Hi @alex-bender !

First of all, make sure you have JACK installed in the first place. It is not installed on Ubuntu by default (unless you use Ubuntu Studio).
I can't tell why ALSA doesn't work, but my guess is that it is busy serving PulseAudio.
So, yeah, unless you actually wanted to use JACK and have it installed, there is nothing to worry about and proceed with PulseAudio.

The logs are activated in config window, misc tab.

Hope it helps!

**Comment by alex-bender** [comment]
Thanks for support! I think that your guess is right, that ALSA is serving PA.
Would be great to have a pointer to the place where people can read about possible solutions, because from the first sight it's a bit unclear what to do with that error.
Could you please share any good resources/materials about sound system(s) on ubuntu (for example) because I really like to play with sounds but often getting bored (actually just out of time) resolving opaque issues?

**Comment by tomek-szczesny** [comment]
This is a global Linux thing, not restricted to Ubuntu only.
Try this: [https://linuxhint.com/guide_linux_audio/](https://linuxhint.com/guide_linux_audio/)
In a nutshell, PulseAudio is de facto standard sound system for casual users. JACK is more flexible and generally has better performance, but some applications (such as Firefox) support PulseAudio only. OSS is pretty much dead.
There is a way to use JACK with PulseAudio together via "bridges", but for now, just stick to PulseAudio until you see any reason to go JACK instead. 
Also, for general questions, feel free to join [Giada Forum](https://www.giadamusic.com/forum/) instead. :)

**Comment by alex-bender** [comment]
Thanks, will check it out!
