### ISSUE TITLE
Use nested namespace definitions (C++17)

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#310]
E.g.:

```c++
namespace giada::m::whatever
{
};
```

Instead of 

```c++
namespace giada {
namespace m {
namespace whatever
{
};
```

Available in C++17 and greater.

**Comment by keryell** [comment]
I started this as a detail of https://github.com/monocasual/giada/pull/402

**Comment by tomek-szczesny** [comment]
I just hope that merging this into my branch won't be a nightmare. ;)

**Comment by gvnnz** [comment]
Done, closing.
