### ISSUE TITLE
./configure: command not found

### ISSUE THREAD

**Issue by neauoire** [monocasual/giada#313]
The repo doesn't come with a `.configure` file, but a `.configure.ac` file, is it an error in [the docs](https://www.giadamusic.com/documentation-compiling-from-source)?

```
derulin@villamoirai ~/R/E/giada> ./configure --target=linux
./configure: command not found
```

**Comment by monocasual** [comment]
You need to run the `autogen.sh` script first, as suggested [here](https://www.giadamusic.com/documentation-development-git-setup). Doc pages are in the middle of a huge update, so thank you for your patience :)
