### ISSUE TITLE
[linux/jack]  incorrect number of input channels

### ISSUE THREAD

**Issue by moonshaadow** [monocasual/giada#314]
Hi.
When choosing the input channels, Giada makes no difference between midi and audio ports. Result is: For a 2 audio outputs app, Giada shows the app as a 3-outputs app, I thinks it's including the midi output. It results to an error at restart if we choose the wrong pair. 

By the way, is there any progress in #247 ?

> "Designed for live performances"

If we can route only one instrument at once, it is not very designed for live.
Regards.

**Comment by monocasual** [comment]
Hi @moonshaadow , thanks for reporting. IO channel counting and everything related is managed by the RtAudio library. We have just updated it to 5.1.0 so you might want to give it a spin just in case you encountered a bug in the previous version.

Regarding #247: I scheduled it for version 1.x. Multi-I/O is mandatory for live performing, but we need a solid I/O and audio rendering architecture first (work is in [progress](https://github.com/monocasual/giada/milestone/11) on that front).

**Comment by moonshaadow** [comment]
Thanks for your answer.
The problem is happening with Giada-0.16.1-x86_64.AppImage. By the way, I realize that the About widget says "version 0.16.0". Should I presume there is no 0.16.1 AppImage or is this an error on the site ? 
Maybe I will build from last git, but how have I to proceed : should I update RtAudio to 5.1 before build Giada ?

Very happy to see you're working on multi-I/O !

**Comment by monocasual** [comment]
I suggest you to build from git as this will become the official way in the very near future. RtAudio is now a git submodule, so it's just a matter of `git submodule init` and similar. Let me know how it goes :)

**Comment by moonshaadow** [comment]
I have successfully built giada 0.16.2 on ubuntu 18.04. The problem is solved .

**Comment by monocasual** [comment]
Thanks @moonshaadow for your feedback!
