### ISSUE TITLE
[Windows] No icon on executable giada_win.exe

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#317]
> This is not exaclty a bug, but I noticed the file giada_win.exe doesn't have an icon, so Windows shows up its default icon. No attractive at all. I really like Giada logo and I think it would make a great icon for the exe. Plus, it will look nice on any start up painel.

https://giadamusic.com/forum/viewtopic.php?f=2&t=1566&p=2532#p2532

**Comment by gvnnz** [comment]
Can't reproduce on Windows 11, closing.
