### ISSUE TITLE
v0.16.2.1 crashes

### ISSUE THREAD

**Issue by muziker** [monocasual/giada#318]
I've checked out the tag v0.16.2.1, and once i've set the audio and midi configuration to use jack, the next run, it segfaults.

**Comment by muziker** [comment]
Also when --enable-vst is on, the compilation does not complete

**Comment by muziker** [comment]
Tried to compile this from the release page tarball. The tarball relies on json and juce libraries, but those are pulled into the project by using git submodule update --init --recursive. The tarball is unable to use git to do this, and there isn't anything that tells the user how to do this. Maybe give instructions on how to get these libraries for those who don't know how to do this.

**Comment by monocasual** [comment]
@muziker thanks for reporting. We are in the middle of a huge tarball transition (see also #153 and #315), so something might be missing. For now I suggest to stick to the GitHub version, unless you're a packager. I'll look into the --enable-vst problem shortly.

**Comment by tomek-szczesny** [comment]
This one is probably solved by now, as most probably is the same as #368.

**Comment by monocasual** [comment]
@muziker please reopen this if the issue persists.
