### ISSUE TITLE
0.16.2.2: Failing to build vst plugin

### ISSUE THREAD

**Issue by dvzrv** [monocasual/giada#328]
Hi!

When trying to build from the newly established source tarball, I also tried building the vst plugin (`--enable-vst`).

This currently leads to a failing build though. This is the build log:
[giada-0.16.2.2-build.log](https://github.com/monocasual/giada/files/4452761/giada-0.16.2.2-build.log)

**Comment by monocasual** [comment]
Oh I remember this one. Which version of gcc are you using?

**Comment by dvzrv** [comment]
Yeah, this seems to be [the same problem as helm is having](https://github.com/mtytel/helm/pull/233).

```
$ gcc --version
gcc (Arch Linux 9.3.0-1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by monocasual** [comment]
Tested right now with
```
gcc (Debian 8.3.0-6) 8.3.0
```
and it builds OK. Maybe gcc 9.x is more picky about it?

**Comment by dvzrv** [comment]
Yeah, for gcc >= 9.1.0 this commit (https://github.com/WeAreROLI/JUCE/commit/4e0adb2af8b424c43d22bd431011c9a6c57d36b6) has to be backported.

**Comment by monocasual** [comment]
BTW, Is VST necessary for you? If I remember correctly Linux distros used to keep VST disabled due to some licensing issues. Can I publish a new point release as requested by eeickmeyer in #315  ?

**Comment by dvzrv** [comment]
Well, VST is problematic, if using the steinberg sdk and having to host it as a package (this is not allowed).
On Linux there are several ways to emulate vst though, with replacement headers and the JUCE way of doing things also seems to work.

That being said: Sure, release away! We can fix this later.

**Comment by hfiguiere** [comment]
The build failure is because of JUCE. I have a patch as I said in #324.

See: https://github.com/flathub/flathub/pull/1626/files#diff-63233e04f2dfa20f73841db33649d8fb

[giada-juce.patch.txt](https://github.com/monocasual/giada/files/4843250/giada-juce.patch.txt)

**Comment by gvnnz** [comment]
@dvzrv @hfiguiere is this still an issue?

**Comment by hfiguiere** [comment]
the current version no longer build VST2 because the VST2 SDK isn't available anymore.

As for that JUCE problem, it has been solved a while ago in JUCE.
