### ISSUE TITLE
BPM not changing via Jack

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#331]
Source: https://www.giadamusic.com/forum/viewtopic.php?f=2&t=1570

>  I change the tempo using Carla [with Jack] but the tempo number in Giada doesn't change and the beat counter keeps going at the same speed.

**Comment by terencode** [comment]
Isn't this a duplicate of #238 ?

**Comment by tblrchstr** [comment]
@terencode the title is a bit misleading, my bad. The problem here is that changing BPM in a Jack client (Carla, in the example) doesn't propagate back to Giada.

**Comment by monocasual** [comment]
Fixed in development branch `non-virtual-channels`.
