### ISSUE TITLE
Giada 0.16.2.2-1 on Fedora 32 - Your sound card isn't configured correctly

### ISSUE THREAD

**Issue by steevithak** [monocasual/giada#333]
I tried out Giada on my new Fedora 32 setup. Did a 'dnf install giada' and now have giada-0.16.2.2-1.fc32.x86_64. I started it and immediately got the error message saying "Your sound card isn't configured correctly" with no other explanation about what that means. I assume it means I need to do something on Giada's config menu. I see the Configuration -> Sound System -> System field supports ALSA, Jack, and Pulseaudio. I started with Pulseaudio since that's what Fedora uses but no luck. Then I tried ALSA and Jack, still nothing. What else do I need to configure to get sound out it? The sound hardware and drivers within Fedora do actually work fine with all other audio programs I use  - browsers, Celluloid, Kdenlive, Rhythmbox, etc. If it matters,  I'm running on an Intel NUC nuc8i7beh.

**Comment by monocasual** [comment]
Hey @steevithak , could you please paste here the log output? [This](https://giadamusic.com/forum/viewtopic.php?f=2&t=2) is how to enable it.

**Comment by PrinzNika** [comment]
I am having the same issue for jack. Alsa seems to work. 
Dont find the log file though. in the .giada folder is only the giada.conf

**Comment by steevithak** [comment]
Sorry for the delay in getting back. I tried Giada again today and I'm no longer getting the error. In the time since I had the problem, I've also installed Hydrogen, Rosegarden and a few other sound related tools. I'm guessing something I did during that process must have magically fixed things (?) but Giada seems to be working now. I tried logging but since I'm no longer getting the error, it didn't report anything of interest.

**Comment by monocasual** [comment]
@steevithak that's weird! Giada logs the list of available/recognized devices on start up, so it might be useful to double-check it in case of I/O trobules.

By the way, @PrinzNika logging works also in the terminal: main window -> config -> "misc" tab -> debug messages -> to standard output.

**Comment by gvnnz** [comment]
No feedback, closing.
