### ISSUE TITLE
Record on signal should be disabled when sequencer is running

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#336]
"Record on signal" is great to kick off a new live looping session, that is when the sequencer is initially off, but there's no practical need for it afterwards. On top of that, the whole live set gets screwed if you accidentally press the 'input recording' button while the "record on signal" is on and the sequencer is playing, since such mode puts the sequencer back in "wait" mode. The "record on signal" mode should therefore be disabled when the sequencer is running to avoid such mistakes. Users can still press the input recording button to live record audio during the live session.

**Comment by monocasual** [comment]
Done in 65d0e7720d9fcf5c3515d3766ce122fb35b46be3.
