### ISSUE TITLE
Feature Request // Sync to Jack as Slave

### ISSUE THREAD

**Issue by PrinzNika** [monocasual/giada#337]
I don't know if it hast been brought up before and it probably has but I was wondering why giada only acts as jack transport sync master. Whats the reason? I would really love to integrate it in my setup but I have already a stable workflow and giving such great control to this application doesnt seem right to me.

**Comment by monocasual** [comment]
This is an important feature we want to ship before version 1.0 (issue #238, closing this as duplicate). Thanks for the heads-up!
