### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by pafri** [monocasual/giada#34]
Could be the localization support available? I would contribute that translators way.

**Comment by monocasual** [comment]
Hi pafri, the i18n implementation is in our roadmap and will be shipped soon. Thank you for your interest, stay tuned for updates :)

**Comment by julian-weinert** [comment]
@monocasual I'd like to offer German l10n!

**Comment by monocasual** [comment]
@julian-weinert sure, thanks for your help!

**Comment by tblrchstr** [comment]
Might be useful for printing text: http://www.fltk.org/doc-1.3/classFl__Multiline__Output.html

**Comment by gvnnz** [comment]
Done in e83eb94a9cb1a4b86377a67b26956fd34da8270f, closing.
