### ISSUE TITLE
Smarter Clock increment

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#341]
There is no need to increment clock frame by frame (e.g. clock::incrCurrentFrame). Let's make it advance by a block and then compute bars/beats/first beats accordingly.

**Comment by tomek-szczesny** [comment]
How much is a "block"? 
I think that sending MIDI sync relies on counting frames, no?

**Comment by monocasual** [comment]
Audio block is just another name for the audio buffer, which is usually made of 8 / 16 / 32 / 64 / ... frames (aka samples). The idea here - still pretty draft at this point - is to advance things by blocks and parse each block for events. For example, say the rendering engine is parsing the block `[256, 512)` and suppose there's a sequencer event at frame `270`: the engine should be able to detect it and trigger the action/MIDI message accordingly.

**Comment by gvnnz** [comment]
Done in 0.17.2, closing.
