### ISSUE TITLE
Numerical volume and pan controllers for all types of channels

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#345]
Currently, the pan knob and the numerical volume input are available only for Sample Channels through the Sample Editor. Both controllers are useful also for MIDI channels. 

Add these controllers (+ future tools such as IO routing and such) in a new subwindow ("Channel setup" maybe?).

**Comment by tomek-szczesny** [comment]
How would a volume and pan control work on MIDI channel? Would it affect NoteOn velocity?

**Comment by monocasual** [comment]
The volume and pan would only affect the final stream, after all effects and MIDI instruments have been rendered to the audio buffer.

**Comment by gvnnz** [comment]
Done in 61938f29d548ff459eb35dab3e9d52953b34ecf3.
