### ISSUE TITLE
0.16.3 fails to compile: implicit instantiation of undefined template 'std::__1::basic_string

### ISSUE THREAD

**Issue by yurivict** [monocasual/giada#347]
```
./src/glue/sampleEditor.h:60:17: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string name;
                ^
```

Did you forget to include ```<string>```?

**Comment by monocasual** [comment]
@yurivict weird. What compiler are you using?

**Comment by yurivict** [comment]
clang

**Comment by yurivict** [comment]
It's not weird. Every module that uses some class std::{cls} has to have ```#include <{cls}>``` in it.

**Comment by monocasual** [comment]
> It's not weird. Every module that uses some class std::{cls} has to have `#include <{cls}>` in it.

Indeed. We are building on GCC 8.3.0 and it compiles fine, though. It seems the inclusion is done somewhere else - e.g. in some standard library files I guess. That could explain the difference with clang. 

I've pushed a fix for this. Does it work for you?

**Comment by yurivict** [comment]
This solved the problem.

Thank you.
