### ISSUE TITLE
Need to keep pressing pad on Novation Launchpad S

### ISSUE THREAD

**Issue by blablack** [monocasual/giada#35]
I noticed something with the Novation Launchpad S.

In a Sample Channel, I can set the 'key press' in the Midi Setup to learn the first button of my Novation Launchpad S - this works.

But, if I now want to trigger the sample to start, I need to keep pressing the pad on the Launchpad.
It would be handy to have the option to just toggle the 'Key Press' by pressing the button once only.

**Comment by blablack** [comment]
I forked the code in my github account:
https://github.com/blablack/giada

I'll create a branch for this functionality - this should be easy enough to have a look at.

**Comment by blablack** [comment]
After further investigation, the issue is due to the fact that the Launchpad S doesn't have a Note Off.
Every press and release of a pad are a Note On with velocity at 0 or 127.

**Comment by monocasual** [comment]
Hi, actually we dealt with several other devices with velocity=0 as Note Off. Unfortunately, at the moment we skip the velocity byte during the MIDI learn. We could enable a further check for those devices and map velocity=0 to a key_release event.

**Comment by blablack** [comment]
Hi, I posted a fix yesterday in my fork https://github.com/blablack/giada/tree/midi_toggle

In a nutshell, I grab the note as usual during the MIDI learn step. I added a setting in the midi configuration that says the device does not send Note Off.
If that setting is activated, Giada simply ignore Note On with Velocity 0.

If you could check the code and tell me if it's acceptable - I created a git pull request as well.

**Comment by blablack** [comment]
Ok, I implemented it this way now:
- There is a general setting to set if the devices sends NoteOff or not
- If it does then it's business as usual
- If it doesn't, Midi learn step includes the velocity byte 

Everything else works the same.

I tested it with the Launchpad, works like a charm :)

The pull request is there: https://github.com/monocasual/giada/pull/38

**Comment by monocasual** [comment]
Feature merged into master branch. I can confirm it works like a charm :) Thanks!
