### ISSUE TITLE
Start MIDI channels after action recording

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#350]
When I record actions on a Sample Channel, the 'R' mode is automatically switched to "ON" as soon as the action recording session is over. I would expect the same from MIDI channels.

This feature is also extremely handy while live performing: I don't want to record my MIDI events AND THEN press play on the MIDI channel.

**Comment by monocasual** [comment]
Implemented in 5aa35f235a67864ba6f39198378c2d70e09445ab.
