### ISSUE TITLE
Save project stretches action timing

### ISSUE THREAD

**Issue by gedobbles** [monocasual/giada#355]
When saving a project to file, the action timing seems to be stretched all over the maximum number of 32 beats.
To reproduce: load a sample, change beats to 8, make actions so it plays every beat, save project, load project.
After that, the sample plays only every fourth beat. If you open the action editor, you can see the 8 beats spread over all of the editable area.

EDIT: I was wrong assuming the actions were spread evenly: When I set up 32 beats and fill all of them with actions, the actions are not stretched by a factor of 4 but a bit more. so the beats are on beat 0, beat 4.5, beat 8.75, beat 13.25, ...
A look into the .gptc file revealed, that the actions are stored in a time measure of frames so the format isn't even compatible when using a soundcard at  a different sample rate! <- this is why you can't change the bpm after loading a project right? Please do some improvement on the file format!

However the actions stored in the file are even multiples of my samplerate therefore I think the problem might be in the load file process.

**Comment by monocasual** [comment]
Hey @gedobbles,

>  you can't change the bpm after loading a project right?

This is definitely a bug: you should be able to change the bpm after loading a project! Back to the timing issue: I'm pretty sure this is related to the sample rate change. Could you please upload a test project that reproduces the problem along with the multiple sample rates in use? Thanks!

**Comment by gedobbles** [comment]
I just saw that I can't change the bpm at all anymore with my AppImage.
I don't have too much time right now, but I will check things out maybe at the weekend. I can send you the AppImage via E-Mail if you want, I didn't change anything just ran the program (Linux x86_64)

**Comment by gedobbles** [comment]
Heres a sample project that loads badly (should hit the drum every beat and did before saving
[test.gprj.zip](https://github.com/monocasual/giada/files/4858450/test.gprj.zip)
)

**Comment by monocasual** [comment]
@gedobbles Your project definitely shows a wrong behavior and I was able to reproduce it in Giada 0.16.3.1 (the AppImage you are using). The bug has been fixed in #192 and #354 and the fix will be included in v.0.16.4 coming soon. Thanks for reporting!

**Comment by monocasual** [comment]
Reopening as fixed in development version.
