### ISSUE TITLE
Shrinking beats can glitch the output

### ISSUE THREAD

**Issue by tomek-szczesny** [monocasual/giada#361]
Hi,
Let me first offer an apology for vanishing from any activity with Giada for so long. My life got complicated, but hopefully I'm on the right track to eventually fulfill my commitments towards MIDI support.

Anyway, I started Giada today to reacquaint with her, and found an odd behavior when shrinking beats using a "Beat operator".
Let's say we have a looped sample in basic loop mode, lasting exactly 4 beats. I expanded number of beats to eight. During normal playback, the sample would be played exactly 2 times per each cycle. However when I shrink beats back to four, here's what happens:
If the current frame is anywhere within the first 4 beats, it works as expected,
If the current frame is within beats that are about to be truncated, the marker (clock?) goes to the very beginning ( I assume frame 0?). 
This way, frame position practically always gains some offset against the already playing sample and ruins the beat consistency in general. When another cycle is finished, it forces the sample to start from the beginning, which is too obvious not to notice.

What seems like a clean solution to me is to recalculate a new frame position as (old_frame_position % new_frames_in_loop) every time any change is made to beats/bars structure. I think this has to do with _recomputeFrames__ but it was hard to deduce anything by browsing code on GitHub.

For the sake of completeness, this occurs on the most recent version of Giada, on Linux, using PulseAudio.

Have a good day!

**Comment by tomek-szczesny** [comment]
I took a slightly more careful peek at the code on a coffee break and from what I can tell the frame position is never taken care of during expanding or shrinking of beats.
I think what happens is that after shrinking, on next run of _incrCurrentFrame()_, it simply realizes the current frame is beyond the framesInLoop and goes back to zero.

So my guess is that a little add-on at the end of _recomputeFrames__ should do the trick. I am no C++ whiz, so take it with a shovel of salt:


```
int f = currentFrame_.load();
f = f % c.framesInSeq;
currentFrame_.store(f);

```

**Comment by monocasual** [comment]
Hey @tomek-szczesny , long time no see! It's nice to have you back on track :wink:

Issue confirmed, and it's a long standing one. You fix should be enough I guess. I'm scheduling this for the 0.17.x series.

**Comment by tomek-szczesny** [comment]
Alrightee, I guess I'll make it my comeback exercise this weekend. I'll have to set up a coding environment again and refresh my git skills. ;)

**Comment by tomek-szczesny** [comment]
Okay, I've spent way too many hours setting up all this, but the bad news are that the proposed change doesn't seem to work. Frankly it seems that it does nothing. Oh well, gotta dig deeper...

**Comment by tomek-szczesny** [comment]
Yass! Pull request is ready. :)

**Comment by monocasual** [comment]
PR: https://github.com/monocasual/giada/pull/373
