### ISSUE TITLE
[Request] Tooltips!

### ISSUE THREAD

**Issue by tomek-szczesny** [monocasual/giada#364]
I am pretty sure I've seen such a request before, but couldn't find it. 

Anyway, Tooltips. I just made sure FLTK does indeed support them ;) They could appear after a really long-ish time, like 2 seconds, so they don't get into a way of experienced users.

Here's why:
1. It's such a popular feature I honestly expected them just to be there,
2. Giada has no built-in help system,
3. Giada online docs tend to get outdated when new features are introduced,
4. It's by far the easiest way to provide help within the program itself.
5. Honestly I don't know what the three-dot button next to record arm does ;)

EDIT: Okay I see this is work in progress. I found a command line switch "-to" but it doesn't seem to work.

**Comment by sezanzeb** [comment]
It also doesn't work for me. No tooltips visible

**Comment by tomek-szczesny** [comment]
Duplicate of #323

**Comment by monocasual** [comment]
@tomek-szczesny  agreed on all points you mentioned. Let's discuss this in the original issue #207 .
