### ISSUE TITLE
stream linker button missing

### ISSUE THREAD

**Issue by sezanzeb** [monocasual/giada#369]
https://www.giadamusic.com/documentation-live-sampling

"the button between the input and the output meter ![image](https://user-images.githubusercontent.com/28510156/88455451-ac928380-ce75-11ea-8766-b075cd8acd0c.png) located on the main window"

this is what I have:

![image](https://user-images.githubusercontent.com/28510156/88455461-bd42f980-ce75-11ea-9447-047c7f1cf3fc.png)

**Comment by tomek-szczesny** [comment]
It is present on current AppImage (Right now on my OS with PulseAudio only), but indeed I remember it was missing when I compiled Giada myself. Where did you get your copy, and what version is it?

**Comment by sezanzeb** [comment]
Mine is compiled from 851f1128d39fc27d2e52d5f037f990876b84090f

**Comment by sezanzeb** [comment]
the appimage has it

**Comment by tomek-szczesny** [comment]
That must be it, for some reason it's not present outside AppImage.

**Comment by monocasual** [comment]
Yes, the stream linker is not included when compiled without VST support. Do you guys think it's useful even without plug-ins?

**Comment by tomek-szczesny** [comment]
I think that's exactly what @sezanzeb wanted. :)
Also, I think it's better to leave the button even if it barely does anything, to avoid confusion where did it go.

**Comment by sezanzeb** [comment]
I don't think I need it, but since it was described I wanted to try it.

**Comment by monocasual** [comment]
Done in f1e4ce07143f75712c0f1825d2f4854bd0b8038f.
