### ISSUE TITLE
GUI corrupted when window maximised

### ISSUE THREAD

**Issue by blablack** [monocasual/giada#37]
Hello,

In the git version of giada (pulled on 17/01/14), giada's GUI gets corrupted when the screen is maximised.

It is fine if the window is resized manually.

Find a screenshot below of the issue.
![screenshot from 2015-01-18 11 17 20](https://cloud.githubusercontent.com/assets/1472461/5792196/276ab2be-9f04-11e4-950c-e68e908d9420.png)

**Comment by blablack** [comment]
FYI - I haven't been able to reproduce this problem on the latest git,

**Comment by monocasual** [comment]
Seems fixed with the latest updates.

**Comment by monocasual** [comment]
btw in your screenshot the vu-meters are misaligned with the other widgets. Are you able to reproduce that in the latest git?

**Comment by blablack** [comment]
That's how the screen looks to me now.

Is that what you expect?
![screenshot from 2015-01-29 19 01 34](https://cloud.githubusercontent.com/assets/1472461/5964113/6db93a86-a7e9-11e4-80fc-df1e003afe87.png)

**Comment by monocasual** [comment]
Nope, the meters should stick to the right edge of the window. The volume knob is in the wrong position, too. The bug shows up only if compiled without --with-vst flag. Now fixed. Thanks!
