### ISSUE TITLE
--helps starts giada, missing descriptions in --help

### ISSUE THREAD

**Issue by sezanzeb** [monocasual/giada#372]
I think this is rather unexpected and dissimilar to other software.

Running `giada --help` should probably only display the cli help and exit, but not start the program itself.

**Comment by sezanzeb** [comment]
and could you maybe also add some description?

`giada --help`:

```
options are:
 -bg2 color
 -bg color
 -di[splay] host:n.n
 -dn[d]
```

what is dnd?

`cp --help`:
```
  -a, --archive                same as -dR --preserve=all
      --attributes-only        don't copy the file data, just the attributes
      --backup[=CONTROL]       make a backup of each existing destination file
  -b                           like --backup but does not accept an argument
      --copy-contents          copy contents of special files when recursive
  -d                           same as --no-dereference --preserve=links
```

**Comment by monocasual** [comment]
@sezanzeb surprisingly, this is the first time I realize Giada has such command line options! I guess it's a leftover from FLTK, the UI library currently in use. Since Giada doesn't take any command line input parameter, the `--help` flag should me muted/removed.

**Comment by keryell** [comment]
> Since Giada doesn't take any command line input parameter

Actually, this is a useful piece of information to have in the help! :-)

**Comment by gvnnz** [comment]
Done, closing.
