### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by malcolmjay** [monocasual/giada#376]
Just have a quick question - is there a way to modify the background color of the application?

**Comment by tomek-szczesny** [comment]
Hi @malcolmjay ,

It appears that colors are hardcoded in src/core/const.h:

```
#define G_COLOR_RED       fl_rgb_color(28,  32,  80)
#define G_COLOR_BLUE      fl_rgb_color(113, 31,  31)
#define G_COLOR_RED_ALERT fl_rgb_color(239, 75,  53)
#define G_COLOR_LIGHT_2   fl_rgb_color(200, 200, 200)
#define G_COLOR_LIGHT_1   fl_rgb_color(170, 170, 170)
#define G_COLOR_GREY_4    fl_rgb_color(78,  78,  78)
#define G_COLOR_GREY_3    fl_rgb_color(54,  54,  54)
#define G_COLOR_GREY_2    fl_rgb_color(37,  37,  37)
#define G_COLOR_GREY_1_5  fl_rgb_color(28,  28,  28)
#define G_COLOR_GREY_1    fl_rgb_color(25,  25,  25)
#define G_COLOR_BLACK     fl_rgb_color(0,   0,   0)
```

The background of main window is hardcoded as such in src/gui/dialogs/mainWindow.cpp, line 52:

`	Fl::background(25, 25, 25); // TODO use G_COLOR_GREY_1`

As you can see, color scheme is still a work in progress, and I remember there were plans for another, bright color scheme, but can't find the issue corresponding with that.

Anyway, for questions regarding  Giada I'd suggest joining [Giada Forum](https://www.giadamusic.com/forum/) instead. :)
Hope it helps!

**Comment by malcolmjay** [comment]
Thanks @tomek-szczesny! this helps out a lot.  Thank you for the link to the forum as well, was looking for it but it looks like the main site has a broken link.

**Comment by tomek-szczesny** [comment]
Not really, sometimes it happens to me that forum engine returns error 503 I think, but works fine after a refresh. I thought that was a problem on my side of the wire. ;)
