### ISSUE TITLE
Error Message - MacOS Mojave

### ISSUE THREAD

**Issue by malcolmjay** [monocasual/giada#377]
Hi,

I'm running Mojave on a 2015 MacBook Pro and get the following error message whenever I quit the application:

Process:               giada_osx [1029]
Path:                  /Users/USER/Desktop/giada.app/Contents/MacOS/giada_osx
Identifier:            giada_osx
Version:               0.16.3 (1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           giada_osx [1029]
User ID:               501

Date/Time:             2020-07-28 15:33:18.321 -0500
OS Version:            Mac OS X 10.14.6 (18G2022)
Report Version:        12
Anonymous UUID:        D97D65D4-1B50-AC29-A967-FB1195B22BEC

Sleep/Wake UUID:       B75C695E-7A1C-4240-BADA-8EF7E14E0106

Time Awake Since Boot: 8400 seconds
Time Since Wake:       380 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000100004000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1029]

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000100004000  rbx: 0x0000000104a21555  rcx: 0x0000000100004000  rdx: 0x0000000000000000
  rdi: 0x0000000100004000  rsi: 0x0000000000000000  rbp: 0x00007ffeeb743b50  rsp: 0x00007ffeeb743b00
   r8: 0x00000000000003ff   r9: 0x00000000000007fb  r10: 0x0000000000002b90  r11: 0x0000000000000010
  r12: 0x00007ffeeb743ba0  r13: 0x0000000104f88555  r14: 0x0000000104a233b0  r15: 0x0000000000564e88
  rip: 0x00000002051255ee  rfl: 0x0000000000010206  cr2: 0x0000000100004000
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 4883
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro12,1, BootROM 188.0.0.0.0, 2 processors, Intel Core i5, 2.7 GHz, 8 GB, SMC 2.28f7
Graphics: kHW_IntelIris6100Item, Intel Iris Graphics 6100, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.61.3 AirPortDriverBrcmNIC-1305.9)
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
USB Device: Cruzer Spark
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by monocasual** [comment]
Thanks for reporting @malcolmjay . Is the crash always reproducible? It would really helpful to run the development version of Giada in a debugger and take a look at the backtrace.

**Comment by gvnnz** [comment]
No feedback, closing.
