### ISSUE TITLE
Sample Editor Issue

### ISSUE THREAD

**Issue by malcolmjay** [monocasual/giada#378]
I'm currently running the latest build on a raspberry pi 4. Whenever I try to trim a long sample while it's playing in the editor, the whole application closes with no error messages provided.

**Comment by tomek-szczesny** [comment]
Hello again! So, tell us more, what OS and sound system do you use, do you happen to have any other sound-related issues, where did you obtain your copy of Giada, what version is it...

Be sure to turn on logging in config window, misc tab. Also run Giada from terminal, so you can catch an error message in it. 
Hope to see some more input from you. :)

**Comment by malcolmjay** [comment]
@tomek-szczesny I'm running a 64 bit version of the latest RaspiOS with ALSA as the sound system.  I compiled the latest version of giada from source from the main website.  Below are the details of the error - wondering if it's the same issue #368 since it's also a segmentation fault.

[KA] using system 0x2
[KA] Opening devices 0 (out), 0 (in), f=44100...
[KA] 2 device(s) found
  0) hw:audioinjector-pi-soundcard,0
  1) default
[mixer::init] buffers ready - framesInSeq=88200, framesInBuffer=128
[mixer::enable] enabled
[KA] latency = 0
[KM] using system 0x2
[KM] 1 output MIDI ports found
  0) Midi Through:Midi Through Port-0 14:0
[KM] 1 input MIDI ports found
  0) Midi Through:Midi Through Port-0 14:0
[geColumn::cb_addChannel] id = 1
[waveManager::create] new Wave created, 8019365 frames
[geWaveform::alloc] 704 pixels, 11391.143555 m_ratio
[wfx::trim] trimming from 0 to 444254 (area = 444254)
Segmentation fault

**Comment by tomek-szczesny** [comment]
I don't think that's related to #368. Although this one rings a bell: #307. Do you think you could check if @muziker's steps to reproduce a problem also work for you?

**Comment by gvnnz** [comment]
No feedback, closing.
