### ISSUE TITLE
Mute Group - Enhancement

### ISSUE THREAD

**Issue by malcolmjay** [monocasual/giada#381]
I’ve been experimenting using Giada like a MPC to trigger sample chops in Oneshot retrig mode over multiple channels. This has been working pretty well except that there is overlap when triggering samples across channels. 

I think it would be a useful feature to have a new mode that is similar to the “Mute Group” functionality in the MPC. This essentially will cut off the audio of a channel when another channel is triggered if they’re in the same group.  A possible option would be to create a new mode called “Oneshot retrig grp 1”. Any channels in this mode could then cut each other off.

**Comment by tomek-szczesny** [comment]
This is something already on a roadmap, I believe: #90

**Comment by monocasual** [comment]
Closing this and moving the comment by @malcolmjay in #90. Thanks
