### ISSUE TITLE
0.16.3 fails to build on Fedora Rawhide (future F33)

### ISSUE THREAD

**Issue by eeickmeyer** [monocasual/giada#385]
Please see https://kojipkgs.fedoraproject.org//work/tasks/3721/48553721/build.log. There have been some changes to Fedora's build system, but none of them should affect this. Maybe my packaging is off, but this seems to be a different error and is a bit over my head.

**Comment by monocasual** [comment]
This has been fixed in 0.16.3.1 (original issue [here](https://github.com/monocasual/giada/issues/351)).

**Comment by eeickmeyer** [comment]
Excellent. That version isn't linked on the main website (which is where I get the source from since the source from the tag is missing the submodules). Might be worth a website update.

**Comment by monocasual** [comment]
Thanks @eeickmeyer, the released linked on the main website has just been updated.

**Comment by eeickmeyer** [comment]
Cool. I've got clean builds on Fedora now. :)
