### ISSUE TITLE
Master Tempo after recording

### ISSUE THREAD

**Issue by malcolmjay** [monocasual/giada#386]
After I record in from my input on a channel, I noticed that the tempo is greyed out and I'm unable to change it. Is that the intended functionality?

**Comment by tomek-szczesny** [comment]
If you use JACK transport then yes, tempo is set by JACK, not another way around. I think Giada cannot be a Jack Master as of now. 
If not, I think that the issue has been fixed recently:
https://github.com/monocasual/giada/commit/851f1128d39fc27d2e52d5f037f990876b84090f#diff-39cb93b9393227161de062514c3b7a24

**Comment by monocasual** [comment]
Actually this is a bug, fixed in https://github.com/monocasual/giada/commit/851f1128d39fc27d2e52d5f037f990876b84090f (development version).
