### ISSUE TITLE
Set all dependencies as git submodules

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#387]
To do:

* [libsndfile](https://github.com/erikd/libsndfile)
* [libsamplerate](https://github.com/erikd/libsamplerate)
* [rtmidi](https://github.com/thestk/rtmidi)
* [fltk](https://github.com/fltk/fltk)

Also update script from #315 to include them in the source tarballs.

**Comment by monocasual** [comment]
CMake provides git submodules integration: https://cliutils.gitlab.io/modern-cmake/chapters/projects/submodule.html

**Comment by monocasual** [comment]
Depends on #315 , moving to 0.17.1.

**Comment by gvnnz** [comment]
Plan has changed, vcpkg + CMake is being used for the task. Done in eac7498e9a51488589f08db1a9591e1779b957ff
