### ISSUE TITLE
Tune samples to notes

### ISSUE THREAD

**Issue by ucodelukas** [monocasual/giada#390]
ability to use a sample with different pitch but the pitch can be set by note :O

**Comment by tomek-szczesny** [comment]
Sounds pretty much like me recent feature request #362 :)

**Comment by ucodelukas** [comment]
Hey, i just thought I can already change the pitch of a sample but I would like to have a stepped note instead

**Comment by gvnnz** [comment]
Thanks @ucodelukas for the input. I'm closing this as duplicate of #362 .
