### ISSUE TITLE
GitHub's Travis-CI check marks are not appearing next to commits

### ISSUE THREAD

**Issue by messmerd** [monocasual/giada#392]
### Describe the bug

[Giada commits on GitHub](https://github.com/monocasual/giada/commits/master) are missing the green check mark (or red X) next to them that indicates whether they passed the Travis-CI tests. 

This is what I'm referring to:
![travis-ci checks](https://user-images.githubusercontent.com/33463986/90849459-48ac8f00-e33d-11ea-8d92-862796c4f9e7.PNG)

Currently, the Giada commit page is missing any of these checks, and it has been since March 2020. 

### How to Fix
I had the [same exact issue](https://github.com/messmerd/dmf2mod/pull/1#issuecomment-605387500) in my repo. It also occurred around the same time in March. 
[It seems](https://github.com/messmerd/dmf2mod/pull/1#issuecomment-606238038) to be related to a change in the way Travis-CI communicates with GitHub. 

Luckily, it's pretty easy to fix. Here's how I did it: 

- Go to [this page](https://github.com/settings/applications) and revoke permissions for Travis-CI. 

- Log out of Travis-CI, then log back in with your GitHub credentials. 

- It will then ask you to allow Travis-CI to access to your GitHub repositories. Click yes, and everything should be back to normal for all future commits. 

- If you want to add the Travis-CI check mark to all the commits since March that lack it, you may need to rebuild them in Travis-CI.

I know this is a relatively minor issue, but it's nice to have it fixed and it's very easy to do.

**Comment by gvnnz** [comment]
Our CI is now powered by GitHub Actions, closing.
