### ISSUE TITLE
Cleanup .gitignore file

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#393]
Most rules were required for Autotools and thus no longer necessary. Related: #153

**Comment by tomek-szczesny** [comment]
Could we leave "*~" ignore rule for tireless vim hermits out there? :rofl:

**Comment by keryell** [comment]
I switched from `vi` to `emacs` around 1993 and I still have a lot of files ending with `~`...
Perhaps a popular rule among traditional editors?

**Comment by monocasual** [comment]
neovim user here :hand: I won't touch the `*~` rule, I promise!

**Comment by gvnnz** [comment]
Moving this to 0.17.2 , depends on #396 .
