### ISSUE TITLE
VST loading crash on Windows

### ISSUE THREAD

**Issue by zeroxoneafour** [monocasual/giada#395]
**Environment**
- OS: Windows 10
- Giada version: 0.16.3.1

**Describe the bug**
When a plugin (like VST) is attempted in the FX for a single channel or the whole project, Giada crashes.

**To Reproduce**
1. Open Giada in Windows
2. Open the FX menu for a channel or project
3. Attempt to load a VST3 or VSTi plugin through the FX mixer or an individual channel
4. Watch it crash

**Expected behavior**
For Giada to not crash and to load/use the VST plugin with a MIDI device

**Additional context**
No debug information was generated in the base directory, even when it was set to.

**Comment by monocasual** [comment]
@free-vbucks thanks for reporting. I'm surprised that you can load VST3 plug-ins, as they are not yet supported (see #72). Can you reproduce the crash with VST2.x plug-ins?

**Comment by gvnnz** [comment]
No feedback, closing.
