### ISSUE TITLE
Cannot pause sequencer if record actions started while sequencer paused

### ISSUE THREAD

**Issue by wcerfgba** [monocasual/giada#397]
**Environment**
- OS: Arch Linux, kernel 5.8.8
- Giada version: 0.16.3

**Describe the bug**
If I press the 'record actions' button (empty circle) while the sequencer/main transport is paused, the sequencer starts for me and I am unable to stop/pause the sequencer even after stopping action recording. However, if I start the transport (play), then press record actions, then stop recording action, then I am able to pause the sequencer.

**To Reproduce**
1. Pause sequencer
2. Start recording action
3. Observe sequencer started
4. Try to pause sequencer -- cannot
5. Stop recording action
6. Try to pause sequencer -- cannot

**Expected behavior**
Should be able to pause sequencer once action recording has stopped. Maybe action recording should not start sequencer in first place? (I do not know, I am still learning how to use the app :smile: )

**Comment by tomek-szczesny** [comment]
There is something fishy going on. Sometimes I can't start a sequencer at random Giada runs, but can run it by clicking an action recorder button. 

I can reproduce behavior described by @wcerfgba as well.

For the record, I use Jack audio and Alsa MIDI.

**Comment by monocasual** [comment]
@tomek-szczesny @wcerfgba I believe this is something related to Jack Audio and how its messages are parsed in Giada. Can you reproduce the behavior without it?

**Comment by tomek-szczesny** [comment]
You might be right, I can recreate this problem on a 0.16.4 AppImage, but only using Jack. PulseAudio and ALSA behave as expected.
