### ISSUE TITLE
source tarball for 0.16.4 missing

### ISSUE THREAD

**Issue by dvzrv** [monocasual/giada#399]
**Environment**
- OS: Arch Linux
- Giada version: 0.16.4

**Describe the bug**
There is no source tarball for 0.16.4

**To Reproduce**
1. Go to https://giadamusic.com/download

**Expected behavior**
A source tarball is available for each release

**Screenshots**
n/a

**Additional context**
Without a source tarball I am not able to upgrade

**Comment by monocasual** [comment]
Tarball published on the official website.

**Comment by dvzrv** [comment]
Thanks! :)
