### ISSUE TITLE
Giada terminates on opening Action Editor when no midimaps available

### ISSUE THREAD

**Issue by ArisNeander** [monocasual/giada#400]
**Environment**
- OS: Fedora 32
- Giada version: 0.16.3

**Describe the bug**
Giada terminates on opening Action Editor when no midimaps available. The directory $HOME/.giada/midimaps does not exist.

**Error Message on terminal**
    [midiMapConf::init] scanning midimaps directory '/home/username/.giada/midimaps/'...
    [midiMapConf::init] unable to scan midimaps directory!
    /usr/include/c++/10/optional:441: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = giada::c::actionEditor::SampleData; _Dp = std::_Optional_base<giada::c::actionEditor::SampleData, true, true>]: Assertion 'this->_M_is_engaged()' failed.

When directory midimaps created manually, but empty:
    [midiMapConf::init] scanning midimaps directory '/home/username/.giada/midimaps/'...
    [midiMapConf::init] total midimaps found: 0
    /usr/include/c++/10/optional:441: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = giada::c::actionEditor::SampleData; _Dp = std::_Optional_base<giada::c::actionEditor::SampleData, true, true>]: Assertion 'this->_M_is_engaged()' failed.

**To Reproduce**
1. Fresh install of Giada
2. Add Sample Channel
3. Edit Actions.

**Expected behavior**
Action Editor should open or an error dialog should appear pointing out the problem.

**Comment by tomek-szczesny** [comment]
Hi!

The warning message about midimaps missing is written right after starting Giada, way before you open Action Editor, so most probably it has nothing to do with your problem.

I followed your steps and nothing suspicious happened.

Please provide more information, like what sound and MIDI systems did you set up in config window, and ideally turn on logging in misc tab of config window, so there is more information to work on.

Also, check out a fresh 0.16.4 version and see if your problem persists. 

Thanks for posting the issue and hope to hear from you soon!

**Comment by ArisNeander** [comment]
Tried it in 0.16.4, no issue there. Thanks.
