### ISSUE TITLE
Windows 0.16.4 binary potentially built without VST support

### ISSUE THREAD

**Issue by fuchsia80** [monocasual/giada#401]
**Environment**
- OS: Windows 7 64-bit
- Giada version: v0.16.4

The Giada 0.16.4 Windows 64-bit binary seems to be compiled without VST support. There's no plugin tab in config, no VST notice in the "About" section and missing FX buttons. Was this done due to the recent reports of VST plugins crashing Giada? I assume it's a mistake, since I couldn't find a related changelog entry or note.

-----

Side note, I also experience the crash upon loading any VST instrument / effect in 0.16.3.
Here's the tail of the log file, in case it's helpful. Seems to be the same issue as the other crash reports.
> [pluginManager::makePlugin] plugin found, uid=VST-CocoaDelay64-c66add25-54657344, name=CocoaDelay64...
[pluginManager::makePlugin] no plugin found with fid=VST-CocoaDelay64-c66add25-54657344!

**Comment by monocasual** [comment]
Thanks @fuchsia80 for reporting: we are about to upload a new Windows build with the fix. Regarding the VST crash: could you please open a new issue?

**Comment by fuchsia80** [comment]
@monocasual I feel like I should only open an issue if the problem persists with 0.16.4 and / or later builds, since older Giada binaries don't crash upon loading a VST, I'll test it once the new build is up.

**Comment by monocasual** [comment]
Binaries updated on the main website.

**Comment by fuchsia80** [comment]
Thank you. VST support works now and the crash does not occur anymore.
