### ISSUE TITLE
Channels in loop-once-bar mode often skip triggers

### ISSUE THREAD

**Issue by tomek-szczesny** [monocasual/giada#403]
**Environment**
- OS: Ubuntu Studio 19.10
- Giada version: 16.4, but I remember the same thing happened in 16.3

**Describe the bug**
I noticed that before, but assumed the problem was with PulseAudio being too slow.
A sample that is supposed to loop for each bar, with a pitch adjusted to a bar length, generally acts as if it was longer than a bar:
- It is always triggered at the beginning of the loop
- It is always triggered at a bar if it wasn't playing in the previous bar,
- It is never triggered at a non-first bar if it was playing in the previous one.

My system runs at 48kHz and I use 120bpm for tests, 16-beat loop and 4-beat bars. That yields 96ks per bar.
My sample has a range 0-93690, so I assume its length is 93691 samples. It is originally 44k100, but I think it's resampled properly.
Giada can automatically adjust pitch to bar, selecting value 0.9759.
One problem is a rounding error, as indeed 93691 / 0.9759 = 96004,... which definitely would cause this problem to happen. However, when I set pitch to 0.9760, which should result in a sample shorter than a bar, on ALSA the problem persists, while on Jack it solves the problem.

Alsa seems to suffer more severly from this bug. At pitch 0.98, a sample is played in the following pattern across four bars: playing, not playing, playing, playing.

Big enough pitch solves the problem of course. In my case +1% was enough.

**To Reproduce**
1. Set loop length to 16 beats and 4 bars,
2. Load any sample in a new sample channel (or the one that I attached)
3. In sample editor, adjust its pitch to fit a bar
4. Set sample channel to loop-once-bar mode
5. Run the transport, play the channel

[123_accent-onna-hats.aif.zip](https://github.com/monocasual/giada/files/5323449/123_accent-onna-hats.aif.zip)

**Expected behavior**
A sample is triggered on each of four bars in a loop.

**Comment by monocasual** [comment]
Interesting! I can reproduce it here on my machine, PulseAudio @44100, 120 bpm. What if, in loop-once-bar mode, we just rewind the sample on each bar if it's still playing? I guess it would make sense for the loop mode in question.

**Comment by tomek-szczesny** [comment]
I agree that in this loop mode samples should restart on each bar if in "playing" state. Just make sure it doesn't apply when in "ending" mode ;)
