### ISSUE TITLE
Channels in loop-once-bar mode cannot stop in some circumstances

### ISSUE THREAD

**Issue by tomek-szczesny** [monocasual/giada#404]
**Environment**
- OS: Ubuntu Studio 19.10
- Giada version: tried 16.3 and 16.4

**Describe the bug**
This bug occurs regardless of a sound system and AFAIK only in loop-bar-once mode. This bug also occurs regardless of whether I use a mouse or MIDI controller to stop a channel.
A channel playing in a loop-once-bar mode cannot be stopped if it is currently "audible" - it will go into its "stopping" state, but once clock hits another bar, a channel goes back to "playing" state rather than "stopped".
If a channel is much shorter than a bar, if one tries to stop it while audible, and the sample ends playing before reaching next bar, a channel goes into "starting" state, and then proceeds playing a sample on a next bar.

The bug occurs regardless of which bar we try - the beginning of a loop is not treated any different.

**To Reproduce**
1. Load any sample to a new sample channel
2. Set channel to loop-once-bar mode
3. Play a channel, try to stop it

**Expected behavior**
A channel always stops when its playhead reaches the end of a sample

**Comment by tomek-szczesny** [comment]
Seems like this is the problem:

https://github.com/monocasual/giada/blob/bab9bf5abd0ff4cd9d127ef37f594d291449a924/src/core/channels/sampleController.cpp#L150

Code contradicts the comment above. Frankly I don't understand what is the intended purpose of this if/else construct. Shouldn't channel always go "off" on last frame when in "ending" state?

**Comment by monocasual** [comment]
Good catch. That piece of code in `sampleController.cpp` must be a weird left-over from a previous refactoring. As you said, channels should always go "off" on last frame when in "ending" state.

**Comment by monocasual** [comment]
Should be fixed in 0ce9e7d6.

**Comment by tomek-szczesny** [comment]
>  That piece of code in `sampleController.cpp` must be a weird left-over from a previous refactoring.

Oh yes, I did "blame" just to reassure myself that this indeed might be wrong. ;)
