### ISSUE TITLE
Convert monocasual profile into an organization

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#406]
Monocasual Laboratories will become a GitHub organization. Projects such as Giada, Giada Website, Giada MIDI maps and other repositories will become part of it. 

How to: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/converting-a-user-into-an-organization#convert-your-personal-account-into-an-organization-automatically

**Comment by tomek-szczesny** [comment]
Cool, but what does that mean in practice?

**Comment by monocasual** [comment]
Well, it will gives us a more professional look 😎 Also, an organization allows to set roles, permissions and additional security. More information: https://docs.github.com/en/enterprise-server@2.19/github/setting-up-and-managing-organizations-and-teams/about-organizations

**Comment by tomek-szczesny** [comment]
Cool!
Are you recruiting for some specific roles? I'm giving up my Mensa membership at the end of this year, could use some other volunteering job.

**Comment by monocasual** [comment]
@tomek-szczesny thanks, I appreciate your help! No idea yet though, I still need to figure out how the whole thing works. I'll keep you posted...

**Comment by gvnnz** [comment]
We made it! This is my new "personal" account, formerly known as monocasual (now ghost). Nothing should have changed for you @tomek-szczesny and any other collaborator.
