### ISSUE TITLE
NSM Support?

### ISSUE THREAD

**Issue by unfa** [monocasual/giada#414]
Having Giada talk to NSM (Non Session Manager / New Session Manager) session mangers would allow users to incorporate it into easily stored/restored modular setups.

For example I'd like to use Giada in tandem with Carla, but currently it seems the only way to store and restore a project made in this way is to manually save and load projects in both programs.

I'm personally rather new to using session managers, but [when I tried Agordejo](https://www.youtube.com/watch?v=sIqvmz40PVo) I found it's actually a nice way to manage multi-program audio projects without requiring a lot of work to save/load.

**Comment by trebmuh** [comment]
Duplicate #232

**Comment by monocasual** [comment]
Hi @unfa , we definitely want to investigate the NSM technology in the future and #232 proves it. Thanks for the suggestion, I'm closing this one as duplicate.

**Comment by unfa** [comment]
Oh, I'm sorry - I should've searched the issues before posting.
I'm glad it's on the plate somewhere!
