### ISSUE TITLE
failing build on rtmidi

### ISSUE THREAD

**Issue by dromer** [monocasual/giada#417]
**Environment**
- OS: Linux Debian Buster
- Giada version: latest master

**Describe the bug**
In the configure I see:
```
checking rtmidi/RtMidi.h usability... yes
checking rtmidi/RtMidi.h presence... yes
checking for rtmidi/RtMidi.h... yes
```

However the compile fails with:
```
src/core/kernelMidi.cpp:28:10: fatal error: RtMidi.h: No such file or directory
 #include <RtMidi.h>
          ^~~~~~~~~~
compilation terminated.
```

**To Reproduce**
* Install all dependencies
* git clone
* git submodule init
* git submodule update
* ./autogen.sh
* ./configure --target=linux
* make

**Expected behavior**
Build giada.

**Comment by tomek-szczesny** [comment]
Hi!
Yes, this is to be expected, as "master" branch HEAD is not stable, tags are. The reason it fails to compile is that the build environment has been changed in the meantime.
Follow the tips from [this forum post](https://www.giadamusic.com/forum/viewtopic.php?f=7&t=1518#p2605) to resolve your issues.

Let us know if you need more help!

**Comment by dromer** [comment]
Check. Was already considering to checkout a release tag instead ;)

I'm maybe also too used to git-flow, where master always tracks the latest release.

**Comment by dromer** [comment]
Ok, can confirm that with
`git clone --depth 1 --branch v0.16.4 git://github.com/monocasual/giada.git`
giada builds and runs.

**Comment by dvzrv** [comment]
This problem is still present on 0.17.0 and breaks the build for packaging on Arch Linux:

```
g++ -DPACKAGE_NAME=\"giada\" -DPACKAGE_TARNAME=\"giada\" -DPACKAGE_VERSION=\"0.16\" -DPACKAGE_STRING=\"giada\ 0.16\" -DPACKAGE_BUGREPORT=\"giadaloopmachine@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"giada\" -DVERSION=\"0.16\" -DWITH_SYSTEM_CATCH=1 -DNDEBUG=1 -DHAVE_LIBPTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -D
HAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I.  -I./src    -D__LINUX_ALSA__ -D__LINUX_PULSE__ -D__UNIX_JACK__   -D_FORTIFY_SOURCE=2 -std=c++17 -Wall  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -MT src/core/giad
a-waveManager.o -MD -MP -MF src/core/.deps/giada-waveManager.Tpo -c -o src/core/giada-waveManager.o `test -f 'src/core/waveManager.cpp' || echo './'`src/core/waveManager.cpp
mv -f src/core/plugins/.deps/giada-pluginHost.Tpo src/core/plugins/.deps/giada-pluginHost.Po
mv -f src/core/plugins/.deps/giada-plugin.Tpo src/core/plugins/.deps/giada-plugin.Po
src/core/kernelMidi.cpp:28:10: fatal error: RtMidi.h: No such file or directory
   28 | #include <RtMidi.h>
      |          ^~~~~~~~~~
compilation terminated.
mv -f src/core/plugins/.deps/giada-pluginManager.Tpo src/core/plugins/.deps/giada-pluginManager.Po
mv -f src/core/plugins/.deps/giada-pluginState.Tpo src/core/plugins/.deps/giada-pluginState.Po
make: *** [Makefile:3956: src/core/giada-kernelMidi.o] Error 1
```

I have to manually add rtmidi's cflags to CPPFLAGS:

```
CPPFLAGS+="$(pkgconf --cflags rtmidi)"
```

Please reopen!

**Comment by dvzrv** [comment]
A more clean solution to this problem is:

```
diff -ruN a/Makefile.am b/Makefile.am
--- a/Makefile.am	2020-11-15 21:26:40.000000000 +0100
+++ b/Makefile.am	2020-11-20 18:53:06.031868664 +0100
@@ -402,7 +402,7 @@
 if LINUX
 
 # Add preprocessor flags to enable ALSA, Pulse and JACK in RtAudio.
-cppFlags += -D__LINUX_ALSA__ -D__LINUX_PULSE__ -D__UNIX_JACK__
+cppFlags += -D__LINUX_ALSA__ -D__LINUX_PULSE__ -D__UNIX_JACK__ $(RTMIDI_CFLAGS)
 
 ldAdd += -lsndfile -lfltk -lXext -lX11 -lXft -lXpm -lm -ljack -lasound \
 	-lpthread -ldl -lpulse-simple -lpulse -lsamplerate -lrtmidi \
diff -ruN a/configure.ac b/configure.ac
--- a/configure.ac	2020-11-15 21:26:40.000000000 +0100
+++ b/configure.ac	2020-11-20 18:52:11.715602516 +0100
@@ -138,6 +138,7 @@
 		[],
 		[AC_MSG_ERROR([library 'rtMidi' not found!])]
 	)
+	PKG_CHECK_MODULES([RTMIDI], [rtmidi])
 	AC_LANG_POP
 fi
 ```

**Comment by dromer** [comment]
On `0.17.1` this problem is also back for me.

**Comment by tomek-szczesny** [comment]
This looks like an unrelated problem. I googled this error message and it seems that upgrading gcc to version 9 might help. Check this out: https://github.com/CLIUtils/CLI11/issues/445

**Comment by dromer** [comment]
Hmm, I'm not exactly in a position where I feel comfortable to change the gcc version on my system at the moment :#

**Comment by dvzrv** [comment]
With the cmake setup in 0.17.2 rtmidi is picked up properly.

**Comment by dromer** [comment]
The build succeeds, however now I run in to: https://github.com/monocasual/giada/issues/457

I should try what plain alsa config does on top of pipewire.

I guess this ticket can be closed (again), we get to an executable now :)
