### ISSUE TITLE
Build error on Linux

### ISSUE THREAD

**Issue by tank-trax** [monocasual/giada#418]
Debian Buster 10
Branch: master
commit ad0dcf983c8e0c4ec3dcb426754eb8a05adda26d

I am getting the same error using ./configure or cmake
```
src/gui/dialogs/pluginList.cpp: In member function ‘virtual void giada::v::gdPluginList::rebuild()’:
src/gui/dialogs/pluginList.cpp:110:8: error: ‘class geLiquidScroll’ has no member named ‘scroll_to’; did you mean ‘scrollbar’?
  list->scroll_to(0, 0);
        ^~~~~~~~~
        scrollbar
make: *** [Makefile:4648: src/gui/dialogs/giada-pluginList.o] Error 1

```

**Comment by tomek-szczesny** [comment]
Thanks for reporting. Yes, master branch is by default the "Work in progress" branch. For stable operation please clone the most recent tag.

**Comment by tank-trax** [comment]
I was able to build version 17.0 recently and can load a few VST3's as well... like Dexed, OB-xD and Odin2

Surge crashes it though

if you'd like help with testing let me know

**Comment by monocasual** [comment]
@tank-trax that build error is pretty weird. What version of FLTK is installed in your system?

**Comment by tank-trax** [comment]
recently installing some deps for another app to build locally and for some reason it pushed FLTK back to libfltk1.1-dev

upped it back to libfltk1.3-dev and Giada builds now

thanks
