### ISSUE TITLE
Missing VCRUNTIME140_1.DLL on Windows

### ISSUE THREAD

**Issue by tomek-szczesny** [monocasual/giada#420]
**Environment**
- Windows

**Describe the bug**
Users report on the forum that VCRUNTIME140_1.DLL file is missing, and Giada cannot execute without it.

**To Reproduce**
1. Run Giada (0.16.4?) on Windows

**Screenshots**
![giada_runtime_error_10-20-2020](https://user-images.githubusercontent.com/44300715/99046552-32f0e380-2593-11eb-9393-2f2eddbf0a54.jpg)

**Additional context**
A user [points](https://www.giadamusic.com/forum/viewtopic.php?f=2&t=1587&p=2618#p2608) to a resource on Microsoft website that has the missing library.

**Comment by monocasual** [comment]
Thanks! A fix is on its way.

**Comment by monocasual** [comment]
Experimental Windows build that *should* fix the issue: [giada-master-x86_64-windows.zip](https://github.com/monocasual/giada/files/5539517/giada-master-x86_64-windows.zip)

**Comment by monocasual** [comment]
No feedback from the forum so far. I'm moving this to 0.17.1 just in case.

**Comment by gvnnz** [comment]
No feedback since October, closing.
