### ISSUE TITLE
Add CMake install rules

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#422]
To allow users to install Giada on their system (e.g. `make install`). Required by #358 .

Howto: https://cmake.org/cmake/help/latest/guide/tutorial/index.html#installing-and-testing-step-4

**Comment by gvnnz** [comment]
'Done in #422. 

Usage, beyond the usual `make install`: 

With CMake >= 3.15:
```
cmake --install <build_dir> [--prefix <install-dir>]
```

With CMake < 3.15:

```
cmake --build <build_dir> --target install
```
