### ISSUE TITLE
Cloned MIDI channels refer to the original one

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#426]
**Environment**
All

**Describe the bug**
Cloning a MIDI channel creates a kind of weird reference with the MIDI actions from the source channel, as seen here: https://youtu.be/7dR_Zo4Y5fA?t=2092. 

**To Reproduce**
1. Create a new MIDI channel
2. add some MIDI actions in it
3. clone the channel
4. delete a MIDI action from the cloned channel
5. open the Action Editor in the original channel: actions got deleted in the cloned channel too

**Expected behavior**
Original channel should not be affected by changes made in the cloned one.

**Comment by tomek-szczesny** [comment]
Well, it's faster to fix it than to finish midi-overhaul, I guess. ;)

**Comment by monocasual** [comment]
> Well, it's faster to fix it than to finish midi-overhaul, I guess. ;)

:crossed_fingers:

**Comment by gvnnz** [comment]
Fixed in 1b654272080af4e4a6c5e44bf164867c26eff60c, closing.
