### ISSUE TITLE
CMake complaints - Missing dependencies

### ISSUE THREAD

**Issue by tomek-szczesny** [monocasual/giada#429]
**Environment**
- Armbian Linux Focal on Odroid N2+ SBC

**Describe the bug**

First I installed all dependencies that I listed out in a [tutorial](https://www.giadamusic.com/forum/viewtopic.php?f=7&t=1518) years ago.

I started out with fresh git clone, and ran `cmake ..`.
I got this:

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindALSA.cmake:60 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:431 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/mctom/git/giada/build/CMakeFiles/CMakeOutput.log".
See also "/home/mctom/git/giada/build/CMakeFiles/CMakeError.log".
```
Resolved by `sudo apt install libasound2-dev` as found out [here](https://github.com/mpromonet/v4l2rtspserver/issues/28) (no idea if this is a correct resolution, but it works)

Then, running CMake again I got:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/mctom/git/giada/LIBRARY_RTMIDI_INCLUDE_DIR
   used as include directory in directory /home/mctom/git/giada
LIBRARY_JACK
    linked by target "giada" in directory /home/mctom/git/giada
LIBRARY_PULSE
    linked by target "giada" in directory /home/mctom/git/giada
LIBRARY_PULSE_SIMPLE
    linked by target "giada" in directory /home/mctom/git/giada
LIBRARY_RTMIDI
    linked by target "giada" in directory /home/mctom/git/giada

-- Configuring incomplete, errors occurred!
See also "/home/mctom/git/giada/build/CMakeFiles/CMakeOutput.log".
See also "/home/mctom/git/giada/build/CMakeFiles/CMakeError.log".
```

Resolved by installing `librtaudio-dev` and then `librtmidi-dev`. Wouldn't let me do it otherwise, but that's outside of the scope of this issue.

Prior to this I installed all dependencies that I listed out in a [tutorial](https://www.giadamusic.com/forum/viewtopic.php?f=7&t=1518) years ago.

I'm not entirely sure whether it's a problem purely on my side, but that `libasound2` made me think that perhaps the "compiling from source" page is missing one dependency.

But hey, it builds now! :)

**Comment by monocasual** [comment]
> Resolved by sudo apt install libasound2-dev as found out here (no idea if this is a correct resolution, but it works)

Yes this is correct: the message is saying that ALSA dev libs are missing. I agree the message should be more explicit - e.g. "ALSA lib not found, please install libasound2-dev".

> Resolved by installing librtaudio-dev and then librtmidi-dev.

Same as above. Those dependencies must be installed manually before compiling.

**Comment by tomek-szczesny** [comment]
All I'm saying is these dependencies are not listed in the [documentation](https://www.giadamusic.com/documentation-compiling-from-source) and adding them there would be enough. :)

**Comment by gvnnz** [comment]
CMake script is now more explicit if dependencies are missing. Closing.
