### ISSUE TITLE
"Cancel" button in "Load Project" dialog crashes Giada

### ISSUE THREAD

**Issue by tomek-szczesny** [monocasual/giada#430]
**Environment**
- Armbian Linux Focal on Odroid N2+ SBC
- Giada 0.17.0 built from source, with Debug flag

**To Reproduce**
- Run Giada
- Select menu "File/Open Project..."
- Click "Cancel"

**Expected behavior**
Dialog disappears

**Additional context**
This is the console output of the program:
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot make canonical path: Invalid argument []
Aborted
```

**Comment by monocasual** [comment]
Confirmed here, Giada 0.17.0 on Debian.

**Comment by monocasual** [comment]
This also happens when going up a directory. In both cases the crash occurs only if the path bar is empty.

**Comment by tomek-szczesny** [comment]
Can't say whether this is something new. Come to think of it, I don't remember the last time I used any of these two buttons :D
