### ISSUE TITLE
No rule to make target 'src/gui/elems/basics/baseButton.cpp', needed by 'src/gui/elems/basics/giada-baseButton.o'.

### ISSUE THREAD

**Issue by yurivict** [monocasual/giada#433]
Build fails on FreeBSD 12.2 with clang-10:
```
===>  Building for giada-0.17.0
gmake[1]: Entering directory '/usr/ports/audio/giada/work/giada-0.17.0'
gmake[1]: *** No rule to make target 'src/gui/elems/basics/baseButton.cpp', needed by 'src/gui/elems/basics/giada-baseButton.o'.  Stop.
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: Leaving directory '/usr/ports/audio/giada/work/giada-0.17.0'
```

Version 0.17.0

**Comment by monocasual** [comment]
Hey @yurivict , did you follow [these instructions](https://www.giadamusic.com/documentation-compiling-from-source)?

**Comment by yurivict** [comment]
The command ```git submodule update --init --recursive``` doesn't bring in this file (```baseButton.cpp```).

**Comment by monocasual** [comment]
It looks like you are still using Autotools, which is deprecated as discussed in https://github.com/monocasual/giada/issues/431 . Try to use CMake as suggested in the documentation.

**Comment by yurivict** [comment]
cmake doesn't install anything:
```
===>   Generating temporary packing list
ninja: error: unknown target 'install/strip'
```

You don't have any ```install``` instructions to match what Autotools-based build installs, so Autotools build can't be deprecated.

**Comment by yurivict** [comment]
https://github.com/monocasual/giada/issues/435

**Comment by monocasual** [comment]
Pushed a quick fix to Makefile.am.

**Comment by yurivict** [comment]
What about a cmake fix?

**Comment by gvnnz** [comment]
CMake should already be fine.
