### ISSUE TITLE
CMAKE_TOOLCHAIN_FILE not defined!

### ISSUE THREAD

**Issue by yurivict** [monocasual/giada#442]
**Environment**
- OS: FreeBSD 12.2
- Giada version: 0.17.0-23-g74b9a80a

**Describe the bug**
configure fails:
```
CMake Error at CMakeLists.txt:275 (message):
  CMAKE_TOOLCHAIN_FILE not defined!
```

**To Reproduce**
1. cmake .

**Comment by gvnnz** [comment]
You need to tell CMake to use system libraries, like this:

```
cmake -DWITH_SYSTEM_<library>
```

The full list of `WITH_SYSTEM_<...>` option is [here](https://github.com/monocasual/giada/blob/master/CMakeLists.txt#L233) and we are discussing the whole idea in #315 .

**Comment by yurivict** [comment]
The cmake variable for using system RtAudio is missing, and it fails:
```
CMake Error at CMakeLists.txt:517 (add_executable):
  Cannot find source file:

    src/deps/rtaudio/RtAudio.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


```

**Comment by gvnnz** [comment]
@yurivict things have changed again lately (for the better, I hope!). Please try again on master branch. Thanks!
