### ISSUE TITLE
CMake install rule seems wrong

### ISSUE THREAD

**Issue by musicinmybrain** [monocasual/giada#450]
**Environment**
- OS: Fedora Linux 33 x86_64, but it does not matter
- Giada version: (master)

**Describe the bug**
When configured with `-DCMAKE_INSTALL_PREFIX:PATH=/usr`, Giada is installed as `/usr/giada` instead of `/usr/bin/giada`

**To Reproduce**
1. `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr`
2. `cmake --build .`
3. `sudo cmake --install .`
4. See that the binary is installed as `/usr/giada` instead of `/usr/bin/giada`

**Expected behavior**
The binary is installed to `/usr/bin/giada`.

**Screenshots**

**Additional context**

The following patch seems to give the expected behavior, and is consistent with the examples in https://cmake.org/cmake/help/latest/command/install.html#command:install.

```diff
--- giada-0.17.1-src-original/CMakeLists.txt	2021-02-01 12:41:42.000000000 -0500
+++ giada-0.17.1-src/CMakeLists.txt	2021-02-20 13:29:48.152058634 -0500
@@ -500,7 +500,7 @@
 # Install rules
 # ------------------------------------------------------------------------------
 
-install(TARGETS giada DESTINATION ${CMAKE_INSTALL_PREFIX})
+install(TARGETS giada DESTINATION bin)
 
 # ------------------------------------------------------------------------------
 # Extra
```

**Comment by gvnnz** [comment]
Thanks! I'm not sure how it behaves outside Fedora. Needs more testing, we'll look into it.

**Comment by gvnnz** [comment]
What if you pass `-DCMAKE_INSTALL_PREFIX:PATH=/usr/bin` instead of just `-DCMAKE_INSTALL_PREFIX:PATH=/usr`?

**Comment by musicinmybrain** [comment]
Sure, that will work, since giada does not install anything else under the `CMAKE_INSTALL_PREFIX`. It’s very weird and surprising, though. Users on Linux and UNIX-like systems expect a “prefix” to be a directory with subdirectories like `bin`, `lib`, `share`, and so on. That’s why the [CMake default is `/usr/local`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html), and Fedora’s `%cmake` spec file macro sets `-DCMAKE_INSTALL_PREFIX:PATH=%{_prefix}`, where `%{_prefix}` is `/usr`. It works for _almost_ every package in the distribution. It looks like [Widelands](https://www.widelands.org/) is the only other software that wants `-DCMAKE_INSTALL_PREFIX:PATH=%{_bindir}`.

**Comment by gvnnz** [comment]
I must admit my ignorance when it comes to installing stuff on Linux and derived system (especially if done through CMake). The point is: Giada is currently just a single binary to be copied to a sensible place - `/usr/bin`, `/usr/local/bin`,  whatever. So what's the best/official way here to handle this through CMake? A quick and shallow search through other CMake-based projects shows that the `CMAKE_INSTALL_PREFIX` variable is relevant:

https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L663
https://github.com/rncbc/qtractor/blob/master/CMakeLists.txt#L791

Others use `CMAKE_INSTALL_BINDIR`:

https://github.com/mixxxdj/mixxx/blob/main/CMakeLists.txt#L1134

Help wanted? :sunglasses:

**Comment by musicinmybrain** [comment]
Thanks!
