### ISSUE TITLE
Some dependencies may need to be found with pkg-config/pkgconf on some platforms

### ISSUE THREAD

**Issue by musicinmybrain** [monocasual/giada#451]
**Environment**
- OS: Fedora Linux 33–35 x86_64
- Giada version: 0.17.1

**Describe the bug**

On Fedora Linux, RtMidi and SndFile (libsndfile) can be found using pkg-config but not CMake. This could be considered a packaging bug; the packages for those two libraries should probably be installing the relevant CMake files. However, it is possible to work around the problem by falling back to pkg-config (pkgconf) in Giada. This could make it easier for users on varied platforms to build Giada.

**To Reproduce**
1. Try to build Giada on Fedora Linux, with libsndfile-devel and rtaudio-devel packages installed.
2. These two dependencies are not found.

**Expected behavior**
These two dependencies are not found.

**Screenshots**
Not applicable.

**Additional context**
I will follow up with a PR that seems to work for me, while preserving the existing CMake dependency resolution where it would succeed.

Feel free to implement this differently, or to decide you do not want to support this method of finding dependencies at all.

**Comment by gvnnz** [comment]
Thank you @musicinmybrain , the PR has been checked, squashed and merged to master.
