### ISSUE TITLE
Deleted folder error

### ISSUE THREAD

**Issue by emrergin** [monocasual/giada#455]
**Environment**
- Windows 10, latest.
- Giada, latest.

**Describe the bug**
Missing folder causes crash.

**To Reproduce**
- Import a sample. 
- Exit the program. 
- Delete or move the folder where the sample is included. 
- Reopen the program.
- The program will find no files as expected.
- Try to change the navigation.
- Program crashes.

**Expected behavior**
Probably when the last used folder is not existant, some default folder should be used.

I corrected the issue by moving the folder back to where it was, and changing the used folder within program, then move the original folder again.

**Comment by gvnnz** [comment]
FIxed. Thanks!
