### ISSUE TITLE
Giada crashes when pressing play fresh from start

### ISSUE THREAD

**Issue by blablack** [monocasual/giada#46]
It all says it in the title :)

From the latest git (March 15) branch "midi-lightning", open Giada and press play, it crashes straight away.

**Comment by blablack** [comment]
After further testing - pressing record first is a work around to the issue.

**Comment by monocasual** [comment]
Unable to reproduce, here... Does it still crash with the latest updates?

**Comment by blablack** [comment]
Hello,

Yes still - it doesn't do it every time... Maybe 3-4 times out of 10.

I'm using jack1 as the audio system.

I tried to add the log but no message there.

If I get the chance i'll try to debug to give you additional indications.

**Comment by blablack** [comment]
After more testing:
- I can reproduce it on the Master branch (so it's not my code :))
- I get this error on Giada's side: 
```
RtApiJack: the Jack server is shutting down this client ... stream stopped and closed!!
```

Any idea what this could mean?

**Comment by blablack** [comment]
After further investigation, Core Dump sometimes happens in RtAudio.cpp in method __HACK__getJackClient

I added at the beginning of the method verifyStream();

When Giada crashes (again, doesn't happen every run, only sometimes) I now get
```
what():  RtApi:: a stream is not open!
```

I don't know if it would help, but here is the full Giada log from start to crash (I run it in GDB so you might get more info)

```
[init] Giada 0.9.6 - Tue Apr 14 19:08:20 2015
[init] configuration file ready
[KA] using system 0x1
[KA] Opening devices 0 (out), -1 (in), f=48000...
[New Thread 0x7ffff1a87700 (LWP 919)]
[KA] 2 device(s) found
[Thread 0x7ffff1a87700 (LWP 919) exited]
[New Thread 0x7ffff1a87700 (LWP 922)]
[Thread 0x7ffff1a87700 (LWP 922) exited]
  0) system
[New Thread 0x7ffff1a87700 (LWP 925)]
  1) alsa_midi
[Thread 0x7ffff1a87700 (LWP 925) exited]
[New Thread 0x7ffff1a87700 (LWP 928)]
[KA] JACK in use, freq = 48000
[Thread 0x7ffff1a87700 (LWP 928) exited]
[New Thread 0x7ffff1a87700 (LWP 933)]
[Thread 0x7ffff1a87700 (LWP 933) exited]
[New Thread 0x7ffff1a87700 (LWP 937)]
[KM] using system 0x0
[KM] 2 output MIDI ports found
  0) Midi Through 14:0
  1) UA-25EX 20:0

MidiOutAlsa::getPortName: error looking for port name!


MidiOutAlsa::openPort: the 'portNumber' argument (2) is invalid.

[KM] unable to open MIDI out port 2: MidiOutAlsa::openPort: the 'portNumber' argument (2) is invalid.
[KM] 2 input MIDI ports found
  0) Midi Through 14:0
  1) UA-25EX 20:0

MidiInAlsa::getPortName: error looking for port name!


MidiInAlsa::openPort: the 'portNumber' argument (2) is invalid.

[KM] unable to open MIDI in port 2: MidiInAlsa::openPort: the 'portNumber' argument (2) is invalid.
[gKeyboard::__cb_addColumn] new column added (index = 0), total count=1, addColumn(x)=384
[gKeyboard::__cb_addColumn] new column added (index = 1), total count=2, addColumn(x)=760
[gKeyboard::__cb_addColumn] new column added (index = 2), total count=3, addColumn(x)=1136
[gKeyboard::__cb_addColumn] new column added (index = 3), total count=4, addColumn(x)=1512
[gKeyboard::__cb_addColumn] new column added (index = 4), total count=5, addColumn(x)=1888
[gKeyboard::__cb_addColumn] new column added (index = 5), total count=6, addColumn(x)=2264
[New Thread 0x7ffff09a3700 (LWP 940)]
[New Thread 0x7ffff7ec9700 (LWP 941)]
[KA] latency = 128
[KA] Jack transport stopped, frame=2326016
[New Thread 0x7fffebf49700 (LWP 944)]

RtApiJack: the Jack server is shutting down this client ... stream stopped and closed!!

[Thread 0x7ffff7ec9700 (LWP 941) exited]
[Thread 0x7ffff1a87700 (LWP 937) exited]
[Thread 0x7fffebf49700 (LWP 944) exited]
terminate called after throwing an instance of 'RtAudioError'
  what():  RtApi:: a stream is not open!

Program received signal SIGABRT, Aborted.
```

**Comment by blablack** [comment]
So, much more debugging and I believe:
- the issue is with method jackSyncCb in kernelAudio which is used by jack_set_sync_callback
- jack_set_sync_callback doesn't like if it's JackSyncCallback creates a blocked process even for an instant
- jackSyncCb uses glue_stopSeq and glue_startSeq
- in glue_stopSeq and glue_startSeq is used Fl::lock() which blocks the main process

by removing the Fl::lock and Fl::unlock i haven't managed to reproduce the issue so far. I must have restarted Giada 100 times without crashing it (normally would happen 3 times out of 10). The fact that it is thread related and happens only sometimes seem consistant with my experience with threads :) 
In addition, that might explain why I cannot reproduce it with jack2 (AFAIK its less sensible than jack1 to threading and blocked processes).

In conclusion, the following patches fixed the problem for me:

```
diff --git a/src/glue.cpp b/src/glue.cpp
index 05fcb64..351bec9 100644
--- a/src/glue.cpp
+++ b/src/glue.cpp
@@ -341,9 +341,9 @@ void glue_startSeq(bool gui)
 		kernelMidi::send(MIDI_POSITION_PTR, 0, 0);
 	}
 
-	Fl::lock();
+    if (gui) Fl::lock();
 	mainWin->controller->updatePlay(1);
-	Fl::unlock();
+    if (gui) Fl::unlock();
 }
 
 
@@ -367,9 +367,9 @@ void glue_stopSeq(bool gui) {
 
 	if (recorder::active) {
 		recorder::active = false;
-		Fl::lock();
+        if (gui) Fl::lock();
 		mainWin->controller->updateRecAction(0);
-		Fl::unlock();
+        if (gui)Fl::unlock();
 	}
 
 	/* if input recs are active (who knows why) we must deactivate them.
@@ -377,14 +377,14 @@ void glue_stopSeq(bool gui) {
 
 	if (G_Mixer.chanInput != NULL) {
 		mh_stopInputRec();
-		Fl::lock();
+        if (gui) Fl::lock();
 		mainWin->controller->updateRecInput(0);
-		Fl::unlock();
+        if (gui) Fl::unlock();
 	}
 
-	Fl::lock();
+    if (gui) Fl::lock();
 	mainWin->controller->updatePlay(0);
-	Fl::unlock();
+    if (gui) Fl::unlock();
 }
 
 ```

**Comment by monocasual** [comment]
Good search! Indeed those glue_* functions are called from kernelAudio, specifically in 

`int jackSyncCb(jack_transport_state_t state, jack_position_t *pos, void *arg)`

as recently confirmed in #49 . I would say that those Fl:lock might be even useless. I should test it more carefully, though. Thanks for the patch. :+1:
