### ISSUE TITLE
Run tests using cmake

### ISSUE THREAD

**Issue by dvzrv** [monocasual/giada#463]
**Environment**
- OS: Arch Linux
- Giada version: 0.17.2

**Describe the bug**
Currently it is unclear how to run tests.

**To Reproduce**
1. Use the `WITH_TESTS=ON` parameter
2. Be unable to run `make test` or similar after `make`

**Expected behavior**
Clear instructions on what it means when `WITH_TESTS=ON` is used and how to run the tests.

**Screenshots**
n/a

**Additional context**
Since the autotools setups is removed, it is impossible to run tests.

**Comment by musicinmybrain** [comment]
I’m the maintainer of the package in Fedora Linux. I think I looked at `.github/workflows/ci.yml` to figure this out. You just need

```sh
xvfb-run -a /path/to/your/built/giada --run-tests
```

Yes, that means enabling the tests affects your installed binary.

(Maybe there’s still a better place to document this.)

**Comment by gvnnz** [comment]
Hey guys, the "[how to build from source](https://www.giadamusic.com/documentation-compiling-from-source)" guide on the website has been updated lately. You will find instructions on how to run tests at the bottom. Is it OK for you? Feedback are welcome.
