### ISSUE TITLE
acorn master key 61 midi keyboard not recognizing inputs 

### ISSUE THREAD

**Issue by ghost** [monocasual/giada#464]
**Environment**
- OS: Windows 10 64bit
- Giada version: [e.g. v0.17.2]

**Describe the bug**

when i plug in my midi keyboard acorn master key 61 giada doesn't recognize its inputs when selected.

**Comment by gvnnz** [comment]
@wander799 basic questions: is your MIDI keyboard recognized by other DAWs or MIDI apps? Could you paste here the console output when you open Giada? How to enable console logging: [here](https://www.giadamusic.com/forum/viewtopic.php?f=2&t=2)

**Comment by gvnnz** [comment]
No feedback, closing.
