### ISSUE TITLE
BSOD on launch after enabling ASIO

### ISSUE THREAD

**Issue by asktoby** [monocasual/giada#465]
**Environment**
- OS: Windows 10
- Giada version: giada-0.17.2-x86_64-windows

**Describe the bug**
Giada causes BSOD on launch when ASIO selected.

**To Reproduce**

- Fresh download of Giada 0.17.2
- Launch, see the below in console:

```
[init] Giada 0.17.2
[init] Build date: Mar 28 2021
[init] Release build
[init] Dependencies:
[init]   FLTK - 1.3.5
[init]   RtAudio - 5.1.0
[init]   RtMidi - 3.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.0.31
[init]   JSON for modern C++ - 3.9.1
[init]   JUCE - 6.0.7
[KA] Compiled RtAudio APIs: 3
  ASIO
  WASAPI
  DirectSound
[init] Can't read configuration file! Using default values
[midiMapConf::init] scanning midimaps directory '.\midimaps\'...
[midiMapConf::init] unable to scan midimaps directory!
```

- Click Config
- Change System from DirectSound to ASIO
- Save, Quit.
- giada.conf created with the following contents:

`{"action_editor_grid_on":0,"action_editor_grid_val":0,"action_editor_h":480,"action_editor_w":640,"action_editor_x":640,"action_editor_y":285,"action_editor_zoom":100,"browser_h":480,"browser_last_path":"","browser_last_value":0,"browser_position":0,"browser_w":640,"browser_x":640,"browser_y":285,"buffer_size":1024,"channels_in_count":1,"channels_in_start":-1,"channels_out":0,"chans_stop_on_seq_halt":false,"envelope_editor_h":40,"header":"GIADACFG","input_monitor_default_on":false,"last_midimap":"","limit_output":false,"log_mode":4,"main_window_h":510,"main_window_w":816,"main_window_x":552,"main_window_y":270,"midi_in":false,"midi_in_action_rec":0,"midi_in_beat_doble":0,"midi_in_beat_half":0,"midi_in_filter":-1,"midi_in_input_rec":0,"midi_in_metronome":0,"midi_in_rewind":0,"midi_in_start_stop":0,"midi_in_volume_in":0,"midi_in_volume_out":0,"midi_input_h":480,"midi_input_w":640,"midi_input_x":0,"midi_input_y":0,"midi_port_in":-1,"midi_port_out":-1,"midi_sync":0,"midi_system":4,"midi_tc_fps":25.0,"midimap_path":"","overdub_protection_default_on":false,"patches_path":"","piano_roll_h":422,"piano_roll_y":-1,"plugin_chooser_h":480,"plugin_chooser_w":640,"plugin_chooser_x":0,"plugin_chooser_y":0,"plugin_list_x":0,"plugin_list_y":0,"plugin_sort_method":0,"plugins_path":"","rec_trigger_level":-10.0,"rec_trigger_mode":0,"resample_quality":0,"sample_action_editor_h":40,"sample_editor_grid_on":0,"sample_editor_grid_val":0,"sample_editor_h":480,"sample_editor_w":640,"sample_editor_x":0,"sample_editor_y":0,"samplerate":44100,"samples_path":"","show_tooltips":true,"sound_device_in":-1,"sound_device_out":0,"sound_system":8,"treat_recs_as_loops":false,"velocity_editor_h":40}`

- Launch giada.exe

**Expected behavior**
Giada should load.

**Observed behavior**
Blue screen of death.
BSOD Stop Code: SYSTEM_SERVICE_EXCEPTION
What failed: ScopePci.sys

**Comment by gvnnz** [comment]
@asktoby is this still a problem with the latest version?

**Comment by asktoby** [comment]
Confirmed issue is still there with giada-0.18.1-x86_64-windows.zip

**Comment by gvnnz** [comment]
Tested latest master (234d76514b86bfb805589fa1b06611c4d67a0332) on Wiindows 11, can't reproduce this. Please @asktoby feel free to reopen if you still see the problem.
