### ISSUE TITLE
cannot select internal mic 

### ISSUE THREAD

**Issue by Aid19801** [monocasual/giada#466]
**Environment**
- OS: macOS 10.15.7
- Giada version: [e.g. v0.17.2]

**Describe the bug**
I select the internal mac mic from input devices, save, close and re-open application like in video
No input is detected and when i go back to config, it has not saved/persisted.

**To Reproduce**
Download app, as advised on Downloads page, open, select internal mic, close and reopen application, check mic/input source in config again.

**Expected behavior**
Mic remains selected and can be used

**Comment by gvnnz** [comment]
Hi @Aid19801 , thanks for reporting. The whole I/O configuration is quite buggy at the moment, but it has been simplified and optimized in version 0.18.0 (coming soon). Please wait a few days and test the new release to see if your issue still persists.,,

**Comment by gvnnz** [comment]
Any luck with v.0.18.0?

**Comment by gvnnz** [comment]
No feedback, closing.
