### ISSUE TITLE
Multiple Drag&Drop on same column

### ISSUE THREAD

**Issue by blablack** [monocasual/giada#47]
From the latest git (March 15) branch "midi-lightning"

When dragging-dropping multiple samples on the same column what happend is that the last one will replace the previous one:
1. Open Giada
2. Drag&Drop a sample called "Drums_Full" -> new channel is created with "Drums_Full"
3. Drag&Drop a sample called "Aspect_DirtyBass" on same column -> first channel is now called "Aspect_DirtyBass" and second channel is called "Aspect_DirtyBass-1"

**Comment by monocasual** [comment]
Bug confirmed. It happens in branch "master" too.
