### ISSUE TITLE
Latest merge of master branch into midi-lightning

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#48]
The latest merge of master branch into midi-lightning (made a few minutes ago) was a little painful because `ge_channel.*` is now split into `ge_sampleChannel.*` and `ge_midiChannel.*`. 

@blablack is midi-lightning ok to you? No missing pieces or strange bugs?

**Comment by blablack** [comment]
Hi,

it doesn't compile on my side:
```
ge_sampleChannel.cpp: In member function ‘virtual void gSampleChannel::resize(int, int, int, int)’:
ge_sampleChannel.cpp:574:3: error: ‘fx’ was not declared in this scope
   fx->hide();
   ^
ge_sampleChannel.cpp:583:3: error: ‘fx’ was not declared in this scope
   fx->show();
```

Could be due that I don't compile with VST?

**Comment by monocasual** [comment]
You're right. Should be ok now, thanks!

**Comment by blablack** [comment]
Sorry for the delay - got the chance to test midi-lightning today and it still works as expected :)
