### ISSUE TITLE
midi bindings to free a channel and skipping a shitty record

### ISSUE THREAD

**Issue by rbckman** [monocasual/giada#484]
I'm trying out Giada as my live looping station. Got jack running at 2 ms latency and Giada has been performing solid with newest version.

as a live looper id really not want to fiddle around with the mouse, got a midi controller for arming channels, everything is good as long as I dont mess up while recording. Then I have to mousy around, click the channel, click free channel, click ok...

can there please be a free channel midi binding? or is there some way around this that I dont get?

also, when you record a loop and fuck up, could there be a trash-that-recording function? like while its recording you can press a button and then the recording never happend.

ps. keep on rocking in the free world!

**Comment by gvnnz** [comment]
Hey @rbckman , thanks for your feedback! 

> can there please be a free channel midi binding? or is there some way around this that I dont get? 

There is but it's a bit obscure: you have to right-click on the MIDI learn box that displays the value  (the _(not set)_ button in the picture below): 
![midi-input-window](https://user-images.githubusercontent.com/74901950/127462561-eda768f2-9be6-4068-a1c9-37f23a98b50a.png)
I agree this should be more explicit, though. 

> also, when you record a loop and fuck up, could there be a trash-that-recording function? like while its recording you can press a button and then the recording never happend.

Good Idea, I'll put it in our TO-DO list.

**Comment by rbckman** [comment]
cool! sorry for not being clear enough, what I mean is a midi binding to free armed samples (not freeing the midi binding). Freeing a midi binding is good enough to me man!

**Comment by gvnnz** [comment]
Well, the right-click thing is weird anyway, it deserves some UX improvements :) I'll add the feature you suggested to the roadmap. Thanks

>  what I mean is a midi binding to free armed samples

I'll add this one too to the roadmap. Thanks!

**Comment by gvnnz** [comment]
Issues #486, #487, #488 extracted from this one, closing.
