### ISSUE TITLE
Let Midi Thru output Channel if Armed 

### ISSUE THREAD

**Issue by CarloCattano** [monocasual/giada#498]
When triying to make live loops with midi and many diferent instruments in outputs for each clip , it would be awesome to be able to play along with the composition without the need to be "recording" actively .

At the current setup ( Giada - > Carla ) , I cant hear what I play , unless Im recording 

A switch similar to the audio "monitor on " would be awesome 

aditional :

  _Fist of all , a big thanks to you and all the people involved . 
  Im not experienced in the language but I would love to contribute however I can  .
  My current testing machine is a raspberry pi and Im in a dream .

Its exactly what I was looking for , for a really long time ._

**Comment by gvnnz** [comment]
@CarloCattano thanks for your kind words! If I understand your point correctly, you can hear what you play without recording: just press the "arm" button on any channel and send MIDI events to it. The whole thing works whether the transport is stopped or running. Does it make sense?

**Comment by CarloCattano** [comment]
Yes @gvnnz thats intended to be like that , but for some reasons in my builds or config setup it isnt ? 
I only can hear midi sent to my outputs if clip is recording . But if armed and not in recording I wont get midi output . Same while recording a loop , I hear the notes only after the loop is finished by clicking record on both clip and master and play the clip

Does it make sense ? I will test again and be more specific with my routings regarding 
jack and midi

**Comment by gvnnz** [comment]
I got it now: you want to send MIDI data through armed channels _outside_ Giada: currently the behavior works only internally, that is for VST plug-ins. Good point, I'll add it to the TO-DO list.

**Comment by gvnnz** [comment]
Done, closing.
