### ISSUE TITLE
Midi Lightning Message not sent on sample channel stop

### ISSUE THREAD

**Issue by fabulou1** [monocasual/giada#517]
**Environment**
- OS: Win10
- Giada version: v.0.18.2]

**Describe the bug**
Hi, it seems that on the newest Version Midi Lightning Messages are not working correctly. When Playing a sample Channel the current Version sends two Midi Messages instead of just the defined "Playing" Message and when manually Stopping the Channel it again sends two messages. Letting the Sample play to the end does not cause a message to be sent at all. 

**Expected behavior**
I formerly used v0.13.2 and there i would get one message and playback start and when either at manual stop or sample ending as defined in the midimaps file.

Apart from that, great Software!

**Comment by gvnnz** [comment]
Hi @fabulou1 , I can confirm the issue here, will be fixed in the next version. Thanks for reporting.

**Comment by gvnnz** [comment]
Fixed in 90318ef3 and later.
