### ISSUE TITLE
Automate the tarball release process

### ISSUE THREAD

**Issue by dvzrv** [monocasual/giada#518]
**Is your feature request related to a problem? Please describe.**
A new release has been tagged 4 days ago: https://github.com/monocasual/giada/releases/tag/v0.19.0
The combined source tarball for this release is not available though

**Describe the solution you'd like**
Either automatic pushing of a source tarball to a github release and/or website. 

**Describe alternatives you've considered**
Build from git repository instead (needs locking of git commit checksum)

**Additional context**
As downstreams monitor the releases of upstreams using tools such as [nvchecker](https://github.com/lilydjwg/nvchecker), the most convenient way is usually to track their upstream repository for new tags (thus releases).
This issue has been around for a while (see https://github.com/monocasual/giada/issues/399).

**Comment by gvnnz** [comment]
Yes, currently the upload of binaries + source tarball on the website is a manual process. A good improvement for the 1.0 release, when the website will be redesigned.

**Comment by gvnnz** [comment]
Done in 7b2823786956fa8b9ea8ff6da77d5e569205dc74, closing.
