### ISSUE TITLE
Audio input device greyed out

### ISSUE THREAD

**Issue by Michaaaaaaaa** [monocasual/giada#519]
**Environment**
- OS: Win10 Pro 20H2
- Giada version: v0.18.2

**Describe the bug**
While i can select an audio output device, the field for selecting an audio input device is greyed out.

**To Reproduce**
1. Go to 'Configuration'
2. Click on selection box 'Input Device'
3. See that selecting an input device is not possible, as the selection box doesn't react when clicked on. Nonfunctionality is additionally indicated by the selection box being greyed out. As a result of the bug, recording is not possible.

**Expected behavior**
I would like to select my Asio audio interface's input so that i can record stuff.

**Screenshots**
![Giada Input](https://user-images.githubusercontent.com/51052754/140531867-0e6535e6-b2ee-4885-a84b-cb83b5eb8a86.png)

**Additional context**
Here's the startup message log:

[init] Giada 0.18.2
[init] Build date: Sep 12 2021
[init] Release build
[init] Dependencies:
[init] FLTK - 1.3.7
[init] RtAudio - 5.1.0
[init] RtMidi - 3.0.0
[init] Libsamplerate
[init] Libsndfile - libsndfile-1.0.31
[init] JSON for modern C++ - 3.9.1
[init] JUCE - 6.1.0
[KA] Compiled RtAudio APIs: 3
ASIO
WASAPI
DirectSound
[midiMapConf::init] scanning midimaps directory '.\midimaps'...
[midiMapConf::init] unable to scan midimaps directory!
[midiMapConf::read] midimap not specified, nothing to do
[init] MIDI map read failed!
[KA] using system 0x4
[KA] Opening device out=1, in=-1, samplerate=48000

RtApiAsio::getDeviceInfo: error (Hardware input or output is not present or available.) initializing driver (Mackie ASIO Driver).

[KA] Can't probe device 0
[KA] 5 device(s) found
0)
ins=0 outs=0 duplex=0
isDefaultOut=0 isDefaultIn=0
sampleRates:

US-16x08 ASIO
ins=16 outs=8 duplex=8
isDefaultOut=0 isDefaultIn=0
sampleRates:
44100 48000 88200 96000
Voicemeeter AUX Virtual ASIO
ins=8 outs=8 duplex=8
isDefaultOut=0 isDefaultIn=0
sampleRates:
32000 44100 48000 88200 96000 176400 192000
Voicemeeter Insert Virtual ASIO
ins=22 outs=22 duplex=22
isDefaultOut=0 isDefaultIn=0
sampleRates:
32000 44100 48000 88200 96000 176400 192000
Voicemeeter Virtual ASIO
ins=8 outs=8 duplex=8
isDefaultOut=0 isDefaultIn=0
sampleRates:
32000 44100 48000 88200 96000 176400 192000
RtApiAsio::getDeviceInfo: error (Hardware input or output is not present or available.) initializing driver (Mackie ASIO Driver).

[mixer::init] buffers ready - maxFramesInLoop=576000, framesInBuffer=2048
[mixer::enable] enabled
[KA] latency = 2988
[KM] using system 0x4
[KM] 2 output MIDI ports found
0) Microsoft GS Wavetable Synth 0

US-16x08 MIDI 1
[KM] 1 input MIDI ports found
US-16x08 MIDI 0

**Comment by enorrmann** [comment]
have you tried to check the checkbox next to the greyed selection ? on the right ?

**Comment by Michaaaaaaaa** [comment]
Hi enorrmann, thank you for your reply!
Yes i have, nothing happens(the checkbox doesn't get 'checked' when i click on it, it doesn't react at all)

**Comment by Michaaaaaaaa** [comment]
So nobody has an idea what might be wrong? Don't want to annoy, but if there's no solution i want to know so i can move on.

**Comment by Xpktro** [comment]
@Michaaaaaaaa I stumbled upon this issue in Linux while swapping sound systems. Somehow the Giada config file is not being refreshed properly. Try deleting it first and restarting.

**Comment by gvnnz** [comment]
> Hi enorrmann, thank you for your reply! Yes i have, nothing happens(the checkbox doesn't get 'checked' when i click on it, it doesn't react at all)

@Michaaaaaaaa  this is odd. Once checked, the input list should get enabled: you can now choose the input device from the drop down menu (initially it's empty). Is that menu empty for you?

**Comment by Michaaaaaaaa** [comment]
Hey, thank you both for your help!

> @Michaaaaaaaa I stumbled upon this issue in Linux while swapping sound systems. Somehow the Giada config file is not being refreshed properly. Try deleting it first and restarting.

I did, and it did change something: I was able to use Direct Sound as sound system, but not Asio.
However, i took a look at the config file and found the line (after selecting Direct Sound):
"sound_device_in":5,"sound_device_out":1,"sound_system":3

after selecting Asio as sound system (and the input being back to greyed out), the line became:
"sound_device_in":5,"sound_device_out":1,"sound_system":4,

So i edited the txt file to this, just to see what happens:
"sound_device_in":1,"sound_device_out":1,"sound_system":4,
...and voila, next time i start up, the previously unselectable input was set to the one i wanted.
yeaaah :-)

> @Michaaaaaaaa this is odd. Once checked, the input list should get enabled: you can now choose the input device from the drop down menu (nothing is selected initially). Is that menu empty for you?

Just for completeness: No, as described, there was nothing happening at all. The menu did not show anything (see screenshot), nor react in any way, Nothing could be selected because nothing moved, unfolded or happended otherwise if clicked. It was dead pixels all the way.

Thank you :-)

**Comment by gvnnz** [comment]
Thank you for your feedback @Michaaaaaaaa . Looks like there are some refresh issues with the config file, especially when it comes to the input sound device. It might be worth writing some CI tests to iron this out.

**Comment by Michaaaaaaaa** [comment]
> No, as described, there was nothing happening at all. The menu did not show anything (see screenshot), nor react in any way, Nothing could be selected because nothing moved, unfolded or happended otherwise if clicked. It was dead pixels all the way.

To be clear, the program did NOT crash, it was still usable. What i meant was that only the input select box was dead.

**Comment by bradphelan** [comment]
Found a work around. With giada.exe not running. Open the giada.conf in a text editor.  Change the setting

```
"sound_device_in":-1
```
to
```
"sound_device_in":0
```

Start giada.exe

It will tell you that the audio input device is incorrectly configured. But now when you open the configuration dialog the option to choose a sound input is now available. When I closed giada.exe and inspected the configuration file I found.

```
"sound_device_in":6
```

**Comment by journey-of-code** [comment]
@bradphelan : I had the same issue on Windows 10.0.19044.1586 (not being able to select an input device). With your method, I could finally enable the input (setting input device to 0 in the config and then selecting it).

**Comment by gvnnz** [comment]
Please guys check again with version 0.25.0, which features many improvements to the whole "Configuration" experience.

**Comment by gvnnz** [comment]
No feedback, closing.
