### ISSUE TITLE
MIDI lightning learning doesn't work if MIDI input not enabled

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#527]
The MIDI learning process for the MIDI lightning setup doesn't work if MIDI input is not enabled first. Sometimes this is confusing in the following screen:

![1](https://user-images.githubusercontent.com/39955275/141676769-55188f52-4335-41be-9f63-eaa84492b4b0.png)

MIDI lightning output is enabled, but learning doesn't work until you enable MIDI input in the "Setup MIDI input" window. The MIDI input should be enabled automatically when the "Enable MIDI lightning output" flag is checked.

**Comment by gvnnz** [comment]
Moving to 0.26, the usability milestone.

**Comment by gvnnz** [comment]
Done in 9e82dbdb28756b82e315853788e7b8e165525e99.
