### ISSUE TITLE
RTAudio version inconsistency

### ISSUE THREAD

**Issue by musicinmybrain** [monocasual/giada#535]
**Environment**
- OS: N/A
- Giada version: 0.19.1

**Describe the bug**
The changelog for 0.19.1 says RTAudio is upgraded to 5.2.0, but as of the `v0.19.1` tag, the git submodule references a commit of RTAudio with internal version number ` 6.0.0beta1`.

**To Reproduce**
1. Examine the git repository as of tag `v0.19.1`.

**Expected behavior**
RTAudio version is consistent between changelog message and git.

**Screenshots**
N/A

**Additional context**

This is mostly just a heads-up.

**Comment by gvnnz** [comment]
0f62d807 RtAudio updated to 6.0.0beta1. Changelog entry will follow. Closing.
