### ISSUE TITLE
Recursive buffer rendering?

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#538]
Currently is not possible to play very short audio samples in continuous loop modes such as single.endless mode. This is because the audio data gets rendered only twice (at most): the [normal chunk while playing](https://github.com/monocasual/giada/blob/master/src/core/channels/samplePlayer.cpp#L147) AND [the head of the sample in case of looping](https://github.com/monocasual/giada/blob/master/src/core/channels/samplePlayer.cpp#L164). If the sample is very short, shorter than an audio block, the audio data is copied only twice, leaving part of the buffer empty.

**Comment by gvnnz** [comment]
Done in 77746e1, closing.
