### ISSUE TITLE
Version number in release title field?

### ISSUE THREAD

**Issue by mxmilkiib** [monocasual/giada#550]
**Is your feature request related to a problem? Please describe.**
Items on https://github.com/monocasual/giada/releases don't include version numbers in their titles. This makes it impossible to parse the version from the releases.atom feed.

**Describe the solution you'd like**
If release titles could be prefixed with the version numbers, like "v0.20.0 Alicanto"?

**Additional context**
This is for https://libreav.org

**Comment by gvnnz** [comment]
Interesting, I wasn't aware of the atom thing. Can't you just parse the `id` tag? E.g.:

`<id>tag:github.com,2008:Repository/6603254/v0.20.0</id>`

**Comment by mxmilkiib** [comment]
Unfortunately there's no facility in the Drupal 8/9 Feeds ecosystem for conditional parsing, and there are radically different variations used for the id element (e.g SourceForge feeds give just a hash for id).

**Comment by gvnnz** [comment]
OK cool, we'll add the version number along with the release title. I'll start from the last one (v0.20.0).
