### ISSUE TITLE
- no ports found - (MIDI)

### ISSUE THREAD

**Issue by MiLO83** [monocasual/giada#557]
**Environment**
- OS: Win 11 x64
- Giada version: 0.20.0

**Describe the bug**
- no ports found - (MIDI)
I have loopbe1 and loopmidi installed it detects neither. :(

**Screenshots**
![Screenshot 2022-02-14 194938](https://user-images.githubusercontent.com/5951434/153989290-fcd2291f-ea4d-4c5c-b056-13c455ca5475.png)

**Comment by gvnnz** [comment]
Hey @MiLO83  , you have to enable it by checking the box on the right. Both for Output and Input port. Hope it helps.

**Comment by gvnnz** [comment]
On a second thought, I think the available ports should be scanned on startup, regardless of the port status (enabled or disabled). This will improve the user experience.

**Comment by gvnnz** [comment]
Done, closing.
