### ISSUE TITLE
Windows: Some (specific vendor?) VST3 plugins do not have any impact, neither on sample channel, nor on input, nor on output

### ISSUE THREAD

**Issue by CTBlaze** [monocasual/giada#563]
Now I can record via audio interface, I tried different plugins, first on sample channel, then on input and output.
The audio just don't seem to be routed there (or back), no impact of the FX on the audio at all. 
Log attached.  [giada.log](https://github.com/monocasual/giada/files/8096937/giada.log)
example screen, no errors apparently
![image](https://user-images.githubusercontent.com/99221765/154680218-28f16a5f-4e48-4002-9f7f-61082e47eda0.png)

**Comment by gvnnz** [comment]
According to the screenshot there's no sample loaded in your channel, so nothing gets processed. If you want to route incoming audio to that channel for recording, you have to "arm" it first (the record button, 2nd one from the left). If you also want to hear it, select "input monitor" from the channel's drop-down menu.

**Comment by CTBlaze** [comment]
> According to the screenshot there's no sample loaded in your channel, so nothing gets processed. If you want to route incoming audio to that channel for recording, you have to "arm" it first (the record button, 2nd one from the left). If you also want to hear it, select "input monitor" from the channel's drop-down menu.

Ciao Giovanni, sorry the screenshot made that impression, just wanted to show the loaded VST.. ;)
After finally being able to record (see my initial audio interface issue), 
of course I spend MANY HOURS to get it right, tried everything. 
Recorded samples, loaded samples from disk, tried FX in the channel level, at input and at output level. 
In no case the loaded and enabled VSTs had any impact on the audio, I swear! It's very frustrating , because I REALLY WANT GIADA TO WORK FOR ME, the concept is excellent. 
I am no dummy with computers, nor with audio stuff nor with looping stuff.
Giada also crashed on me liek 4-5 times, w/o warning, just disappeared.  But that's another issue.
PLus, I realized that when I record audio (voice), it's kinda time shifted/magled right away, also another issue, will open that.

How can we test the VST/FX issuer here more? WHat info/data do you need from me? it seems the log does not tell us anything, right?

**Comment by CTBlaze** [comment]
PS: just now it crashed, while having the FX dialog open, removed a (non working) VST, selected another, and on OK it crashed, force close, nothing in the logs.
Also, NOTHING about recording a sample in the log at all - is that on purpose?

**Comment by CTBlaze** [comment]
OK, some more testing:
I can confirm that audio is being SENT to FX, see screen with meter plugin. yet, any FX that should have an audible impact, do not. Have to try instrument VST to see if geenrated audio arrives in Giada, so far I have only tried effects processing the audio played by Giada.
![image](https://user-images.githubusercontent.com/99221765/154801075-25641191-bd51-4076-babd-27f494e0c3ad.png)

**Comment by CTBlaze** [comment]
here a notification output from the stdout, thought it might interest you:
![image](https://user-images.githubusercontent.com/99221765/154801209-c399bb29-a054-4d18-8eaa-92b265b11a7f.png)

**Comment by CTBlaze** [comment]
more news: I tried a VST3 from Audiothing today... and THAT one worked!?
Any idea, why all my Native Instruments or Plugin Alliance (major market players) would not work in Giada?
As in: no impact on audio (is the VST routing bonkers?)
![image](https://user-images.githubusercontent.com/99221765/154864751-c8970db8-e3fb-4182-bbfb-857c7c80118c.png)

**Comment by CTBlaze** [comment]
also, ROLAND Instrument VST3 seem to work! Notes I did put in the action editor in a test MIDI channel come out fine of the synth engine and out of the speakers. 
![image](https://user-images.githubusercontent.com/99221765/154865087-bdcad282-5b0c-43c4-91cc-f6cce53a00d9.png)

**Comment by CTBlaze** [comment]
So how can we find out what's wrong with the ones from Native Instruments , or some from Plugin Alliance, like from Unfiltered Audio? THis one does not have any impact on the audio at all ;( works fine in other hosts
![image](https://user-images.githubusercontent.com/99221765/154866084-f339dbf6-79e2-43c9-a7fd-775013a86319.png)

**Comment by CTBlaze** [comment]
ALso for Overloud TH3 VST3, the audio does not even arrive... ;(
![image](https://user-images.githubusercontent.com/99221765/154866319-df0b9746-8c30-43f7-92db-22d11c7ba041.png)

**Comment by CTBlaze** [comment]
So which do I have found not working so far? VST3s from the following vendors/providers:
- Native Instruments
- Overloud
- Unfiltered Audio
- Togu Audio Line (TAL)

@gvnnz would you care to try a free TAL VST3 plugin yourself?
see https://tal-software.com/products in the free plugins section
Native Instruments also has trials of course, e.g. for Driver, Supercharger, Phasis etc.

**Comment by gvnnz** [comment]
@CTBlaze I'm currently using [TAL reverb 4](https://tal-software.com/products/tal-reverb-4) on Linux and it works as expected. Could this be a Windows issue? Can you try it too? 

Later on I'll give it a spin on Windows and see what happens. I'll also try some of the Native Instruments demos. I'll keep you posted.

**Comment by CTBlaze** [comment]
@gvnnz I do confirm that TAL Reverb 4 works fine, in Windows. Can you please try the [TAL Filter-2](https://tal-software.com/products/tal-filter) please? That one does not seem to work here... (sorry I only tested the filter of TAL)
TH3 by Overloud doesn't get the audio (no input visible in the plug, no impact audible).
The Native Instruments FX, Like Choral, Phasis, Driver, Supercharger - startup fine, but do not seem to do anything (mayber also  do not get the audio for processing?)

**Comment by CTBlaze** [comment]
Update - no better news - I upgraded to Overloud TH-U Guitar Modeling software.
Same behaviour as with TH-3 - the audio from the Giada sample channel does arrive at the VST3 plugin... dang
![image](https://user-images.githubusercontent.com/99221765/155900287-32c80c9f-599a-4d90-9742-7d98cf092759.png)

**Comment by gvnnz** [comment]
I was able to reproduce this with any plug-in that takes both MIDI and audio in input (like TH-U for example). A fix is coming soon.

**Comment by CTBlaze** [comment]
Bene, bene. Grazie!

**Comment by gvnnz** [comment]
Hopefully fixed in c255236001a88feef296f5112458362115fd2250 and included in version 0.21.0, out soon.

**Comment by gvnnz** [comment]
Closing. @CTBlaze please feel free to reopen it if the issue persists, once Giada 0.21 is out. Thanks!
