### ISSUE TITLE
giada-0.20.1 fails to build from source with g++-11

### ISSUE THREAD

**Issue by umlaeute** [monocasual/giada#570]
**Environment**
- OS: Debian/sid
- Giada version: 0.20.1
- compiler: g++ (Debian 11.2.0-18) 11.2.0

**Describe the bug**

giada fails to build from source with g++-11, as it uses `size_t` without also importing the `std` namespace in https://github.com/monocasual/giada/blob/e53867fd9e5ded0f173837fe30aa9aaa34c48c05/src/gui/elems/basics/flex.cpp#L93-L94

**Screenshots**

https://salsa.debian.org/multimedia-team/giada/-/jobs/2523675#L3163

**Additional context**
possible fixes are:
- use `std::size_t` instead of `size_t`
- add `using std::size_t;`
- add `using namespace std;`
- add `#include <csstddef>`

**Comment by umlaeute** [comment]
ah, i've just seen https://github.com/monocasual/giada/pull/566 which fixes this

**Comment by gvnnz** [comment]
#566 merged, closing. Thanks for reporting
