### ISSUE TITLE
Ability to open more than one plug-in UI

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#575]
Currently only one VST window can be opened at once. Having more than one visible is useful, so you can tweak parameters manually (with the mouse) across different plugins.

EDIT: multiple VST windows _can_ be opened, but only for VSTs from the same channel.

**Comment by CTBlaze** [comment]
Yes, e.g. a meter and/or spectral analysis plugin in the master slot should always be visible, if the user wishes to... can be very helpful

**Comment by gvnnz** [comment]
Done in branch `multi-plugin-ui`, closing.
