### ISSUE TITLE
Mac not capturing audio/midi

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [monocasual/giada#583]
Macbook M1 Monterey 12.3.1
Giada 0.21.0

Not capturing any audio or MIDI.

Trying to sample from iPad over lightning/usb/idam w/e. Giada is failing to capture any audio. Not capturing MIDI either, tried with bluetooth and usb.

**Comment by gvnnz** [comment]
Can you please launch Giada from the terminal and paste here the debug output? [Here](https://github.com/monocasual/giada/discussions/584)'s how to enable it.

**Comment by ST33LDI9ITAL** [comment]
[init] Giada 0.22.0
[init] Build date: May 13 2022
[init] Release build
[init] Dependencies:
[init]   FLTK - 1.3.8
[init]   RtAudio - 6.0.0beta1
[init]   RtMidi - 5.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.1.0
[init]   JSON for modern C++ - 3.9.1
[KA] Compiled RtAudio APIs: 1
  CoreAudio
[MidiMapper::init] scanning midimaps directory '/Users/st33l/Library/Application Support/Giada/midimaps'...
[MidiMapper::init] unable to scan midimaps directory!
[MidiMapper::read] midiMap not specified, nothing to do
[Engine::init] MIDI map read failed!
[KA] using system 0x5
[KA] Opening device out=3, in=0, samplerate=44100
[KA] 7 device(s) found
  0) Apple Inc.: iPhone
      ins=2 outs=0 duplex=0
      isDefaultOut=0 isDefaultIn=1
      sampleRates:
	44100 
  1) Existential Audio Inc.: BlackHole 8ch
      ins=8 outs=8 duplex=8
      isDefaultOut=0 isDefaultIn=0
      sampleRates:
	8000 16000 44100 48000 88200 96000 176400 192000 352800 384000 705600 768000 
  2) Apple Inc.: MacBook Pro Microphone
      ins=1 outs=0 duplex=0
      isDefaultOut=0 isDefaultIn=0
      sampleRates:
	44100 48000 88200 96000 
  3) Apple Inc.: MacBook Pro Speakers
      ins=0 outs=2 duplex=0
      isDefaultOut=1 isDefaultIn=0
      sampleRates:
	44100 48000 88200 96000 
  4) Static Z Software: Sound Control Output
      ins=0 outs=2 duplex=0
      isDefaultOut=0 isDefaultIn=0
      sampleRates:
	44100 
  5) Apple Inc.: Aggregate Device
      ins=10 outs=10 duplex=10
      isDefaultOut=0 isDefaultIn=0
      sampleRates:
	8000 16000 44100 48000 88200 96000 176400 192000 352800 384000 705600 768000 
  6) Apple Inc.: Stereo Mix
      ins=0 outs=2 duplex=0
      isDefaultOut=0 isDefaultIn=0
      sampleRates:
	44100 48000 88200 96000 
[mixer::reset] buffers ready - maxFramesInLoop=529200, framesInBuffer=1024
[mixer::enable] enabled
[KA] Start stream - latency = 110
[KM] Opening output device 'Giada MIDI output', port=1

RtMidiOut: no compiled support for specified API argument!


[KM] Opening input device 'Giada MIDI input', port=1

RtMidiIn: no compiled support for specified API argument!


[KM] Device 'Giada MIDI output': 2 MIDI ports found
  0) iPhone
  1) midiLE USB Dest
[KM] Device 'Giada MIDI input': 2 MIDI ports found
  0) iPhone
  1) midiLE USB Source

Well, I managed to get it compiled and audio works now, somewhat. Recording and playing works but can't monitor with stream linker to hear samples before recording.. stream linker/hear what playing not working. I tried every work around I could think of but couldn't get it.

**Comment by gvnnz** [comment]
From the message

> RtMidiOut: no compiled support for specified API argument!

it seems the RtMidi lib has been built on macOS without the necessary API. Will get fixed in the next release 0.22.

> Recording and playing works but can't monitor with stream linker to hear samples before recording.. 

Can you please open a new issue for this one? Thank you!

**Comment by gvnnz** [comment]
Also reported here: https://github.com/microsoft/vcpkg/issues/6993

**Comment by gvnnz** [comment]
This should have been fixed in version 0.22. Just tested on my virtualized macOS. @ST33LDI9ITAL can you confirm?

**Comment by gvnnz** [comment]
No feedback, closing.
