### ISSUE TITLE
Stream linker / Hear what played monitor mode not working

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [monocasual/giada#585]
Giada master @ [aed7dc3]
M1 Mac Monterey

Toggle stream linker on and no sound output. Tried various ways of mixing audio to no effect. Records and plays back audio fine, but not "hear what playing".

**Comment by gvnnz** [comment]
Reproduced also on Linux version.

**Comment by gvnnz** [comment]
Fixed in 1b99c0a2e812f2923d0196a30b08c31c2960aaa6. Closing.
