### ISSUE TITLE
`GLIBCXX_3.4.26' not found Required By AppImage

### ISSUE THREAD

**Issue by DroWnThePoor** [monocasual/giada#587]
On Ubuntu 18.04(GNOME)
Appimage v0.21.0 

Attempting to run results in: 
./Giada-v0.21.0-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./Giada-v0.21.0-x86_64.AppImage)

strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25

I've seen this on other AppImage issues and considered adding the toolchain-r/test PPA, but it made me nervous to go through with it.

**Comment by gvnnz** [comment]
Thanks, I can reproduce this too. 0.19.2 seems the last working version.

**Comment by gvnnz** [comment]
This is probably related to https://github.com/monocasual/giada/commit/5fe46bebf22c4c15291ef0228a0bf7eca61d5cc4, where we updated GCC from 8 to 10. I guess we have to live with it at this point and add the GLIBCXX_* >= 3.4.25 as a requirement.
