### ISSUE TITLE
Duplicated .desktop file

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#591]
**Environment**
All.

**Describe the bug**
The file `extras/com.giadamusic.Giada.desktop` is the source of truth for the Linux `.desktop` file, but the [`make-package.sh` script](https://github.com/monocasual/giada/blob/master/.github/scripts/linux/make-package.sh#L17) defines its own (outdated) version. The packager script should include `extras/com.giadamusic.Giada.desktop` instead.

**Comment by gvnnz** [comment]
Done in https://github.com/monocasual/giada/commit/f167bed948cc0e9b0d8791f236b03709e5adab2d.
