### ISSUE TITLE
Weird noise when playing two cloned Sample Channels with altered pitch

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#602]
**Environment**
All.

**To Reproduce**
1. Create a Sample Channel, load a sample in it and set the pitch to != 1.0;
2. Clone the channel and set the pitch to != 1.0;
3. Play the two channels together: weird noise is generated.

**Comment by gvnnz** [comment]
Fixed in 2054a916858fe499201e7255b58e99aefba18a9d, closing.
