### ISSUE TITLE
no juce cmakelist in /deps/juce when build with source code release

### ISSUE THREAD

**Issue by silverhikari** [monocasual/giada#610]
**Environment**
- OS: Manjaro
- Giada version: 0.23.0

**Describe the bug**
when build giada with the source code release avaible on the website, there is no cmakelists.txt in the juce dependency folder

**To Reproduce**
1. download source code release of website and extract
2. run cmake with options (the options used -DCMAKE_INSTALL_PREFIX=/usr  -DWITH_VST3=ON -W no-dev
3. cmake fails

**Expected behavior**
cmake completes and continue to rest of build.

**Comment by gvnnz** [comment]
Thanks @silverhikari for the report and sorry for the delay. We will look into it.

**Comment by mazes-80** [comment]
Seems that juce is not exported in archive. I manually downloaded juce and it works about juce.

However as exports for dependencies failed in archive I encounter the same problem with fltk.
I tried to unbundle things as I'm gentoo user, but it seems that my current system fltk version diverge from the one used in project, moreover it seems that fltk used by giada is a static library not being compiled from sources.
I may open another issue about fltk when I feel brave enough.

**Comment by gvnnz** [comment]
Fixed, will be applied to the next release - 0.25.1 coming out soon.

**Comment by mazes-80** [comment]
I'm trying to make a package for giada for gentoo. For now I consider this package as a draft, even usable, I got to tweak the build system quite a lot.

Among disturbing things:
got to add to my cxxflags:
 * -I/usr/include/r1tmidi/ maybe gentoo does not follow classic path for rt1midi headers ?
 * -no-pie : related to fltk being built as a static library I guess

Having juce included in the archive seems a quite nice step, thanks.

**Comment by gvnnz** [comment]
> Among disturbing things: got to add to my cxxflags:
> 
> * -I/usr/include/r1tmidi/ maybe gentoo does not follow classic path for rt1midi headers ?
> * -no-pie : related to fltk being built as a static library I guess
> 

Unfortunately we are limited to the traditional Ubuntu scenario here, I can't help much with Gentoo or other distro. Please feel free to submit patches!
