### ISSUE TITLE
BUG of moving windows for VST Plugin Window

### ISSUE THREAD

**Issue by LoveBodhi** [monocasual/giada#621]
**Environment**
- OS: Windows 10
- Giada version: 0.23.2

**Describe the bug**
When moving VST plugin window, it shrinks and the user have to re-open manually again!

**To Reproduce**

1. Click "Add Column"
2. Click "Add MIDI Channel", then click "FX"
3. Add new plugin (I used tuning workbench synth for testing purpose)
4. Click the name, open the VST Plugin window (GUI)
5. Move the window

**Expected behavior**
Window size has been incorrectly shrank, and the only way is close and re-open.

**Screenshots**
![捕获 giada11](https://user-images.githubusercontent.com/37089530/207621641-63abcd26-83ba-4dc6-b6b8-2ddfcf9d1047.PNG)

**Additional context**
None

**Comment by gvnnz** [comment]
FIxed in 6625256, closing.
