### ISSUE TITLE
Right-click on a column's empty space should pop up the "Edit column" menu

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#628]
Currently it's not super clear how to add a new channel to a column, especially when the column is already filled with channels and the "Edit column" button is beyond the scroll viewport boundaries. Also right-clicking to add new channels feels more natural IMO.

**Comment by gvnnz** [comment]
Done in https://github.com/monocasual/giada/commit/250e10ca2453fee1efd6f457fa5b6461e8e922ae, closing.
