### ISSUE TITLE
Better explain why sometimes you can't record audio or enable specific audio recording modes

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#629]
You can record audio if:
* input device is enabled
* there is at least one empty and armed sample channel

You can enable free-looplength mode if:
* there are no channels, or...
* there are only empty sample channels

You can enable record-on-signal mode if:
* the sequencer is not running

Those info are written in the manual but sometimes it's not super clear why and how, and the buttons in the main transport just do nothing. I suggest to simply grey out buttons when you can't perform an action.

**Comment by gvnnz** [comment]
Done, closing.
