### ISSUE TITLE
Free loop length

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#63]
https://giadamusic.com/forum/viewtopic.php?t=46

> You start to record something by pressing one time the big rec button, then, when you have finished, at the second key press, Giada should adjust the beats/bpm to the length of your recording.

**Comment by keryell** [comment]
Update the URL to the message https://giadamusic.com/forum/viewtopic.php?t=46
I would love such a feature too.

**Comment by gvnnz** [comment]
Implemented in 36e3aa2643a6bb9ac21b135401b544073f1575f3 .
