### ISSUE TITLE
build fails on about.cpp with "error: call to non-‘constexpr’ function ‘const char* giada:: v ::Ui::getI18Text(const std::string&) const’"

### ISSUE THREAD

**Issue by silverhikari** [monocasual/giada#634]
**Environment**
- OS: Manjaro
- Giada version: 0.24.0
- GCC: 12.2.1

**Describe the bug**

build fails with the following error listed in title with the full error in log. this is done with the base settings enabled for cmake build.

error log and cmake configuration: https://paste.ee/p/jQs0E

**To Reproduce**
1. git clone https://github.com/monocasual/giada/
2. make build folder and cmake ..
3. make

**Expected behavior**
build completes and binary is made.

**Comment by edogawa23** [comment]
same here when trying to update the giada rpm package I maintain for openSUSE in OBS:
[https://build.opensuse.org/package/show/home:edogawa/giada](url)
(on a side note, see also the trivial patch to fix compilation via g++13 that Tumbleweed uses now)
Buildlog: 
[https://build.opensuse.org/public/build/home:edogawa/openSUSE_Tumbleweed/x86_64/giada/_log](url)

**Comment by hfiguiere** [comment]
Apparently this is also #626
