### ISSUE TITLE
Clear learned MIDI (Global and Channel)

### ISSUE THREAD

**Issue by PatDyn** [monocasual/giada#637]
**Is your feature request related to a problem? Please describe.**
Currently, it does not seem to be possible to clear the learned MIDI input. The only workaround now is to delete the channel or values in the config. 

**Describe the solution you'd like**
Having an "X" or "clear" button next to the "Learn" Button in the MIDI Input Setup both global and per channel would be nice.

**Describe alternatives you've considered**
Some form of click action on the MIDI code to delete the current value could work too.

Thanks, Giada works great for me so far! :)

**Comment by gvnnz** [comment]
Hey @PatDyn , it is possible actually by right-clicking on the value box, but it's super annoying. That's why we fixed it recently on the development version (see 2e310ed1), scheduled for version 0.25.

**Comment by PatDyn** [comment]
Hi @gvnnz ,
Thanks for the info! Weirdly, right-clicking does not work for me (Using Manjaro and v0.24 from AUR).

**Comment by PatDyn** [comment]
Update:
Clearing by right click works only, when the channel of the learned MIDI input and the input channel are the same. Changing the channel will effectively break clearing the learned midi.

**Comment by gvnnz** [comment]
@PatDyn please try the new version 0.25, where we added the almighty "Clear" button next to the MIDI binding box. Thanks!
