### ISSUE TITLE
Midi In/Out Ports not created on AppImage build

### ISSUE THREAD

**Issue by PatDyn** [monocasual/giada#649]
**Environment**
- OS: Manjaro 22.1
- Giada version: 0.25
- a2jmidi
- jack: 1.9.22 with qjackctl
- carla 2.5.4

**Describe the bug**
The in/out midi ports are not created on giada startup
with jack server running.

**To Reproduce**
0. Start jack
1. Start giada
2. go to config
3. check the midi tab
4. no ports are visible
5. check jack/carla connection graph 
6. no ports created either

**Expected behavior**
Ports should be visible on connection graph and in the giada settings.

**Comment by PatDyn** [comment]
This is the corresponding log output:

[mixer::enable] enabled
[KA] Start stream - latency = 0
ALSA lib .././../src/v1.2.6.1-c343e99f4e.clean/src/conf.c:4553:(snd_config_update_r) Cannot access file /home/runner/work/giada/giada/build/vcpkg_installed/x64-linux/share/alsa/alsa.conf
ALSA lib ../.././../src/v1.2.6.1-c343e99f4e.clean/src/seq/seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

MidiOutAlsa::initialize: error creating ALSA sequencer client object.

[KM] Error opening device 'Giada MIDI output': MidiOutAlsa::initialize: error creating ALSA sequencer client object.
ALSA lib .././../src/v1.2.6.1-c343e99f4e.clean/src/conf.c:4553:(snd_config_update_r) Cannot access file /home/runner/work/giada/giada/build/vcpkg_installed/x64-linux/share/alsa/alsa.conf
ALSA lib ../.././../src/v1.2.6.1-c343e99f4e.clean/src/seq/seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

MidiInAlsa::initialize: error creating ALSA sequencer client object.

[KM] Error opening device 'Giada MIDI input': MidiInAlsa::initialize: error creating ALSA sequencer client object.
[MidiMapper::init] total midimaps found: 3
[MidiMapper::read] MIDI map read failed!
[LangMapper::init] total langmaps found: 0
[init] Giada 0.25.0
[init] Build date: Jun  3 2023
[init] Release build
[init] Dependencies:
[init]   FLTK - 1.4.0
[init]   RtAudio - 6.0.0beta1
[init]   RtMidi - 5.0.0
[init]   Libsamplerate
[init]   Libsndfile - libsndfile-1.0.31
[init]   JSON for modern C++ - 3.10.5
[init]   JUCE - 7.0.5
[KA] Compiled RtAudio APIs: 4
  JACK
  PulseAudio
  ALSA
  Dummy
[KM] Compiled RtMidi APIs: 1
  ALSA

**Comment by gvnnz** [comment]
@PatDyn can you confirm you're using the AppImage package downloaded from the website?

**Comment by PatDyn** [comment]
Yes. I definitely used the AppImage package from the website. :)

**Comment by gvnnz** [comment]
Ok great, so there's a problem with the ALSA lib shipped by vcpkg. Thanks for reporting!
