### ISSUE TITLE
Arch linux build and install failed

### ISSUE THREAD

**Issue by vanarok** [monocasual/giada#653]
**Environment**
- OS: Arch linux
- Giada version: v0.25.0

**Describe the bug**
Failed to install master on arch linux without intervention.

I had to roll back gcc to 12.1.0 and use the branch https://github.com/monocasual/giada/pull/652

**To Reproduce**
1. Build master
2. See build error
3. Go to pull https://github.com/monocasual/giada/pull/652
4. Build project
5. See build error
6. Downgrade gcc to 12.1.0
7. Build project success

**Expected behavior**
Simple install

**Comment by vanarok** [comment]
I don't mind if this issue gets closed, I created it specifically for those who run into this issue on arch linux.

**Comment by silverhikari** [comment]
hello i am the maintainer for the giada build on archlinux. can you tell me what was the build error you were seeing when trying to build with gcc 13?

**Comment by gvnnz** [comment]
@vanarok and @silverhikari: PR https://github.com/monocasual/giada/pull/652 has been merged, so the issue has been fixed. Thank you for your time!

**Comment by luzpaz** [comment]
Close ticket ?
