### ISSUE TITLE
Better legend scrolling in Action Editor

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#655]
The vertical legend printed in each widget disappears when scrolling to the right:

![Screenshot_2023-07-07_18-47-03](https://github.com/monocasual/giada/assets/39955275/638cf093-ebe4-4592-8e8c-a973c83c76a6)
![Screenshot_2023-07-07_18-46-09](https://github.com/monocasual/giada/assets/39955275/a192addd-52f3-4fe5-85bf-968c258fcfad)

It would be nice to have a floating legend that stays sticky during the whole scroll movement.

**Comment by gvnnz** [comment]
Done, will be shipped with v.0.26.
