### ISSUE TITLE
0.25.1 libmp3lame is missing on windows 11. Cannot launch program.

### ISSUE THREAD

**Issue by PieterHagedoorn** [monocasual/giada#661]
**Environment**
- OS: [Windows 11]
- Giada version: [v0.25.1]

**Describe the bug**
When you double click the program to launch, it throws a popup with an error: "The code execution cannot proceed because libmp3lame.DLL was not found. Reinstalling the program may fix this problem." Reinstalling does not work. This bug does happen for version 0.25.1.

**To Reproduce**
1. Go to '[the download page](https://www.giadamusic.com/index#download)' and download the newest windows version.
2. Double click the exe to launch the program.
3. encounter error

**Expected behavior**
The program should have launched without errors.

**Comment by tpk109** [comment]
Same problem here. Win 10.

**Comment by gvnnz** [comment]
Fixed in 89db096848d0b5a18d7d588ec0cefa24121e0649.
