### ISSUE TITLE
No Jack Transport Sync

### ISSUE THREAD

**Issue by PatDyn** [monocasual/giada#662]
**Environment**
- OS: Manjaro and Linux Mint 21 Vanessa
- Giada version: v0.25.1 

**Describe the bug**
When using multiple programs that utilize jack transport option (like play, stop, pause) Giada does not sync.

**To Reproduce**
* Start jack server (e.g. via qjackctl).
* Start a program that uses jack transport, for example Hydrogen or Carla
* Start Giada
* Start playback on H2 or Carla
* Giada will not sync to running transport

*Other way around*
* With all playback stopped
* Start playback in giada
* Transport will not sync to other applications

**Expected behavior**
The transport should change simultaneously on all applications when changed in one place.

**Additional context**
Using qjackctl and jack2

**Comment by gvnnz** [comment]
Just tested this on latest master (0650238a7a21810ed37bcd6266feac4591df5881) with Renoise + JACK transport, could not reproduce it. Please @PatDyn feel free to reopen the issue otherwise.
