### ISSUE TITLE
Windows: libmp3lame.DLL was not found during installation

### ISSUE THREAD

**Issue by bluntrapture** [monocasual/giada#668]
### Discussed in https://github.com/monocasual/giada/discussions/664

<div type='discussions-op-text'>

<sup>Originally posted by **jonasbue** August 26, 2023</sup>
The Windows installer (Windows 11) stopped because the libmp3lame.DLL file is missing/not found.

How do I approach this? Is it a missing dependency I need to install myself?
Thanks for any help :)</div>

**Comment by bluntrapture** [comment]
I tried to download Giada looper to my Windows 11 pc, and I am unable to load it because I'm missing liblmp3lame.dll

After 2 weeks of going crazy, I finally found this discussion, see that it's apparently been fixed.......

But no matter how up-to-date the download for Giada is, it still says it's missing.

I've looked everywhere and tried everything to no avail. (At least what I can understand.)

Not only is libmp3lame.dll missing, there doesn't seem to be any SUPPORT for Giada.

Has anyone successfully downloaded it, or know how to fix this missing dll?

I'm not an advanced technician --- just a dumb guy, so please keep it simple.

**Comment by gvnnz** [comment]
Fixed in 0.26.0, please download the new version and try again. Thanks!
