### ISSUE TITLE
Error message at startup: Your soundcard isn't configured correctly!

### ISSUE THREAD

**Issue by yurivict** [monocasual/giada#669]
**Environment**
- OS: FreeBSD 13.2
- Giada version: 0.26.0 (0.17.1 had the same message)

**Describe the bug**
When Giada is started, the popup box is displayed with the message from the subject.

**Additional info**
The error message should say what exactly is wrong: what audio backend, what audio endpoint returned what error.
The error message should also suggest how to correct the problem: open the Config screen, click on this or that, change this or that.

**Comment by gvnnz** [comment]
Done in cacdd1a6d971e36ec495445c948d996dd3187dde, closing. Thank you guys.
