### ISSUE TITLE
Need help compiling on Debian 11!

### ISSUE THREAD

**Issue by KYOSUKE-SATAKE** [monocasual/giada#671]
Hi,

I'm trying to compile on antiX (Debian based distro) and CMake has successfully generated the script.
However, when I tried to build it, I got this error.

In file included from /home/X/Documents/giada/src/core/engine.cpp:33:
/home/X/Documents/giada/src/utils/log.h: In function ‘void giada::u::log::print(const char*, Args&& ...)’:
/home/X/Documents/giada/src/utils/log.h:70:25: error: ‘runtime’ is not a member of ‘fmt’
   70 |   fmt::print(file, fmt::runtime(format), args...);
      |                         ^~~~~~~
/home/X/Documents/giada/src/utils/log.h:72:19: error: ‘runtime’ is not a member of ‘fmt’
   72 |   fmt::print(fmt::runtime(format), args...);
      |                   ^~~~~~~
gmake[2]: *** [CMakeFiles/giada.dir/build.make:108: CMakeFiles/giada.dir/src/core/engine.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:174: CMakeFiles/giada.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2

Could someone help me out?
Thank you for your help in advance!

**Comment by gvnnz** [comment]
Hey @KYOSUKE-SATAKE , are you following [these instructions]https://giadamusic.com/documentation-compiling-from-source), using vcpkg for installing the dependencies?

**Comment by KYOSUKE-SATAKE** [comment]
Sorry for my late reply. I got locked out from my own account.

Thank you for your reply!
Yeah, I'm following those instructions except that I've manually installed dependencies using apt.

**Comment by KYOSUKE-SATAKE** [comment]
I've decided to do the compilation process on a different distro in a virtual machine.
That way I can at least generate appimage that works on antiX as well.

Thank you again for those who took the time to read this and tried to help me out!
