### ISSUE TITLE
Changelog: please append 'Unreleased' to the development version to make it easier for downstream maintainers to parse file

### ISSUE THREAD

**Issue by luzpaz** [monocasual/giada#674]
![Screenshot_20231221_145113](https://github.com/monocasual/giada/assets/4140247/dd06c435-1071-442c-a068-a85f6720d6f8)

Mockup of the [ChangeLog](https://github.com/monocasual/giada/blob/master/ChangeLog) so that it makes it easier to parse the changelog for the current released version.

**Comment by gvnnz** [comment]
Thanks @luzpaz, will do. Out of curiosity: are maintainers really used to grab the latest, unreleased, bleeding edge version?

**Comment by luzpaz** [comment]
Some do, but this is more relevant to pulling the correct latest stable changelog info.

**Comment by gvnnz** [comment]
Done, closing. Thanks!
