### ISSUE TITLE
Begin/end points in Sample Channels get messed up when sample rate differs

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#680]
**Environment**
- OS: all
- Giada version: 0.26.1

**To Reproduce**
1. Create a project with a sample channel with begin/end points set somewhere
2. save it, then close it
3. change sound card sample rate to another value
4. open the previously saved project, see error in sample editor: begin/end points are wrong

**Comment by gvnnz** [comment]
Fixed, closing.
