### ISSUE TITLE
test-suite fails

### ISSUE THREAD

**Issue by umlaeute** [monocasual/giada#69]
the test-suite in todays HEAD is failing, mainly because test-files are missing:

## wave

```
tests/wave.cpp:18: FAILED:
  REQUIRE( w1.open("test.wav") == 1 )
with expansion:
  0 == 1
```
which comes without suprise, as there is no `test.wav` file in the first place. (i guess it has been removed from the repository)
so i remove the wave.cpp from the tests

## midiMapConf

next failing test

```
[MidiMapConf::init] scanning midimaps directory...
[MidiMapConf::init] unable to scan midimaps directory!

 -~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
giada_tests is a Catch v1.2.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
Test MidiMapConf class
  test read
-------------------------------------------------------------------------------
tests/midiMapConf.cpp:9
...............................................................................

tests/midiMapConf.cpp:59: FAILED:
  REQUIRE( midimap.maps.size() >= 2 )
with expansion:
  0 >= 2
```

well, yes; i don't have a `~/.giada/midimaps/` directory to scan (btw, shouldn't the error mention which directory was (not) scanned?) - but i think the test should be self-contained and not make assumptions about the contents of the home-directory of the user running the tests.
if the midimaps directory is not available, i think the test should be skipped!

## success?
so after removing beth `tests/wave.cpp` and `tests/midiMapConf.cpp` from the test-sources (leaving only a few other tests to run) now the test succeeds.

**Comment by monocasual** [comment]
Hi @umlaeute,

Actually the tests are crafted for Travis.ci and they rely upon `travis.yml` script, which takes care of all those "dependencies" (wave files, midimaps and now also VST plugins). The script basically downloads the needed files, for example:

```
  # Download midimaps package for testing purposes

  - wget https://github.com/monocasual/giada-midimaps/archive/master.zip -O giada-midimaps-master.zip
  - unzip giada-midimaps-master.zip
  - mkdir -p $HOME/.giada/midimaps
  - cp giada-midimaps-master/midimaps/* $HOME/.giada/midimaps
```

That's why the tests surely fail if not launched from Travis. I understand that this might be the wrong approach, since one would want to run the suite by itself without Travis. Any suggestion on the issue is welcome. Thanks for your feedback!

**Comment by umlaeute** [comment]
well, here's a suggestion: *document* this. (since you are using the standard autotools test target, chances are likely that people used to running test-suites will "automatically" run them).

the issue came up during Debian packaging that has a number of restrictions/assumptions:

- each package is automatically build on a plethora of different architectures
  - it can be assumed that most of these architectures have never been tested by upstream
  - therefore it is highly encouraged to run any test-suite
- network access during (automatic) builds is prohibited

the tests were obviously enabled because of the first point, but I know see that they should be disabled because of the last one.

**Comment by umlaeute** [comment]
btw, the Debian builds have VST-support disabled (due to licensing issues), so it seems there isn't much to test after all.

**Comment by umlaeute** [comment]
apart from that i still think that the test-suite should fail *gracefully* if the prerequisites are missing.

**Comment by monocasual** [comment]
I see your point, here. So what about something like a "--no-network" flag to pass to the test suite? If --no-network is enabled/true, all tests that require downloading anything would be skipped. What do you say?

**Comment by umlaeute** [comment]
how about: checking for the existence of a given file (e.g. the `test.wav`), and skip those test automatically?
you might even want to do that check in the configure-script (to keep the actual test-suite clean).

and  `--no-network` seems to imply a lot of things, and "i had no network to download the test-files" is not very high up on that list.

**Comment by monocasual** [comment]
> how about: checking for the existence of a given file (e.g. the test.wav), and skip those test automatically?

Much better! There is a semi-naive implementation in master branch now:

```
if test -f "./test.wav" && test -f "giada-midimaps-master.zip" && test -f "dexed.tar.xz" ; then
  AC_DEFINE(RUN_TESTS_WITH_LOCAL_FILES)
fi```

That macro is then used in the test suite to skip those tests that rely on samples, plugins, midimaps and so on for their internal workings.

**Comment by umlaeute** [comment]
cool; though i would check for the *actually* used files (`test.wav`) rather than the zip-files used for downloading them (`dexed.tar.xz`).

but anyhow, for my needs this is great.
