### ISSUE TITLE
allow to make reproducible builds

### ISSUE THREAD

**Issue by umlaeute** [monocasual/giada#70]
in order to make giada [build reproducibly](https://reproducible-builds.org/), Debian has patched the sources to allow overriding the value of `__DATE__`.

It would be great if this patch could be included in giada itself.

please find the [patch here](https://anonscm.debian.org/cgit/pkg-multimedia/giada.git/tree/debian/patches/0001-reproducible.patch)

**Comment by monocasual** [comment]
Done, thanks!
