### ISSUE TITLE
Can't clear keyboard bindings

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#708]
**Environment**
- OS: all
- Giada version: 1.1.0

**Describe the bug**
Can't clear keyboard bindings previously assigned.

**Comment by gvnnz** [comment]
Can't reproduce, probably related to #717. Closing

**Comment by gvnnz** [comment]
Actually fixed in https://github.com/monocasual/giada/commit/d12c15ac25410c8f8516e2585332717ff1531bb6.
