### ISSUE TITLE
Solo-ing a column channel doesn't fully mute others

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#709]
**Environment**
- OS: all
- Giada version: 1.1.0

**To Reproduce**
1. add two channels in two different columns;
2. add a delay or reverb to column channel 2;
3. play both channels;
4. solo column channel 1;
5. you can still hear the delay or reverb tail from column channel 2.

**Expected behavior**
Only channel 1 should be rendered, with no extra audio leftovers from other channels.

**Comment by gvnnz** [comment]
Fixed in https://github.com/monocasual/giada/commit/fbd650e9c80ffa36381bc15a05a5294cccd5dd28, closing.
