### ISSUE TITLE
Some "FX" buttons don't lit up when opening a project 

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#712]
**Environment**
- OS: all
- Giada version: 1.1.0

**Describe the bug**
Sometimes the FX buttons don't show the correct state if the channel contains plug-in: the state is always off. This only happens when loading a project.

**Comment by gvnnz** [comment]
Fixed in [8daf24d](https://github.com/monocasual/giada/commit/8daf24d87e5ef938794654145cc7867bf67724f5), closing.
