### ISSUE TITLE
Can't add actions in Action Editor very close to the rightmost edge

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#716]
**Environment**
- OS: Linux
- Giada version: 1.1.0

**Describe the bug**
Can't add actions in Action Editor when clicking in the area close to the rightmost edge. The bug is more noticeable at lower zoom levels (i.e. very zoomed-out).

**Comment by gvnnz** [comment]
Fixed in https://github.com/monocasual/giada/commit/653ab9858e756d426db396dfbea94da416ff2f2c, closing.
