### ISSUE TITLE
Channel out information doesn't refresh properly on MIDI channels

### ISSUE THREAD

**Issue by tblrchstr** [monocasual/giada#717]
**Environment**
- OS: Linux
- Giada version: 1.1.0

**Describe the bug**
When enabling or disabling MIDI output from a MIDI channel, the "ch X out" string is still visible on the channel's main button.

**To Reproduce**
1. Create a new MIDI channel
2. Open the MIDI output window and enable MIDI output, say on channel 1
3. Close the MIDI output window
4. See error: there is no "ch 1 out" message on the channel button. It appears only when another channel is added or removed.

**Comment by gvnnz** [comment]
Fixed in https://github.com/monocasual/giada/commit/1b7e8dfda94c06fe7919182e85a6d231dcd62f93.
