### ISSUE TITLE
VST3 support

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#72]
Depends on ~#73~ and #153.

**Comment by monocasual** [comment]
To be verified. Is this really feasible on the current Windows environment?

**Comment by tblrchstr** [comment]
on Linux: JUCE doesn't seem to support it yet.
on Windows: a Visual Studio build environment is required. Depends on #153 
on macOS: should work out of the box, still to be tested.

**Comment by addminztrator** [comment]
Please make this happen! This is the only feature I consider essential which is currently missing... If there was VST3 support, I'd pick Giada over Ableton every time!

**Comment by monocasual** [comment]
JUCE6 will support VST3 on Linux: https://forum.juce.com/t/announcing-juce-6/38698

**Comment by monocasual** [comment]
Done in 932b53664328cadc23fe7f92ab0e1650d18b26f5.
