### ISSUE TITLE
Configure can't find RtMidi.h on Arch linux

### ISSUE THREAD

**Issue by mzdravkov** [monocasual/giada#74]
Running the configure script on my Arch failed with error `configure: error: library 'rtMidi' not found!`

After a bit of searching I found out that for some reason the [rtmidi](https://aur.archlinux.org/packages/rtmidi) package has moved the RtMidi.h to be install to `/usr/include/rtmidi/` and not in the `/usr/include` as before.

Maybe you want to add this case in the configure file, or if not, I leave this issue here, so that people with this problem can find the problem quicker. So just making a symlink fixes the problem:

 `ln -s /usr/include/rtmidi/RtMidi.h /usr/include/RtMidi.h`

**Comment by monocasual** [comment]
Thanks, has the rtmidi package moved to the new path only on Arch?

**Comment by mzdravkov** [comment]
I don't know, sorry. I'm not involved in any way in the rtmidi project.

**Comment by rmattes** [comment]
No, the same problem shows up under Debian (testing)

    CPPFLAGS="-I /usr/include/rtmidi/"  ./configure --target=linux 

will get you through the configuration but seems suboptimal.

**Comment by SpotlightKid** [comment]
The AUR package for giada has a workaround for this, but the real fix would be integrating the patch from #81.

**Comment by monocasual** [comment]
Should be fixed in 0.13.3.

**Comment by synthbox** [comment]
I got the same error:
`src/core/kernelMidi.cpp:28:10: fatal error: 'rtmidi/RtMidi.h' file not found`

This does not seem to help (rtmidi 2.1.1):
`brew install rtmidi`

This is my environment:
- macOS 
- Clion IDE
- Giada 0.14.1
