### ISSUE TITLE
Nasty crashes on OS X El Capitan 10.11.4

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#77]
Official thread: http://www.giadamusic.com/forum/crash-on-launch-el-cap-10-11-4-t1382.html

Unstripped and uncompressed binary for testing purposes: [giada.zip](https://github.com/monocasual/giada/files/277925/giada.zip)

**Comment by Nick-ANFiT** [comment]
Error message:
-- from here --
dyld: Library not loaded: librtmidi.2.1.0.dylib
  Referenced from: /path/giada
  Reason: image not found
Trace/BPT trap
-- to here --

**Comment by monocasual** [comment]
@Nick-ANFiT good, wrong dynamic linking. There's another version that should fix the issue. Let's keep our fingers crossed.
[giada-2016-05-28.zip](https://github.com/monocasual/giada/files/287658/giada-2016-05-28.zip)

**Comment by Nick-ANFiT** [comment]
I tested a binary from giada-2016-05-28.zip.
Giada runs !

This binary shows this message:
-- from here --
% /path/giada ; exit;
JUCE v4.1.0
[init] Giada 0.12.2 - Sat May 28 19:01:31 2016
[Conf::read] unable to read configuration file! Error on line -1: unable to open /Users/USERNAME/Library/Application Support/Giada/giada.conf: No such file or directory
[PluginHost::init] initialize with buffersize=1024, samplerate=44100
-- to here --

But, When I quit giada with command+q key input, This binary shows these error messages.
-- from here --
*** Leaked objects detected: 1 instance(s) of class MessageManager
JUCE Assertion failure in juce_LeakedObjectDetector.h:95
Segmentation fault
logout
-- to here --

**Comment by monocasual** [comment]
Fixed in 0.12.2. I will open a new issue for the segfault on quit.
