### ISSUE TITLE
get rid of mandatory pulse dependency under linux

### ISSUE THREAD

**Issue by mrVanDalo** [monocasual/giada#78]
I wrote an [ebuild](https://gitlab.com/proaudio/proaudio/merge_requests/4/diffs) where I have to patch your 0.12.1 release, to get rid of the pulse-audio dependency.

When I start it, I get a message that there is something wrong with the audio configuration. I configure Jack or Alsa, but nothing happens (the software does not appear in a jack wiring console as well).

When I try to open the config again it crashes with this message

```
[init] Giada 0.12.1 - Sun May 29 13:04:13 2016
Segmentation fault
```

Is it possible that pulse-audio is to tight coupled to your code?

**Comment by monocasual** [comment]
Thanks for reporting. So far Giada has been built always with Pulse included. However at the moment Pulse Audio should not be tightly coupled to the engine, in fact there's a routine that checks if that specific API is available:

```
if (api == SYS_API_PULSE && hasAPI(RtAudio::LINUX_PULSE))
	system = new RtAudio(RtAudio::LINUX_PULSE);
```

(`hasApi(...)` is the important part).

Now, thanks to b1c2f4d335223bff01f6b232f2c925e995aefaab we will be able to customize the build even better. We could try to disable Pulse Audio and see if your crash is reproducible.

**Comment by mrVanDalo** [comment]
Thanks for the quick response.
I'll try to build the master branch without pulse, maybe it's not crashing anymore.

**Comment by mrVanDalo** [comment]
sorry I did not try to build it. but [we](https://github.com/gentoo-audio/audio-overlay) will creat an ebuild sooner or later, and than I would recreate a ticket, so I'll close this one. 

Thanks
