### ISSUE TITLE
Using the dynamics of midi events

### ISSUE THREAD

**Issue by adnion** [monocasual/giada#80]
Hi there,

in "MIDI Input Setup" I can't find a way to use the dynamics of a midi instrument.
The button "learn" saves a hexadecimal number including the volume of a single hit. The sample only gets triggered when I hit this specific volume again.
Having the possibility to use the second midi dataset to play the sample at different volumes would be great.

Best Regards
Nokian

**Comment by monocasual** [comment]
Hi @nokianhunter,

> The button "learn" saves a hexadecimal number including the volume of a single hit. The sample only gets triggered when I hit this specific volume again

This is strange, because we currently we strip off the velocity information, so that you can trigger the channel regardless how "forcefully" you press the key. Just to be 100% sure: do you MIDI learn with the "Device does not send NoteOff" checkbox enabled?

**Comment by nokianhunter** [comment]
Hi @monocasual,
thanks for that hint. You are right. I had this checkbox enabled so I turned it off and it worked!
Nevertheless do you think it makes sense to have a function that saves the velocity information and adjusts the sample volume on each hit?

**Comment by monocasual** [comment]
Well that's an interesting point. Let's see how this -> #57 goes...

**Comment by nokianhunter** [comment]
Just tried 0.13.1.
The setup is straight forward:
- Create a sample channel
- Setup MIDI Input...
- Learn the same MIDI event to the "key press" and the "volume" action
At the moment the "volume" action is ignored, if the "key press" is assigned to the same MIDI event.

**Comment by monocasual** [comment]
@nokianhunter you're right, here's the catch: https://github.com/monocasual/giada/blob/master/src/core/kernelMidi.cpp#L385

KeyPress comes first, so any other event is skipped. We should simply remove the "else" part on each event comparison.

**Comment by nokiann** [comment]
Wouldn't it make sense to make this the default behaviour?
Haven't tested it yet, but I am curious if the volume adjustment really works on the fly (for the hit that triggered it).

**Comment by monocasual** [comment]
@nokiann yes it does, indeed. We are currently working on this, through #104 . Stay tuned :smile:

**Comment by nokiann** [comment]
Just removed the "else" part as you suggested. It worked quite well.
I also tried to get a lower latency.
The interesting thing is that ALSA with 16 buffer size leads to a lower latency than PulseAudio with 16 buffer size.
Jack is probably the best choice but I found it hard to configure and to use it with other audio sources (browser etc.).

Maybe I should also filter the Midi input because on each hit there is a second event who sets the volume back to 0.

**Comment by nokiann** [comment]
I mapped the "key press" and the "volume" event to the same midi event (0x992400).
Sometimes only the volume gets adjusted but the sample is not played at all.
It's not a problem with the Frames/Period setting or with the midi source itself.
I think it's because of the second NoteOn event.
I have to filter it somehow so giada only receives the first useful NoteOn event.

**Comment by nokiann** [comment]
These errors spam my terminal:
`[KM] MIDI received - unknown signal - size=1, value=0xFE
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
`

**Comment by nokiann** [comment]
Console output with a mididings filter
(


):
`[KM] MIDI received - 0x99273100 (chan 9)
  >>> keyPress, ch=1 (pure=0x99270000)
  >>> volume ch=1 (pure=0x99270000, value=49, float=0.385827)
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xFE
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - unknown signal - size=1, value=0xF8
[KM] MIDI received - 0x89274000 (chan 9)
`

Console Output without the filter:

**Comment by nokiann** [comment]
Last days I tried to track down a triggering problem. Sometimes midi events just get lost.

I use qjackctl with MIDI driver "raw" (48k sample rate, 256 frames/sec, 2 periods/buffer).
In commandline I start 
`mididings "Print()" -b jack-rt`  
which basically shows the midi events on commandline.
I connect the midi input to both giada and mididings using patchage.
In giada I load some samples in "Oneshot retrig"-Mode and produce some fast, rythmic midi input.

I watch both commandline outputs and sometimes mididings shows a (correct) event that giada doesn't recognize.

Do you have an idea how to solve this?

**Comment by Punkroku** [comment]
hi i want to modify midi in windows i want to be able to write script to modify input or clone send to multiple channels or scalarmute or random mute notes in cloned midi channel like to add to sound with 2nd instrument in unison or to accent or patch slider same notes in different patches. i know this will increase latency maybe a table array will be fast for note mirroring. In Linux Alsa Library works for this prototype tiny.cc/mpmmm or sourceforge.com/mpmmm email me earl@bitsfit.com

**Comment by adnion** [comment]
> @nokianhunter you're right, here's the catch: https://github.com/monocasual/giada/blob/master/src/core/kernelMidi.cpp#L385
KeyPress comes first, so any other event is skipped. We should simply remove the "else" part on each event comparison.

@monocasual could you please remove the "else" part?

**Comment by adnion** [comment]
I want to unterstand this correctly:
Do all giada users throw away the velocity information of the MIDI input or do they use some kind of MIDI message splitter to generate special velocity messages? Or a special volume adjuster for each input?
I can't believe dynamics is so underrated for a music software.

**Comment by monocasual** [comment]
Hey @adnion , sorry for the delay. We are pretty busy on the upcoming version and its new super-cool sample editor. Don't worry, this issue will not fall off our radar :satellite: 
P.S. 
Pull requests always welcome and encouraged

**Comment by monocasual** [comment]
Closing this, as feature #146 should make the "else" removal hack useless. :boom:
