### ISSUE TITLE
LV2 support

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#83]
It's down to JUCE :) - https://github.com/WeAreROLI/JUCE/issues/123

**Comment by dvzrv** [comment]
I don't think it is worth waiting for JUCE. After more than 8 years of waiting (and no reaction), I think it is quite unrealistic, that this is ever going to happen.

However, there are alternatives, that can be persued, such as: https://github.com/DISTRHO/DPF

**Comment by CarloCattano** [comment]
Hi there . Thanks for working on Giada first of all , its an amazing piece of software . THis lv2 compatibilty would be super nice . Any news on this ?

**Comment by gvnnz** [comment]
Hi @CarloCattano , still waiting for JUCE to implement it. Fingers are crossed...

**Comment by dvzrv** [comment]
As pointed out [earlier](https://github.com/monocasual/giada/issues/83#issuecomment-560001179), this is very unlikely to ever happen: https://github.com/juce-framework/JUCE/issues/123#issuecomment-520725413

It is the more viable option to either use https://github.com/DISTRHO/DPF or https://github.com/DISTRHO/JUCE as upstream JUCE does not seem to be interested at all.

**Comment by gvnnz** [comment]
Surprise surprise... https://github.com/juce-framework/JUCE/issues/123

**Comment by CarloCattano** [comment]
Woha! This could be big, and enrich Giada a lot with the open source lv2 available

**Comment by gvnnz** [comment]
Done in 42f1beb5af369005303169cdd630364a1754170a, closing.
