### ISSUE TITLE
Full Jack transport

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#89]
http://www.giadamusic.com/forum/mute-groups-playlist-scenes-dedicated-outputs-t1399.html

"Giada is already partly Jack Transport master but it still need to pass the BPM to jack and the "rewind " button (back to start) to be fully functional and syncable with other (jack) software."

**Comment by monocasual** [comment]
Useful functions:

* [`jack_transport_reposition`](http://jackaudio.org/files/docs/html/group__TransportControl.html#ga2f371010358add3cbed8454bd0bd2ef8)
* [`jack_transport_locate`](http://jackaudio.org/files/docs/html/group__TransportControl.html#gab3f52a42084aead87fd1ee75ed25b240)
*[`jack_set_timebase_callback`](http://jackaudio.org/files/docs/html/group__TransportControl.html#ga0c2f2f464f6ba1c0b2aa45e6507b7aa9)

Implementation examples:

* https://github.com/musescore/MuseScore/pull/1035/commits/fa509a800b6d8fbdba55f9b7c0b0bac04b083506

**Comment by beatboxchad** [comment]
Nice.

**Comment by sonejostudios** [comment]
Amazing!! thank you very much!
