### ISSUE TITLE
Channel groups

### ISSUE THREAD

**Issue by monocasual** [monocasual/giada#90]
- [x] Clone channels in group
- [x] Delete channels in group
- [x] Clone group channels
- [x] Move channels outside groups
- [x] Move channels within groups
- [x] Move channels into groups
- [x] Move group channels
- [x] Group channels' MIDI I/O
- [x] Persistence

**Comment by tomek-szczesny** [comment]
Updated forum links:
https://www.giadamusic.com/forum/viewtopic.php?f=3&t=1399&p=2495&hilit=groups#p2019
https://www.giadamusic.com/forum/viewtopic.php?f=3&t=148&p=479&hilit=groups#p479

**Comment by monocasual** [comment]
Additional notes from #381 (closed as duplicate of this one):

> I’ve been experimenting using Giada like a MPC to trigger sample chops in Oneshot retrig mode over multiple channels. This has been working pretty well except that there is overlap when triggering samples across channels.
>
> I think it would be a useful feature to have a new mode that is similar to the “Mute Group” functionality in the MPC. This essentially will cut off the audio of a channel when another channel is triggered if they’re in the same group. A possible option would be to create a new mode called “Oneshot retrig grp 1”. Any channels in this mode could then cut each other off.
