### ISSUE TITLE
Compiling for 32 bit windows

### ISSUE THREAD

**Issue by lukeoftheaura** [monocasual/giada#98]
Is it possible to compile giada for 32-bit windows (compiling on a linux computer) and if so, how?

**Comment by monocasual** [comment]
I suppose so, with a cross-compiler, but we never had the chance to do something like that . [This question on Stackoverflow](http://stackoverflow.com/questions/2033997/how-to-compile-for-windows-on-linux-with-gcc-g) might point to the right direction. Any update on this would be nice.
